import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("ships the BTC 5M strategy monitor", async () => {
  const [page, layout, styles, packageJson, viteConfig, readme] = await Promise.all([
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/layout.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
    readFile(new URL("../package.json", import.meta.url), "utf8"),
    readFile(new URL("../vite.config.ts", import.meta.url), "utf8"),
    readFile(new URL("../README.md", import.meta.url), "utf8"),
  ]);
  assert.match(page, /BTC 5M LAB/);
  assert.match(page, /type StrategyView = "live-m0w" \| "research" \| "reliability-shadow" \| "lead-observer" \| "m-series" \| "pair-arb" \| "legacy" \| "paused"/);
  assert.match(page, /useState<StrategyView>\("m-series"\)/);
  assert.match(page, /M 系列主實驗/);
  assert.match(page, /正式實單監視與規則/);
  assert.match(page, /策略、金額與時段門檻可調整/);
  assert.match(page, /REAL MONEY/);
  assert.match(page, /這個分頁只顯示 Binance 正式 Prediction 訂單與獨立實單帳本/);
  assert.match(page, /每市場硬上限/);
  assert.match(page, /MARKET 約需 1\.5 USDT，故一律禁用/);
  assert.match(page, /timeout／5xx 標為不確定，不盲目重送/);
  assert.match(page, /M0 每小時實單閘門/);
  assert.match(page, /本時段暫停下單/);
  assert.match(page, /低於 \{hourlyGuard\.minWinRatePct \?\? 50\}% 即停單/);
  assert.match(page, /超過 \{hourlyGuard\.maxWinThenLossRatePct \?\? 50\}% 即停單/);
  assert.match(page, /剛好 50% 仍允許下單/);
  assert.match(styles, /\.live-hourly-guard\.blocked/);
  assert.match(page, /正式實單規則/);
  assert.match(page, /實單訊號策略/);
  assert.match(page, /策略 \$\{index \+ 1\} 每筆／每組互補單的獨立上限/);
  assert.match(page, /M0 每小時最低勝率/);
  assert.match(page, /M0 一勝一敗率上限/);
  assert.match(page, /apiUrl\("\/api\/live-rules"\)/);
  assert.match(page, /fetchDashboardJson<LiveM0WState \| null>\("\/api\/live-rules", pending\)/);
  assert.match(page, /\/api\/live-rules is a lightweight snapshot/);
  assert.match(page, /\.\.\.\(current\.liveM0W\?\.autoRedeem \?\? \{\}\),\s+\.\.\.\(next\.autoRedeem \?\? \{\}\),/);
  assert.match(page, /等待實單規則載入…/);
  assert.match(page, /disabled=\{!observerSupported\}/);
  assert.match(page, /可先選版本再開啟 Observer/);
  assert.match(page, /確認並套用新規則/);
  assert.match(page, /未儲存草稿會保留在這個瀏覽器/);
  assert.match(page, /LIVE_RULE_DRAFT_STORAGE_KEY/);
  assert.match(page, /window\.localStorage\.setItem/);
  assert.match(page, /window\.addEventListener\("beforeunload"/);
  assert.match(page, /有尚未套用的實單規則草稿/);
  assert.match(page, /rulesDraft=\{liveRulesDraft\}/);
  assert.match(page, /rulesDirty=\{liveRulesDirty\}/);
  assert.match(page, /同一個私有區域網路中的手機也能正式儲存/);
  assert.match(styles, /\.live-rules-editor/);
  assert.match(page, /apiUrl\("\/api\/live-control"\)/);
  assert.match(page, /apiUrl\("\/api\/live-sell"\)/);
  assert.match(page, /X-BTC-Lab-Manual-Exit/);
  assert.match(page, /同一區域網路/);
  assert.match(page, /liveM0W\?: LiveM0WState \| null/);
  assert.match(styles, /\.live-m0w-console/);
  assert.match(styles, /\.live-real-badge/);
  assert.match(page, /const LIVE_TABLE_PAGE_SIZE = 10/);
  assert.match(page, /visibleRedeems = redeems\.slice/);
  assert.match(page, /visibleOrders = orders\.slice/);
  assert.match(page, /visibleRedeems\.map/);
  assert.match(page, /visibleOrders\.map/);
  assert.match(page, /每頁最多 10 筆/);
  assert.match(page, /tablePager\("勝方結算領取"/);
  assert.match(page, /tablePager\("正式訂單、成交與損益"/);
  assert.match(styles, /\.live-table-pager/);
  assert.match(page, /OBSERVATION \+ FAIL-CLOSED M01 GATES/);
  assert.match(page, /暫定狀態/);
  assert.match(page, /RANGE score/);
  assert.match(page, /TREND score/);
  assert.match(page, /Winner Touch Rate 高/);
  assert.match(page, /偏 RANGE／震盪反轉/);
  assert.match(page, /Winner Touch Rate 低/);
  assert.match(page, /偏 TREND／單邊趨勢/);
  assert.match(page, /M01 Conditional Fill Win Rate/);
  assert.match(page, /M01 損益平衡勝率/);
  assert.match(page, /M01 Edge/);
  assert.match(page, /未計交易成本/);
  assert.match(page, /這項歷史期望警示不直接控制實單/);
  assert.match(page, /Median 60s ER/);
  assert.match(page, /Early 60s ER/);
  assert.match(page, /P75 60s ER/);
  assert.match(styles, /\.market-observer-score-strip/);
  assert.match(styles, /\.market-observer-alert/);
  assert.match(page, /M01 時間／市況過濾、Floor／Rebound、M1／M3／M7/);
  assert.match(page, /M01 過濾強度三組對照/);
  assert.match(page, /三組共用同一 market ID、固定種子方向、Ask 價格、可見深度與模擬成交規則/);
  assert.match(page, /被擋交易的反事實結果/);
  assert.match(page, /交易覆蓋率/);
  assert.match(page, /實際成交率/);
  assert.match(page, /Profit Factor/);
  assert.match(page, /最大回撤/);
  assert.match(page, /每日零交易比例/);
  assert.match(styles, /\.m01o-filter-panel/);
  assert.match(page, /個已停止的 \$\{signalFamily\} 出場分支/);
  assert.doesNotMatch(page, /id="m-exit-tab"/);
  assert.doesNotMatch(page, /id="m0-exit-tab"/);
  assert.match(page, /id="research-tab"/);
  assert.match(page, /id="research-panel"/);
  assert.match(page, /id="reliability-shadow-tab"/);
  assert.match(page, /id="reliability-shadow-panel"/);
  assert.match(page, /<ReliabilityShadowPanel \/>/);
  assert.match(page, /模型可靠／失準影子標籤/);
  assert.match(page, /只記錄、不阻擋/);
  assert.match(page, /RC_LOW_ENTRY/);
  assert.match(page, /RC_STALE_QUOTE/);
  assert.match(page, /FL_DIRECTION/);
  assert.match(page, /MP_LATE_WINDOW/);
  assert.match(page, /MP_FRESH_BOOK/);
  assert.match(page, /MP_MIDPRICE_WEAK/);
  assert.match(page, /前向樣本：尚未接入/);
  assert.match(styles, /\.reliability-shadow-panel/);
  assert.match(styles, /repeat\(8,minmax\(0,1fr\)\)/);
  assert.match(page, /id="lead-observer-tab"/);
  assert.match(page, /id="lead-observer-panel"/);
  assert.match(page, /<FuturesLeadObserverPanel data=\{state\.researchForward\}/);
  assert.match(page, /R_FUTURES_LEAD_OBSERVER_F1/);
  assert.match(page, /R_FUTURES_LEAD_OBSERVER_V2/);
  assert.match(page, /R_FUTURES_LEAD_OBSERVER_V3/);
  assert.match(page, /R_FUTURES_LEAD_OBSERVER_V4/);
  assert.match(page, /R_FUTURES_LEAD_OBSERVER_V6/);
  assert.match(page, /R_OFI_OBSERVER_V3/);
  assert.match(page, /R_MICROPRICE_OBSERVER_V3/);
  assert.match(page, /R_MICROPRICE_OBSERVER_V6/);
  assert.match(page, /R_CALIBRATED_VALUE_OBSERVER_V6/);
  assert.match(page, /R_OFI \+ V3/);
  assert.match(page, /R_MICROPRICE \+ V3/);
  assert.match(page, /R_MICROPRICE \+ V6/);
  assert.match(page, /R_CALIBRATED_VALUE \+ V6/);
  assert.match(page, /OBSERVER · NINE INDEPENDENT SHADOWS/);
  assert.match(page, /trade\.strategy\.includes\("_OBSERVER_"\)/);
  assert.match(page, /api\/trades\/futures-lead-observer\?page=\$\{observerTradePageNumber\}/);
  assert.match(page, /observerTradePage\.trades/);
  assert.match(page, /SQLite 完整歷史共/);
  assert.match(page, /每頁固定 10 筆/);
  assert.match(page, /九組 Observer 模擬交易分頁/);
  assert.match(page, /策略 \$\{index \+ 1\} 是否使用 Observer/);
  assert.match(page, /策略 \$\{index \+ 1\} Observer 版本/);
  assert.match(page, /實單策略 \{index \+ 1\}/);
  assert.match(page, /strategyObserverEnabled/);
  assert.match(page, /strategyObserverVersions/);
  assert.match(page, /strategyLossCooldownEnabled/);
  assert.match(page, /兩連敗冷卻/);
  assert.match(page, /連敗兩次後跳過下一市場/);
  assert.match(page, /R_OFI: "研究實單 · 10 秒訂單流不平衡"/);
  assert.match(page, /R_CALIBRATED_VALUE: "研究實單 · 校準機率價值"/);
  assert.match(page, /<ResearchForwardPanel data=\{state\.researchForward\}/);
  assert.match(page, /R_MICROPRICE/);
  assert.match(page, /R_MICROPRICE: "研究實單 · Microprice 深度失衡"/);
  assert.match(page, /R_OFI/);
  assert.match(page, /R_OFI_MIN040/);
  assert.match(page, /R_OFI_EVENT_CUM/);
  assert.match(page, /R_OFI_EVENT_CUM_FILTERED/);
  assert.match(page, /R_FUTURES_LEAD_REVERSE/);
  assert.match(page, /R_FUTURES_LEAD_REGIME_REVERSE_3L/);
  assert.match(page, /目前有效：/);
  assert.match(page, /強制正方向/);
  assert.match(page, /強制反方向/);
  assert.match(page, /strategy_r_futures_lead_regime_reverse_3l_direction_mode/);
  assert.match(page, /R_FUTURES_LEAD_EXIT30/);
  assert.match(page, /R_FUTURES_LEAD_DISTANCE/);
  assert.match(page, /R_FUTURES_LEAD_EXIT30_DISTANCE/);
  assert.match(page, /五組主策略＋八組獨立 Shadow/);
  assert.match(page, /固定 chronological cohort/);
  assert.match(page, /R_FUTURES_LEAD/);
  assert.match(page, /R_CALIBRATED_VALUE/);
  assert.match(page, /R_CONSENSUS/);
  assert.match(page, /<MExitExperimentPanel data=\{state\.mExitExperiment\} signalFamily="M" variantSuffixes=\{ALL_MX_SUFFIXES\} pausedView/);
  assert.match(page, /<MExitExperimentPanel data=\{state\.m0ExitExperiment\} signalFamily="M0" variantSuffixes=\{ALL_MX_SUFFIXES\} pausedView/);
  assert.match(page, /mExitExperiment\?: MExitExperimentState \| null/);
  assert.match(page, /m0ExitExperiment\?: MExitExperimentState \| null/);
  assert.match(page, /停止整個 \$\{signalFamily\} 出場分支系列/);
  assert.match(page, /id="pair-arb-tab"/);
  assert.match(page, /id="pair-arb-panel"/);
  assert.match(page, /<PairArbPanel data=\{state\.pairArbExperiment\}/);
  assert.match(page, /pairArbExperiment\?: PairArbState \| null/);
  assert.match(page, /UP＋DOWN 互補鎖利測試/);
  assert.match(page, /PAIR_ARB_010/);
  assert.match(page, /PAIR_ARB_020/);
  assert.match(page, /每腿滑點 0\.005/);
  assert.match(page, /strategy_pair_arb_stake/);
  assert.match(page, /F1 · Observer 判斷 M01 進場/);
  assert.match(page, /F1 門檻才會影響新實單/);
  assert.match(page, /互補評估診斷/);
  assert.match(page, /雙簿資料已接通/);
  assert.match(page, /independent UP／DOWN outcome token 訂單簿|獨立 UP／DOWN outcome token 訂單簿/);
  assert.match(styles, /repeat\(7,minmax\(0,1fr\)\)/);
  for (const suffix of ["T60", "T70", "T80", "T90", "T98", "P50", "P10", "REV"]) {
    assert.match(page, new RegExp(`suffix: "${suffix}"`));
  }
  assert.match(page, /開盤後前 10 秒建立限價不高於 0\.50 的進場 intent/);
  assert.match(page, /EXPIRED_UNFILLED 或 EXPIRED_PARTIAL/);
  assert.match(page, /ask 高於 0\.50 不買/);
  assert.match(page, /固定 0\.60 全倉止盈/);
  assert.match(page, /固定 0\.70 全倉止盈/);
  assert.match(page, /固定 0\.80 全倉止盈/);
  assert.match(page, /固定 0\.90 全倉止盈/);
  assert.match(page, /固定 0\.98 全倉止盈/);
  assert.match(page, /每上漲 50% 賣一半/);
  assert.match(page, /每上漲 10% 賣 10%/);
  assert.match(page, /反向穿越正式 startPrice/);
  assert.match(page, /bid 先站上 0\.50、再跌回 0\.50 以下/);
  for (const field of [
    "realizedPnl", "openPositions", "trades", "wins", "losses", "requestedEntryQty", "filledEntryQty",
    "requestedExitQty", "filledExitQty", "entryFillRatio", "exitFillRatio",
    "fullyUnfilledIntentRatio", "partialFillIntentRatio", "remainingShares",
  ]) {
    assert.match(page, new RegExp(`${field}\\?:`));
  }
  assert.match(page, /進場填單率/);
  assert.match(page, /出場填單率/);
  assert.match(page, /已成交交易/);
  assert.match(page, /勝 \/ 負/);
  assert.match(page, /完全未成交 intent 不計/);
  assert.match(page, /未平倉暫不判定/);
  assert.match(page, /完全未成交 intent/);
  assert.match(page, /部分成交 intent/);
  assert.match(page, /未平倉部位/);
  assert.match(page, /委託與未成交明細/);
  assert.match(page, /部分成交紀錄/);
  assert.match(page, /舊策略 A–L/);
  assert.match(page, /既有未平倉仍會正常結算，歷史資料也不會刪除/);
  assert.match(page, /盤中反彈差價/);
  assert.match(page, /尾盤高機率/);
  assert.match(page, /strategy_b_stop_loss_price/);
  assert.match(page, /每筆使用固定本金/);
  assert.match(page, /最佳買價嚴格低於/);
  assert.match(page, /stopPrice\.toFixed\(2\)/);
  assert.match(page, /最佳買量足以完整退出/);
  assert.match(page, /損益同時扣除進場與出場費用/);
  assert.doesNotMatch(page, /strategy B[^\n]*無條件持有到結算/);
  assert.match(page, /尾盤動態加碼止損/);
  assert.match(page, /<StrategyCard id="B2"/);
  assert.match(page, /strategy_b2_last_seconds/);
  assert.match(page, /strategy_b2_min_seconds_left/);
  assert.match(page, /strategy_b2_min_price/);
  assert.match(page, /strategy_b2_max_price/);
  assert.match(page, /strategy_b2_min_stake/);
  assert.match(page, /strategy_b2_max_stake/);
  assert.match(page, /strategy_b2_size_curve/);
  assert.match(page, /strategy_b2_stop_loss_price/);
  assert.match(page, /本金依剩餘時間由最低值逐步增加到最高值/);
  assert.match(page, /低於 3 秒不再開新倉/);
  assert.match(page, /可見買量足以完整退出/);
  assert.match(page, /首次觀測到同側最佳買價低於 0\.60/);
  assert.match(page, /待驗證的時間風險假設/);
  assert.match(page, /現貨＋市場確認動能/);
  assert.match(page, /嚴格時間套利/);
  assert.match(page, /波動標準化動能/);
  assert.match(page, /保守機率淨優勢/);
  assert.match(page, /尾盤逆轉狙擊偵測/);
  assert.match(page, /賭狗策略/);
  assert.match(page, /尾盤賭狗反彈價差/);
  assert.match(page, /基差校正終局勝率/);
  assert.match(page, /逆轉狙擊偵測器先等待連續 2 局/);
  assert.match(page, /strategy_e_min_baseline_seconds_left/);
  assert.match(page, /strategy_e2_min_move_z/);
  assert.match(page, /strategy_e2_min_return_samples/);
  assert.match(page, /strategy_e2_max_book_age_ms/);
  assert.match(page, /strategy_g_probability_shrinkage/);
  assert.match(page, /strategy_g_uncertainty_margin/);
  assert.match(page, /strategy_g_max_book_skew_ms/);
  assert.match(page, /strategy_g_max_book_age_ms/);
  assert.match(page, /strategy_h_leader_min_price/);
  assert.match(page, /strategy_h_reversal_seconds/);
  assert.match(page, /strategy_h_anchor_lookback_seconds/);
  assert.match(page, /strategy_h_entry_window_seconds/);
  assert.match(page, /strategy_h_max_entry/);
  assert.match(page, /strategy_h_required_reversals/);
  assert.match(page, /strategy_h_max_consecutive_losses/);
  assert.match(page, /最近一筆送單總延遲/);
  assert.match(page, /quote→送出/);
  assert.match(page, /strategy_h_max_book_skew_ms/);
  assert.match(page, /strategy_h_max_book_age_ms/);
  assert.match(page, /strategy_h_stake/);
  assert.match(page, /<StrategyCard id="I"/);
  assert.match(page, /strategy_i_max_entry/);
  assert.match(page, /strategy_i_stake/);
  assert.match(page, /strategy_i_min_seconds_left/);
  assert.match(page, /strategy_i_max_book_skew_ms/);
  assert.match(page, /strategy_i_max_book_age_ms/);
  assert.match(page, /<StrategyCard id="J"/);
  assert.match(page, /strategy_j_window_seconds/);
  assert.match(page, /strategy_j_min_seconds_left/);
  assert.match(page, /strategy_j_min_gap/);
  assert.match(page, /strategy_j_max_entry/);
  assert.match(page, /strategy_j_target_multiplier/);
  assert.match(page, /strategy_j_max_book_skew_ms/);
  assert.match(page, /strategy_j_max_book_age_ms/);
  assert.match(page, /strategy_j_stake/);
  assert.match(page, /<StrategyCard id="K"/);
  assert.match(page, /strategy_k_max_seconds_left/);
  assert.match(page, /strategy_k_min_seconds_left/);
  assert.match(page, /strategy_k_min_baseline_seconds_left/);
  assert.match(page, /strategy_k_lookback_observations/);
  assert.match(page, /strategy_k_min_return_samples/);
  assert.match(page, /strategy_k_sigma_floor/);
  assert.match(page, /strategy_k_basis_uncertainty_bps/);
  assert.match(page, /strategy_k_calibration_slope/);
  assert.match(page, /strategy_k_min_probability/);
  assert.match(page, /strategy_k_latency_seconds/);
  assert.match(page, /strategy_k_min_net_edge/);
  assert.match(page, /strategy_k_max_spread/);
  assert.match(page, /strategy_k_spread_edge_multiplier/);
  assert.match(page, /strategy_k_slippage_bps/);
  assert.match(page, /strategy_k_max_book_skew_ms/);
  assert.match(page, /strategy_k_max_book_age_ms/);
  assert.match(page, /strategy_k_stake/);
  assert.match(page, /strategy_k_max_seconds_left \?\? 180/);
  assert.match(page, /strategy_k_min_seconds_left \?\? 20/);
  assert.match(page, /strategy_k_basis_uncertainty_bps \?\? 1\.5/);
  assert.match(page, /strategy_k_calibration_slope \?\? \.5/);
  assert.match(page, /strategy_k_min_probability \?\? \.65/);
  assert.doesNotMatch(page, /strategy_k_probability_shrinkage|strategy_k_uncertainty_margin/);
  assert.match(page, /<StrategyCard id="L"/);
  assert.match(page, /雙向前段反彈/);
  assert.match(page, /strategy_l_window_seconds/);
  assert.match(page, /strategy_l_max_entry/);
  assert.match(page, /strategy_l_target/);
  assert.match(page, /strategy_l_total_stake/);
  assert.match(page, /strategy_l_max_book_skew_ms/);
  assert.match(page, /strategy_l_max_book_age_ms/);
  assert.match(page, /strategy_l_window_seconds \?\? 60/);
  assert.match(page, /strategy_l_max_entry \?\? \.5/);
  assert.match(page, /strategy_l_target \?\? \.7/);
  assert.match(page, /strategy_l_total_stake \?\? 10/);
  assert.match(page, /strategy_l_max_book_skew_ms \?\? 500/);
  assert.match(page, /strategy_l_max_book_age_ms \?\? 2000/);
  assert.match(page, /兩腿互相獨立，可在不同時間成交/);
  assert.match(page, /每腿最多使用總本金的一半/);
  assert.match(page, /實際本金可能低於半額上限/);
  assert.match(page, /相同 USDT 也不代表取得相同 shares/);
  assert.match(page, /同側第一檔買量足以完整退出/);
  assert.match(page, /以目標價 \$\{target\.toFixed\(2\)\} 模擬賣出/);
  assert.match(page, /未達目標或深度不足的腿持有到正式結算/);
  assert.match(page, /摘要的交易數以每一腿分別計算/);
  assert.match(page, /雙邊都買不是無風險或保證套利/);
  assert.match(page, /若要從完整一輪開始量測/);
  assert.match(page, /<StrategyCard id="M"/);
  assert.match(page, /開盤方向盲單/);
  assert.match(page, /strategy_m_entry_window_seconds/);
  assert.match(page, /strategy_m_stake/);
  assert.match(page, /fields = mFields\("m"\)/);
  assert.match(page, /strategy_m_entry_window_seconds \?\? 10/);
  assert.match(page, /strategy_m_stake \?\? 10/);
  assert.match(page, /WS 事件驅動引擎收到第一個有效且非零/);
  assert.match(page, /舊版每秒策略交易由後端 strategy_version 分開保留/);
  assert.match(page, /正數買 UP、負數買 DOWN、相等則等待下一筆 Spot trade 事件/);
  assert.match(page, /不代表 Prediction 上游每 1 ms 更新/);
  assert.match(page, /固定基差也可能讓方向長期偏向一側/);
  assert.match(page, /Prediction 報價不參與方向或勝率判斷/);
  assert.match(page, /也沒有買價上限/);
  assert.match(page, /ask 即使接近 1 仍可能買入/);
  assert.match(page, /有多少成交多少/);
  assert.match(page, /持有到正式結算/);
  assert.match(page, /因此不是勝率模型/);
  for (const id of ["M0", "M01", "M01T180", "M01T180D", "M01TASYM", "M01O", "M01O_F1", "M01O_LIVE", "M01F", "M01R", "M0W", "M01W", "M1", "M2", "M3", "M4", "M5", "M6", "M7_1", "M7_2", "M7_3", "M7_5"]) {
    assert.match(page, new RegExp(`<StrategyCard id="${id}"`));
  }
  assert.match(page, /18 ACTIVE OBSERVATION IDS/);
  assert.match(page, /其餘每個 ID 仍有自己的交易摘要與歸零起點/);
  assert.match(page, /Prediction 訂單簿只負責模擬執行/);
  assert.match(page, /固定種子隨機基準/);
  for (const field of ["currentWinStreak", "averageWinStreak", "currentLossStreak", "averageLossStreak", "averageWinLossCycleStreak"]) {
    assert.match(page, new RegExp(`${field}\\?:`));
  }
  assert.match(page, /目前連續命中/);
  assert.match(page, /平均連續命中/);
  assert.match(page, /目前連續失敗/);
  assert.match(page, /平均連續失敗/);
  assert.match(page, /一勝一敗平均連續/);
  for (const field of ["winThenLossCount", "winThenLossOpportunities", "winThenLossRatePct"]) {
    assert.match(page, new RegExp(field));
  }
  assert.match(page, /m0-hourly-patterns/);
  assert.match(page, /平均連勝/);
  assert.match(page, /平均連敗/);
  assert.match(page, /一勝一敗率/);
  assert.match(page, /上一個相鄰 M0 勝、本局敗/);
  assert.match(page, /M0 低價等待進場/);
  assert.match(page, /整個設定窗口內只觀察選定側/);
  assert.match(page, /maxEntry\.toFixed\(2\)/);
  assert.match(page, /strategy_m01_max_entry/);
  assert.match(page, /M01-T180 時間門檻對照/);
  assert.match(page, /只在剩餘時間嚴格大於/);
  assert.match(page, /strategy_m01t180_min_seconds_left/);
  assert.match(page, /可在正式實單規則中單獨選用/);
  assert.match(page, /M01T180 · 剩餘 >180 秒等 0\.30/);
  assert.match(page, /F2 嚴格過濾/);
  assert.match(page, /F1 寬鬆過濾/);
  assert.match(page, /LIVE 當輪優先/);
  assert.match(page, /strategy_m01o_max_entry/);
  assert.match(page, /strategy_m01o_min_observer_samples/);
  assert.match(page, /目前可放行/);
  assert.match(page, /目前阻擋/);
  assert.match(page, /指標尚未成熟記為 NOT_READY/);
  assert.match(page, /行情缺失或延遲才記為 MISSING_OR_STALE/);
  assert.match(page, /開盤 0～60 秒以雙邊觸及 \+2/);
  assert.match(page, /滿 60 秒後改用 Median 60s ER/);
  assert.match(page, /至少兩筆跨時 60s ER 觀測/);
  assert.match(page, /絕不送進正式實單/);
  assert.match(page, /M01-Floor 價格下限對照/);
  assert.match(page, /M01 價格下限對照組/);
  assert.match(page, /strategy_m01f_min_entry/);
  assert.match(page, /strategy_m01f_max_entry/);
  assert.match(page, /不會送進實單執行器/);
  assert.match(page, /M01-Rebound 低價反彈/);
  assert.match(page, /M0 方向低價反彈觸發/);
  assert.match(page, /strategy_m01r_max_anchor/);
  assert.match(page, /strategy_m01r_rebound/);
  assert.match(page, /0\.10→0\.20 或 0\.30→0\.40/);
  assert.match(page, /M0 命中續買版/);
  assert.match(page, /上一盤 M0 已經結算且命中/);
  assert.match(page, /fields = mFields\("m0w"\)/);
  assert.match(page, /M0 命中低價等待版/);
  assert.match(page, /strategy_m01w_max_entry/);
  assert.match(page, /上一盤 M0 失敗、未知或沒有交易就不監掛、不買/);
  assert.match(page, /不再依賴上一盤 M01 是否成交/);
  assert.match(page, /永遠 UP 基準/);
  assert.match(page, /原 M 的獨立複本/);
  assert.match(page, /門檻偏離版/);
  assert.match(page, /連續確認版/);
  assert.match(page, /perpetual aggTrade／last traded price/);
  assert.match(page, /不使用較慢的 markPrice/);
  assert.match(page, /與策略開關（toggle）無關的 canonical WS 資料/);
  assert.match(page, /只使用已完成的前序市場/);
  assert.match(page, /累積至少 \$\{minSamples\.toFixed\(0\)\} 個市場/);
  assert.match(page, /凍結跨輪 running mean/);
  assert.match(page, /當輪資料不回寫到自己的基準/);
  assert.match(page, /strategy_m0_seed/);
  assert.match(page, /strategy_m3_min_abs_delta_bps/);
  assert.match(page, /strategy_m4_required_observations/);
  assert.match(page, /strategy_m6_min_basis_samples/);
  assert.ok(page.includes('name={`strategy_${key}_entry_window_seconds`}'));
  assert.ok(page.includes('name={`strategy_${key}_stake`}'));
  assert.ok(page.includes('name={`strategy_${key}_max_book_skew_ms`}'));
  assert.ok(page.includes('name={`strategy_${key}_max_book_age_ms`}'));
  assert.match(page, /onConfig\(`\$\{prefix\}_enabled`, !enabled\)/);
  assert.match(page, /M7 ABSOLUTE DEADLINES/);
  assert.match(page, /四個開盤絕對 deadline/);
  assert.match(page, /市場開盤後絕對 \+1／\+2／\+3／\+5 秒/);
  assert.match(page, /deadline 前最後一筆且年齡不超過 1 秒的 Spot trade/);
  assert.match(page, /deadline 後第一筆有效 Prediction 簿事件於執行寬限內成交/);
  assert.match(page, /四組方向可以不同/);
  assert.match(page, /不是首次 M2 或 Spot 訊號後再延遲/);
  assert.match(page, /M7 共用進場窗/);
  assert.match(page, /strategy_m7_stake/);
  assert.match(page, /fields = mFields\("m7"/);
  assert.match(page, /strategy_m7_execution_grace_seconds/);
  assert.doesNotMatch(page, /strategy_m7_[1235]_entry_window_seconds/);
  assert.match(page, /type StrategyId = "A" \| "B" \| "B2" \| "C" \| "D" \| "E" \| "F" \| "E2" \| "G" \| "H" \| "I" \| "J" \| "K" \| "L" \| "M"/);
  assert.match(page, /\| "M0" \| "M01" \| "M01T180" \| "M01T180D" \| "M01TASYM" \| "M01O" \| "M01O_F1" \| "M01O_LIVE" \| "M01F" \| "M01R" \| "M0W" \| "M01W" \| "M1" \| "M2" \| "M3" \| "M4" \| "M5" \| "M6" \| "M7_1" \| "M7_2" \| "M7_3" \| "M7_5"/);
  assert.match(page, /strategyH\?\.reversalStreak/);
  assert.match(page, /strategyH\?\.lossStreak/);
  assert.match(page, /strategyH\?\.pendingOfficialSettlements/);
  assert.match(page, /已武裝/);
  assert.match(page, /偵測中/);
  assert.match(page, /待正式結算/);
  assert.match(page, /不會把 0\.01 本身視為狙擊證據/);
  assert.match(page, /只在剩餘時間大於 3 秒時/);
  assert.match(page, /最後 3 秒一律跳過/);
  assert.match(page, /承接最佳賣價上任何可見的正數數量/);
  assert.match(page, /本金設定僅為上限/);
  assert.match(page, /帳本本金與損益依實際部分成交計算/);
  assert.equal([...page.matchAll(/label="本金上限"/g)].length, 3);
  assert.match(page, /不代表具有正期望值或交易優勢/);
  assert.match(page, /只在最後 120 秒且剩餘時間大於 3 秒時/);
  assert.match(page, /以實際買價的 2 倍出場/);
  assert.match(page, /未達目標則持有到正式結算/);
  assert.match(page, /交易方向與模型勝率只由開盤基差校正後的現貨距離、剩餘時間及實現波動決定/);
  assert.match(page, /訂單價格不參與方向或勝率判斷/);
  assert.doesNotMatch(page, /必須有足夠的可見深度|必須使用新鮮且有足夠可見深度/);
  assert.match(page, /微結構即時觀測器/);
  assert.match(page, /觀測，不下單/);
  assert.match(page, /各來源更新頻率不同，不代表上游行情為 1 ms/);
  assert.match(page, /type MicrostructureState/);
  assert.match(page, /microstructure\?: MicrostructureState \| null/);
  assert.match(page, /type MRealtimeState/);
  assert.match(page, /mRealtime\?: MRealtimeState \| null/);
  for (const field of [
    "status", "mode", "paperOnly", "marketId", "eventRate", "queueDepth",
    "processedEvents", "droppedEvents", "evaluations", "lastEventAt", "lastDecisionAt",
    "lastQueueDelayMs", "lastDecisionDurationMs", "spotAgeMs", "futuresAgeMs",
    "predictionBookAgeMs", "schedulerTickMs", "error",
  ]) {
    assert.match(page, new RegExp(`${field}\\?:`));
  }
  assert.match(page, /<MRealtimePanel data=\{state\.mRealtime\}/);
  assert.match(page, /WS 毫秒實驗引擎/);
  assert.match(page, /EVENT-DRIVEN · PAPER ONLY/);
  assert.match(page, /網站每 1 秒只刷新監察畫面，不會把策略降成每秒執行/);
  assert.match(page, /Prediction 上游更新並非 1 ms/);
  assert.match(page, /市場 \/ 事件率/);
  assert.match(page, /lastQueueDelayMs/);
  assert.match(page, /lastDecisionDurationMs/);
  assert.match(page, /schedulerTickMs/);
  assert.match(page, /predictionBookAgeMs/);
  assert.match(page, /毫秒 timestamp 與延遲欄位/);
  for (const field of [
    "observed_timestamp_ms", "up_book_timestamp_ms", "down_book_timestamp_ms",
    "book_age_ms", "book_skew_ms", "collection_latency_ms", "futures_price",
    "futures_timestamp_ms", "futures_age_ms", "futures_agg_trade_id",
  ]) {
    assert.match(page, new RegExp(field));
  }
  assert.match(page, /只顯示 API 實際提供的 timestamp／latency/);
  assert.match(page, /不代表上游行情具備毫秒精度/);
  assert.match(page, /function TradeTiming/);
  for (const field of [
    "signal_timestamp", "execution_timestamp", "requested_delay_seconds",
    "actual_delay_seconds", "execution_lag_seconds",
  ]) {
    assert.match(page, new RegExp(field));
  }
  assert.match(page, /本機策略 diagnostics，不代表上游行情延遲/);
  assert.match(page, /Binance 現貨/);
  assert.match(page, /USDT 永續/);
  assert.match(page, /Prediction 訂單簿/);
  assert.match(page, /event\/s/);
  assert.match(page, /transportLatencyMs/);
  assert.match(page, /校正延遲/);
  assert.match(page, /表觀延遲/);
  assert.match(page, /spotMicroprice/);
  assert.match(page, /spotQueueImbalance/);
  assert.match(page, /spotTakerImbalance250ms/);
  assert.match(page, /futuresMicroprice/);
  assert.match(page, /futuresQueueImbalance/);
  assert.match(page, /futuresTakerImbalance1s/);
  assert.match(page, /perpSpotBasisBps/);
  assert.match(page, /predictionRemovalDirection/);
  assert.match(page, /predictionRemovalStrength/);
  assert.match(page, /波動警報/);
  assert.match(page, /方向偏差/);
  assert.match(page, /最近流動性移除/);
  assert.match(page, /dbBytes/);
  assert.match(page, /eventsRows/);
  assert.match(page, /snapshotsRows/);
  assert.match(page, /liquidityRows/);
  assert.match(page, /rawRetentionHours/);
  assert.match(page, /snapshotRetentionHours/);
  assert.match(page, /<MicrostructureMonitor data=\{state\.microstructure\}/);
  assert.match(styles, /strategy-pill\.sH/);
  assert.match(styles, /strategy-pill\.sB2/);
  assert.match(styles, /strategy-pill\.sI/);
  assert.match(styles, /strategy-pill\.sJ/);
  assert.match(styles, /strategy-pill\.sK/);
  assert.match(styles, /strategy-pill\.sL/);
  assert.match(styles, /strategy-pill\.sM/);
  assert.match(styles, /strategy-card\.teal/);
  assert.match(styles, /strategy-card\.green/);
  assert.match(styles, /strategy-card\.silver/);
  assert.match(styles, /strategy-card\.orange/);
  assert.match(styles, /trade-status\.stop_loss_exit/);
  assert.match(styles, /strategy-state\.armed/);
  assert.match(styles, /\.micro-panel/);
  assert.match(styles, /\.micro-stream-grid/);
  assert.match(styles, /\.micro-measure-grid/);
  assert.match(styles, /\.liquidity-row/);
  assert.match(styles, /\.strategy-tabs/);
  assert.match(page, /id="paused-tab"/);
  assert.match(page, /id="paused-panel"/);
  assert.match(page, /暫時停止觀測/);
  assert.match(page, /TEMPORARILY_STOPPED_THRESHOLD_USDT = -500/);
  assert.match(page, /TEMPORARILY_STOPPED_STRATEGIES: StrategyId\[\] = \["A", "C", "D", "J", "L", "M", "M2", "M4", "M5", "M6"\]/);
  assert.match(page, /ALL_MX_SUFFIXES = \["T60", "T70", "T80", "T90", "T98", "P50", "P10", "REV"\]/);
  assert.match(page, /variantSuffixes=\{ALL_MX_SUFFIXES\} pausedView/);
  assert.match(page, /停止後不再建立新模擬交易/);
  assert.match(styles, /\.strategy-tabs button\.paused/);
  assert.match(styles, /\.paused-observation-intro/);
  assert.match(styles, /\.timing-panel/);
  assert.match(styles, /\.m-realtime-panel/);
  assert.match(styles, /\.m-realtime-grid/);
  assert.match(styles, /\.m7-family/);
  assert.match(styles, /\.m-exit-summary-grid/);
  assert.match(styles, /\.m-exit-fill-grid/);
  assert.match(styles, /\.m-exit-details/);
  assert.match(styles, /\.m-exit-table/);
  assert.match(page, /含費配對上限/);
  assert.match(page, /const key = strict \? "f" : "d"/);
  assert.match(page, /fetchDashboardJson<RealtimeState>\("\/api\/realtime", pending\)/);
  assert.match(page, /const REALTIME_REFRESH_MS = 1000/);
  assert.match(page, /const STATISTICS_REFRESH_MS = 15000/);
  assert.match(page, /const MEMORY_RECYCLE_MS = 30 \* 60 \* 1000/);
  assert.match(page, /window\.setTimeout\(recycleMemory, MEMORY_RECYCLE_MS\)/);
  assert.match(page, /memoryRecycleInProgress\.current = true/);
  assert.match(page, /if \(memoryRecycleInProgress\.current\) return/);
  assert.match(page, /window\.location\.reload\(\)/);
  assert.match(page, /document\.visibilityState === "visible"/);
  assert.match(page, /abortPendingRequests\(pending\)/);
  assert.match(page, /頁面每 30 分鐘自動回收記憶體/);
  assert.match(page, /window\.setInterval\(loadRealtime, REALTIME_REFRESH_MS\)/);
  assert.match(page, /window\.setInterval\(loadStatistics, STATISTICS_REFRESH_MS\)/);
  assert.match(page, /apiUrl\("\/api\/config"\)/);
  assert.match(page, /resetAt\?: string \| null/);
  assert.match(page, /carriedOpen\?: number/);
  assert.match(page, /totalOpen\?: number/);
  assert.match(page, /cutoffTradeId\?: number \| null/);
  assert.match(page, /測量起點/);
  assert.match(page, /歸零已實現收益/);
  assert.match(page, /從現在重新計算/);
  assert.match(page, /只重設摘要基準，不刪除歷史交易/);
  assert.match(page, /承接未平倉 \{summary\.carriedOpen\} 筆/);
  assert.match(page, /不納入本輪績效/);
  assert.match(page, /目前全部未平倉/);
  assert.match(page, /type="button" onClick=\{\(\) => onReset\(id\)\}/);
  assert.match(page, /window\.confirm/);
  assert.match(page, /apiUrl\("\/api\/strategy-reset"\)/);
  assert.match(page, /body: JSON\.stringify\(\{ strategy \}\)/);
  assert.match(page, /window\.location\.reload\(\)/);
  assert.match(page, /resetState\?\.status === "loading"/);
  assert.match(page, /role=\{resetState\.status === "error" \? "alert" : "status"\}/);
  assert.match(styles, /\.summary-reset/);
  assert.match(styles, /\.reset-notice\.error/);
  assert.match(styles, /\.carried-open/);
  assert.match(styles, /\.summary-reset>button:focus-visible/);
  assert.match(readme, /過去的交易與原始損益仍完整保留/);
  assert.match(readme, /POST \/api\/strategy-reset/);
  assert.match(page, /window\.location\.hostname/);
  assert.match(page, /:8766\$\{path\}/);
  assert.match(packageJson, /vinext dev --hostname 0\.0\.0\.0 --port 4310/);
  assert.match(viteConfig, /host: "0\.0\.0\.0"/);
  assert.match(viteConfig, /port: 4310/);
  assert.doesNotMatch(page, /127\.0\.0\.1:8766/);
  assert.match(layout, /BTC 5M Lab · M 系列模擬實驗/);
  assert.match(layout, /22 個獨立 M 系列 ID/);
  assert.match(layout, /1／2／3／5 秒延遲實驗/);
  assert.match(layout, /保留 A–L 舊策略/);
  assert.doesNotMatch(layout, /十五條/);
  assert.match(readme, /全部 23 個 M 系列 ID 與 A～L 舊策略仍保留/);
  assert.match(readme, /已實現收益不高於 -500 USDT/);
  assert.match(readme, /策略 M01（M0 低價等待進場）/);
  assert.match(readme, /M01 過濾強度對照的三組統計帳本都維持紙上交易/);
  assert.match(readme, /`M01O_F1` 是 F1 寬鬆組/);
  assert.match(readme, /`M01O_LIVE` 是 LIVE 當輪優先組/);
  assert.match(readme, /至少累積 200 輪、最好 300 輪後再判讀/);
  assert.match(readme, /策略 M01-Floor（價格下限對照/);
  assert.match(readme, /策略 M01-Rebound（低價反彈/);
  assert.match(readme, /策略 M0W（M0 命中續買）/);
  assert.match(readme, /策略 M01W（M0 命中低價等待）/);
  assert.match(readme, /M 出場分支 MX_T60、MX_T80、MX_T98/);
  assert.match(readme, /進場限價上限固定為 0\.50/);
  assert.match(readme, /完全未成交的 intent 標記為 `EXPIRED_UNFILLED`/);
  assert.match(readme, /`MX_T60`、`MX_T70`、`MX_T80`、`MX_T90`、`MX_T98`/);
  assert.match(readme, /`MX_P50`/);
  assert.match(readme, /`MX_P10`/);
  assert.match(readme, /`MX_REV`/);
  assert.match(readme, /fullyUnfilledIntentRatio, partialFillIntentRatio/);
  assert.match(readme, /未平倉部位、委託／未成交 intent、實際模擬 fills/);
  assert.match(readme, /其餘 M 系列、M／M0 出場分支與舊策略分頁繼續觀測/);
  assert.match(readme, /網站的 1 秒刷新只影響畫面，不會把後端策略降成每秒執行/);
  assert.match(readme, /策略 L（實驗，雙向前段反彈）/);
  assert.match(readme, /strategy_l_total_stake/);
  assert.match(readme, /策略 M（原始策略的 WS 事件驅動版，開盤方向盲單）/);
  assert.match(readme, /舊版每秒策略交易由後端 `strategy_version` 分開保留/);
  assert.match(readme, /strategy_m_entry_window_seconds/);
  assert.match(readme, /策略 M0（固定種子隨機基準）/);
  assert.match(readme, /策略 M1（永遠 UP 基準）/);
  assert.match(readme, /策略 M2（首次非零偏離）/);
  assert.match(readme, /策略 M3（門檻偏離）/);
  assert.match(readme, /策略 M4（連續方向確認）/);
  assert.match(readme, /不同 Binance Spot trade 事件/);
  assert.match(readme, /策略 M5（永續成交方向）/);
  assert.match(readme, /策略 M6（歷史基差校正）/);
  assert.match(readme, /與策略開關（toggle）無關的 canonical WS 資料/);
  assert.match(readme, /只使用已完成的前序市場/);
  assert.match(readme, /至少 20 個/);
  assert.match(readme, /策略 M7_1／M7_2／M7_3／M7_5（開盤絕對 deadline 子組）/);
  assert.match(readme, /市場開盤後絕對 \+1／\+2／\+3／\+5 秒/);
  assert.match(readme, /received_monotonic_ns <= deadline/);
  assert.match(readme, /deadline 時年齡不超過 1 秒/);
  assert.match(readme, /第一筆 deadline 後的有效 Prediction 訂單簿事件/);
  for (const id of ["m0", "m1", "m2", "m3", "m4", "m5", "m6"]) {
    for (const suffix of ["enabled", "entry_window_seconds", "stake", "max_book_skew_ms", "max_book_age_ms"]) {
      assert.match(readme, new RegExp(`strategy_${id}_${suffix}`));
    }
  }
  for (const key of [
    "strategy_m0_seed", "strategy_m3_min_abs_delta_bps", "strategy_m4_required_observations",
    "strategy_m6_min_basis_samples", "strategy_m7_1_enabled", "strategy_m7_2_enabled",
    "strategy_m7_3_enabled", "strategy_m7_5_enabled", "strategy_m7_entry_window_seconds",
    "strategy_m7_stake", "strategy_m7_max_book_skew_ms", "strategy_m7_max_book_age_ms",
    "strategy_m7_execution_grace_seconds",
  ]) {
    assert.match(readme, new RegExp(key));
  }
  assert.match(readme, /Prediction 上游每 1 ms 更新/);
  assert.match(readme, /optional `mRealtime` 狀態列/);
  for (const field of [
    "processedEvents", "droppedEvents", "lastQueueDelayMs", "lastDecisionDurationMs",
    "spotAgeMs", "futuresAgeMs", "predictionBookAgeMs", "schedulerTickMs",
  ]) {
    assert.match(readme, new RegExp(field));
  }
  assert.match(readme, /`observed_timestamp_ms`/);
  assert.match(readme, /`futures_agg_trade_id`/);
  assert.match(readme, /`signal_timestamp`/);
  assert.match(readme, /`execution_lag_seconds`/);
  assert.doesNotMatch(readme, /十五種彼此獨立的策略/);
  assert.doesNotMatch(page, /SkeletonPreview|codex-preview/);
  assert.doesNotMatch(packageJson, /react-loading-skeleton/);
});
