import json
from pathlib import Path
P=Path('data/research/r4_v0/p0_provenance_v1')
status_path=P/'r4_management_testbed_status_current_v1.json'
s=json.loads(status_path.read_text(encoding='utf-8'))
step="Policy/world decomposition V1: formal realistic-HFT oracle split shows existing-environment separation dominates at 5s while policy-control separation becomes critical at 15-30s; second-worker 500k synthetic regime-shift stress strongly favors separation; consumed whole-market60 annotation finds p_m1_continue - pExistingWeak5s AUC 0.694737 for CONTINUE->OBSERVE vs correct CONTINUE (mean gap +0.1272 vs -0.00983). Development-only; no threshold/action mutation."
if step not in s.get('latestVerifiedSteps',[]): s.setdefault('latestVerifiedSteps',[]).append(step)
s['currentConclusion']="Policy/world entanglement is now a concrete Management representation failure mode. Existing-world continuity/completion must remain separate from policy-side Objective Purpose/admission. On consumed whole-market60, policy-minus-world disagreement explains CONTINUE->OBSERVE better than either component alone, but it is not promotion evidence and no threshold may be tuned on this cohort."
s['nextHighestInformationStep']="Freeze a strict-past POLICY_WORLD_DISAGREEMENT development head without tuning on consumed whole-market60, then test it on a market-disjoint realistic-HFT whole-market shard with trajectory metrics: CONTINUE->OBSERVE, correct CONTINUE preservation, HANDOFF timing, duplicate repair pipeline, execution infeasible, and economic-damage/progress annotations."
status_path.write_text(json.dumps(s,indent=2),encoding='utf-8')

handoff=Path('data/research/r4_v0/r4_hourly_research_handoff_v1.md')
block='''\n\n## 2026-08-29 — P0-B Policy/World Decomposition V1 — DEVELOPMENT KEEP DIRECTION\n- New formal architecture diagnostic `R4_MANAGEMENT_V6_4_POLICY_WORLD_ORACLE_SPLIT_V1`: realistic-HFT consumed formal cohort. Predict-all direction agreement degrades from 5s 0.741/0.778 to 15s 0.444/0.519 and 30s 0.407/0.426 (floor/absNet). Separating policy-control bits improves to 0.796/0.833, 0.778/0.722, 0.630/0.611; existing-environment oracle is strongest at 5s (0.944/0.926). Architecture diagnostic only.\n- Second LAN worker ran 500k synthetic policy-frequency-shift episodes: entangled policy-as-world BA 0.500 in LOW/MID/HIGH; separated BA 0.657/0.807/0.900. Discovery only, not promotion.\n- Mandatory whole-market reinsertion performed as non-authoritative annotations on consumed 60-row Management trajectory. `p_m1_continue - pExistingWeak5s` distinguishes CONTINUE->OBSERVE from correct CONTINUE with AUC 0.694737; mean gap +0.1272 vs -0.00983. Policy alone AUC 0.6211; existing-world high=error AUC 0.3965. No threshold/veto tuning.\n- Conclusion: keep environment/world completion separate from policy-side Objective Purpose/admission. Ownership Continuity stays environment-only. Next test must be market-disjoint realistic-HFT whole-market validation of a frozen disagreement representation.\n- Artifacts: `r4_management_v64_policy_world_oracle_split_v1.json`, `r4_management_policy_world_wholemarket_annotation_v1.json`, progress `r4_management_testbed_progress_20260829_policy_world_split_v1.md`. Guards unchanged; live 8781/R3/R3.1 untouched; 2026-08-16 SEALED; no <=180s authority.\n<!-- R4_MANAGEMENT_POLICY_WORLD_DECOMPOSITION_V1_20260829 -->\n'''
txt=handoff.read_text(encoding='utf-8')
if 'R4_MANAGEMENT_POLICY_WORLD_DECOMPOSITION_V1_20260829' not in txt: handoff.write_text(txt+block,encoding='utf-8')

reg_path=Path('data/research/r4_v0/r4_hourly_experiment_registry_v1.json')
r=json.loads(reg_path.read_text(encoding='utf-8'))
entry={"experimentId":"R4_MANAGEMENT_POLICY_WORLD_DECOMPOSITION_V1_20260829","testedAt":"2026-08-29T13:00:00+08:00","type":"MANAGEMENT_POLICY_WORLD_DECOMPOSITION_INTEGRATED_SHADOW","status":"TESTED_KEEP_DIRECTION_DEVELOPMENT_ONLY","semanticKeys":["policy_world_split","existing_progress_world","objective_purpose_policy","whole_market_integrated_shadow"],"candidate":"Does separating policy-side continuation/purpose from existing-world progress explain integrated Management trajectory failures better than entangled state?","artifact":"data/research/r4_v0/p0_provenance_v1/r4_management_policy_world_wholemarket_annotation_v1.json","primaryResult":{"wholeMarketRows":60,"continueObserveError":19,"correctContinue":15,"policyAuc":0.6210526315789473,"worldErrorHighAuc":0.3964912280701754,"policyMinusWorldAuc":0.6947368421052631,"errorGapMean":0.12720437180371247,"correctGapMean":-0.009826650813494757},"conclusion":"Policy/world disagreement is a stronger development explanation of CONTINUE->OBSERVE than either component alone on the consumed trajectory. Keep decomposition direction, but no threshold/action authority; require market-disjoint whole-market replication.","promotion":"NONE_RESEARCH_SHADOW_ONLY","retestAllowed":False,"nextDistinct":"Freeze disagreement representation before inspecting a market-disjoint realistic-HFT whole-market shard."}
ex=r.setdefault('experiments',[])
if not any(x.get('experimentId')==entry['experimentId'] for x in ex): ex.append(entry)
reg_path.write_text(json.dumps(r,indent=2),encoding='utf-8')
print(json.dumps({'statusUpdated':True,'handoffUpdated':True,'registryUpdated':True,'experimentId':entry['experimentId']},indent=2))
