import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
ART='data/research/r4_v0/hourly/r4_late_weak_side_flip_lifecycle_protection_routing_v1.json'
PRE='data/research/r4_v0/hourly/r4_late_weak_side_flip_lifecycle_protection_routing_v1_preregistered.json'
TOOL='tools/test_r4_late_weak_side_flip_lifecycle_protection_routing_v1.py'
TID='R4_LATE_WEAK_SIDE_FLIP_LIFECYCLE_PROTECTION_ROUTING_V1_20260828_2033'
a=json.load(open(ROOT/ART,encoding='utf-8')); c=a['coverage']; s=a['summary']
exp_path=ROOT/'data/research/r4_v0/r4_hourly_experiment_registry_v1.json'; reg=json.load(open(exp_path,encoding='utf-8'))
entry={'experimentId':TID,'testedAt':'2026-08-28T20:33:00+08:00','type':'FINAL60_WEAK_SIDE_IDENTITY_LIFECYCLE_PROTECTION_CONTEXT','status':a['status'],'semanticKeys':['final_0_60_positive_floor','weak_side_flip_recency','weak_side_flip_count_15s','next10s_floor_break'],'candidate':a['question'],'artifact':ART,'preregisteredArtifact':PRE,'candidateTool':TOOL,'primaryResult':s,'conclusion':'Strict-past weak-side identity flip lifecycle had adequate support and small positive mean ranking lift, but newest chronology reversed and mean calibration worsened. Reject as incremental late protection context; do not threshold/bin/model-sweep or grant action authority.','promotion':'NONE_NOT_ACTION_AUTHORITY','retestAllowed':False,'nextDistinct':'Freeze retained late quote + placement-readiness context. Do not repackage weak-side flip recency/count. Prefer genuinely new independent chronology for replication or a semantically different naturally-supported late execution/lifecycle source.'}
reg['experiments']=[x for x in reg.get('experiments',[]) if x.get('experimentId')!=TID]+[entry]
test_entry={'testId':TID,'testedAt':'2026-08-28T20:33:00+08:00','status':a['status'],'domain':'R4','semanticAxis':'LATE_CROSSING_PROTECTION / PORTFOLIO_SIDE_LIFECYCLE_STABILITY','semanticKeys':entry['semanticKeys'],'hypothesis':a['question'],'artifact':ART,'preregistration':PRE,'tool':TOOL,'decision':a['status'],'actionAuthority':False,'cohort':c,'primaryResult':dict(s,seedNoRegression5of5='UNCHANGED_LAST_VERIFIED_5_OF_5_NO_ACTION_CODE_CHANGE'),'summary':entry['conclusion'],'retestAllowed':False,'nextDistinct':entry['nextDistinct']}
reg['tests']=[x for x in reg.get('tests',[]) if x.get('testId')!=TID]+[test_entry]
exp_path.write_text(json.dumps(reg,ensure_ascii=False,indent=2),encoding='utf-8')
nov_path=ROOT/'data/research/hourly_novel_test_registry_v1.json'; nov=json.load(open(nov_path,encoding='utf-8')); pre=json.load(open(ROOT/PRE,encoding='utf-8'))
nov_entry={'testId':TID,'testedAt':'2026-08-28T20:33:00+08:00','axis':pre['semanticAxis'],'semanticKeys':pre['semanticKeys'],'hypothesis':pre['hypothesis'],'layerAssignment':pre['layerAssignment'],'cohort':pre['cohort'],'primaryMetrics':pre['primaryMetrics'],'fixedKeepRule':pre['fixedKeepRule'],'semanticDifferenceFromPrior':pre['semanticDifferenceFromPriorTests'],'status':a['status'],'artifact':ART,'preregistration':PRE,'tool':TOOL,'actionAuthority':False}
nov['tests']=[x for x in nov.get('tests',[]) if x.get('testId')!=TID]+[nov_entry]
nov_path.write_text(json.dumps(nov,ensure_ascii=False,indent=2),encoding='utf-8')
prog=ROOT/'data/research/r4_v0/hourly/r4_information_layer_progress_20260828_v45.md'
prog.write_text(f'''# R4 Information Layer Progress V45 — 2026-08-28 20:33\n\n- Exactly one novel bounded test: `{TID}` -> `{a['status']}`; preregistered before scoring after both-registry + semantic duplicate audit.\n- Semantic novelty: tests strict-past changes in **which portfolio side is weak** as a late lifecycle-stability context. This is distinct from quote trajectory/freshness, confirmed-fill cadence, queue/book freshness, PREPARE/BUILD interaction, and prior post-durable reserve-debt age.\n- Layers: weak-side identity history = LOGIC_LIFECYCLE_CONTEXT from strict-past portfolio state; weak quote = retained INFORMATION; placement readiness = retained late-protection BELIEF context; Predict/strike = BELIEF context; current portfolio/payoff = LOGIC; NOT_ACTION_AUTHORITY.\n- Cohort: {c['markets']} ordinary Target markets / {c['rows']} final-60s positive-floor rows; positive rate {c['positiveRate']:.3f}; flip-age median {c['flipAgeMedianS']:.1f}s, P90 {c['flipAgeP90S']:.1f}s; recent-15s flip nonzero rate {c['flipCount15sNonzeroRate']:.3f}; 2026-08-16 SEALED; no Echtgeld fit/ingest.\n- Three chronological folds / {s['testPositives']} positive labels: mean dAUC {s['meanDeltaAuc']:+.5f}, mean dAP {s['meanDeltaAp']:+.5f}, mean log-loss improvement {s['meanLogLossImprovement']:+.5f}, worst dAUC {s['worstFoldDeltaAuc']:+.5f}. Newest chronology reverses and calibration mean worsens, so fixed gate fails.\n- Decision: `{a['status']}`. Do not threshold/bin/model-sweep weak-side flip lifecycle; no order/size/owner/MPQ/KEEP/PULL/REPRICE authority.\n- Last verified seed/no-regression remains 5/5 PASS because no action/champion code changed. R4 champion/live R3-S/R3.1/8781 untouched.\n''',encoding='utf-8')
hp=ROOT/'data/research/r4_v0/r4_hourly_research_handoff_v1.md'; h=hp.read_text(encoding='utf-8'); marker='<!-- R4_LATE_WEAK_SIDE_FLIP_LIFECYCLE_PROTECTION_ROUTING_V1_20260828_2033 -->'
if marker not in h:
 h+=f'''\n\n## 2026-08-28 20:33 — LATE WEAK-SIDE FLIP LIFECYCLE PROTECTION ROUTING V1 — REJECTED\n- Exactly one novel bounded test: `{TID}` -> `{a['status']}`; preregistered before scoring after both-registry + semantic duplicate audit.\n- Semantic novelty: tests strict-past weak-side identity flip recency/frequency as late portfolio-lifecycle stability, not quote/fill/queue freshness or post-durable reserve debt.\n- Layer assignment: weak-side identity history = LOGIC_LIFECYCLE_CONTEXT; weak quote = retained INFORMATION; placement readiness = retained LATE_PROTECTION BELIEF context; Predict/strike = BELIEF context; portfolio/payoff geometry = LOGIC; NOT_ACTION_AUTHORITY.\n- Cohort: {c['markets']} ordinary Target markets / {c['rows']} final-60s positive-floor rows; positive rate {c['positiveRate']:.3f}; 15s flip nonzero rate {c['flipCount15sNonzeroRate']:.3f}; 2026-08-16 SEALED; no Echtgeld fit/ingest.\n- Three folds / {s['testPositives']} positives: mean dAUC {s['meanDeltaAuc']:+.5f}, mean dAP {s['meanDeltaAp']:+.5f}, mean log-loss improvement {s['meanLogLossImprovement']:+.5f}, worst dAUC {s['worstFoldDeltaAuc']:+.5f}. Fixed gate fails -> TESTED_REJECTED.\n- Do not rescue with flip-age/count thresholds/bins or model sweeps. Last verified seed/no-regression remains 5/5 PASS; no action/champion code changed. R4 champion/live R3-S/R3.1/8781 unchanged.\n- Artifact: `{ART}`; preregistration `{PRE}`; progress V45; both registries updated.\n- Next: freeze retained late quote + placement-readiness context; prefer genuinely new independent chronology replication or a semantically different naturally-supported late execution/lifecycle source.\n{marker}\n'''; hp.write_text(h,encoding='utf-8')
print(json.dumps({'ok':True,'status':a['status'],'testId':TID,'progress':str(prog.relative_to(ROOT)).replace('\\','/'),'experimentCount':sum(1 for x in reg['experiments'] if x.get('experimentId')==TID),'testCount':sum(1 for x in reg['tests'] if x.get('testId')==TID),'novelCount':sum(1 for x in nov['tests'] if x.get('testId')==TID)},ensure_ascii=False))
