from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[1]
artp=ROOT/'data/research/r4_v0/hourly/r4_late_reference_context_protection_routing_v1.json'
art=json.loads(artp.read_text(encoding='utf-8'))
tid=art['testId']; c=art['coverage']; s=art['summary']
entry={
 'testId':tid,'testedAt':'2026-08-28T16:38:00+08:00','status':art['status'],'domain':'R4',
 'semanticAxis':'LATE_CROSSING_PROTECTION_INFORMATION_ROUTING / SECONDARY_REFERENCE_CONTEXT_INCREMENTAL_BREAK_RISK',
 'semanticKeys':['final 0-60s','current positive floor','next-10s floor break','perp-spot basis','spot-chainlink disagreement','chainlink-strike context','retained weak-side quote economics','retained late placement readiness','late protection context only'],
 'hypothesis':art['question'],'artifact':'data/research/r4_v0/hourly/r4_late_reference_context_protection_routing_v1.json','preregistration':'data/research/r4_v0/hourly/r4_late_reference_context_protection_routing_v1_preregistered.json','tool':'tools/test_r4_late_reference_context_protection_routing_v1.py','decision':art['status'],'actionAuthority':False,
 'cohort':{'markets':c['markets'],'rows':c['rows'],'positiveRate':c['positiveRate'],'medianPublicLagMs':c['medianPublicLagMs'],'maxPublicLagMs':c['maxPublicLagMs'],'phase':'final 0-60s positive-floor Target chronology','special20260816Sealed':True,'echtgeldTraining':False},
 'primaryResult':{'eligibleFolds':s['eligibleFolds'],'testPositives':s['testPositives'],'meanDeltaAuc':s['meanDeltaAuc'],'meanDeltaAp':s['meanDeltaAp'],'meanLogLossImprovement':s['meanLogLossImprovement'],'worstDeltaAuc':s['worstFoldDeltaAuc'],'allFoldAucNonnegative':s['allFoldAucNonnegative'],'seedNoRegression5of5':'UNCHANGED_LAST_VERIFIED_5_OF_5_NO_ACTION_CODE_CHANGE'},
 'summary':'Secondary basis/reference information has adequate natural variation but does not transfer as incremental final-60s positive-floor break-risk context above the retained late quote+placement-readiness stack. One chronology fold regressed sharply, and mean AUC/AP/calibration all worsened. This rejects the late-protection routing formulation only; it remains secondary information with no action authority.',
 'retestAllowed':False,
 'nextDistinct':'Do not repackage basis/Chainlink/reference context into another late threshold/bin/model. Freeze the retained late quote + placement-readiness context and prefer genuinely new independent chronology for predeclared replication, or a semantically different late execution/lifecycle source with natural support.'}
for rel in ['data/research/r4_v0/r4_hourly_experiment_registry_v1.json','data/research/hourly_novel_test_registry_v1.json']:
 p=ROOT/rel; x=json.loads(p.read_text(encoding='utf-8')); arr=x.setdefault('tests',[]); arr[:]=[z for z in arr if z.get('testId')!=tid]; arr.append(entry); p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
prog=ROOT/'data/research/r4_v0/hourly/r4_information_layer_progress_20260828_v41.md'
prog.write_text(f'''# R4 Information Layer Progress V41 — 2026-08-28 16:38

- Exactly one novel bounded test: `{tid}` -> `{art['status']}`; preregistered before scoring after both-registry + semantic duplicate audit.
- Semantic novelty: the earlier reference/basis test was restricted to 60-300s HIGH-PREPARE Formation. This cycle tests a separate phase/head/target: final-60s positive-floor protection, above the already-retained late weak-side quote + placement-readiness context. It is not a retry of Formation routing and contains no threshold/model rescue.
- Layers: basis/Chainlink/reference = SECONDARY INFORMATION / REGIME CONTEXT; weak quote = retained INFORMATION; placement readiness = retained LATE_PROTECTION BELIEF context; Predict/strike = BELIEF context; portfolio/payoff = LOGIC; NOT_ACTION_AUTHORITY.
- Cohort: {c['markets']} ordinary Target markets / {c['rows']} final-60s positive-floor rows; positive rate {c['positiveRate']:.3f}; strict-past public lag median {c['medianPublicLagMs']:.0f}ms / max {c['maxPublicLagMs']:.0f}ms; candidate reference features had non-zero variation; 2026-08-16 SEALED; no Echtgeld fit/ingest.
- Result: 3 eligible chronological folds / {s['testPositives']} positive test labels. Mean dAUC {s['meanDeltaAuc']:+.5f}, mean dAP {s['meanDeltaAp']:+.5f}, mean log-loss improvement {s['meanLogLossImprovement']:+.5f}, worst dAUC {s['worstFoldDeltaAuc']:+.5f}; fixed gate fails -> `{art['status']}`.
- Do not rescue with basis/reference thresholds, bins or model sweeps. No action authority. Last verified seed/no-regression remains 5/5 PASS because no action/champion code changed; R4 champion/live R3-S/R3.1/8781 untouched.
- Artifact: `data/research/r4_v0/hourly/r4_late_reference_context_protection_routing_v1.json`; preregistration: `data/research/r4_v0/hourly/r4_late_reference_context_protection_routing_v1_preregistered.json`.
- Next: freeze the retained late quote + placement-readiness route and prioritize genuine new independent chronology replication, or a semantically different late execution/lifecycle source with natural support.
''',encoding='utf-8')
h=ROOT/'data/research/r4_v0/r4_hourly_research_handoff_v1.md'
with h.open('a',encoding='utf-8') as f:
 f.write(f'''\n\n## 2026-08-28 16:38 — LATE SECONDARY REFERENCE CONTEXT PROTECTION ROUTING V1 — REJECTED\n- Exactly one novel bounded test: `{tid}` -> `{art['status']}`; preregistered before scoring after both-registry + semantic duplicate audit.\n- Semantic novelty: prior basis/Chainlink/reference routing was rejected only in 60-300s HIGH-PREPARE Formation. This cycle asks a separate final-0-60s protection question on current positive floor, above retained weak-side quote + late placement-readiness context; no threshold/model rescue.\n- Layer assignment: basis/reference = SECONDARY INFORMATION / REGIME CONTEXT; weak quote = retained INFORMATION; placement readiness = retained LATE_PROTECTION BELIEF context; Predict/strike = BELIEF context; portfolio/payoff = LOGIC; NOT_ACTION_AUTHORITY.\n- Cohort: {c['markets']} ordinary Target markets / {c['rows']} rows; positive rate {c['positiveRate']:.3f}; public lag median {c['medianPublicLagMs']:.0f}ms / max {c['maxPublicLagMs']:.0f}ms; reference features had non-zero variation; 2026-08-16 SEALED; no Echtgeld fit/ingest.\n- Three eligible chronological folds / {s['testPositives']} positive labels: mean dAUC {s['meanDeltaAuc']:+.5f}, mean dAP {s['meanDeltaAp']:+.5f}, mean log-loss improvement {s['meanLogLossImprovement']:+.5f}, worst dAUC {s['worstFoldDeltaAuc']:+.5f}. Fixed KEEP gate fails -> `TESTED_REJECTED`.\n- Interpretation: secondary reference/basis context does not add stable late floor-break information after retained quote + readiness context. Do not threshold/bin/model-sweep or grant action authority.\n- Last verified seed/no-regression remains 5/5 PASS; no action/champion code changed. R4 champion/live R3-S/R3.1/8781 unchanged.\n- Artifact: `data/research/r4_v0/hourly/r4_late_reference_context_protection_routing_v1.json`; preregistration `data/research/r4_v0/hourly/r4_late_reference_context_protection_routing_v1_preregistered.json`; progress V41; both registries updated.\n- Next distinct gap: freeze late quote + readiness context. Prefer genuinely new independent chronology for predeclared replication or a semantically different naturally-supported late execution/lifecycle source; do not repackage basis/reference context.\n<!-- R4_LATE_REFERENCE_CONTEXT_PROTECTION_ROUTING_V1_20260828_1638 -->\n''')
print(json.dumps({'ok':True,'testId':tid,'status':art['status'],'progress':str(prog.relative_to(ROOT)).replace('\\','/')}))
