from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[1]
artp=ROOT/'data/research/r4_v0/hourly/r4_late_observed_fill_cadence_protection_routing_v1.json'
art=json.loads(artp.read_text(encoding='utf-8'))
tid=art['testId']; c=art['coverage']; s=art['summary']
entry={
 'testId':tid,'testedAt':'2026-08-28T17:38:00+08:00','status':art['status'],'domain':'R4',
 'semanticAxis':art['semanticAxis'],
 'semanticKeys':['final 0-60s current positive floor','strict-past confirmed Maker fill cadence','weak-side realized shares trailing 15s','surplus-side realized shares trailing 15s','time since last weak-side confirmed Maker fill','next-10s floor break','retained late quote and placement-readiness context','execution lifecycle context only'],
 'hypothesis':art['question'],'artifact':'data/research/r4_v0/hourly/r4_late_observed_fill_cadence_protection_routing_v1.json','preregistration':'data/research/r4_v0/hourly/r4_late_observed_fill_cadence_protection_routing_v1_preregistered.json','tool':'tools/test_r4_late_observed_fill_cadence_protection_routing_v1.py','decision':art['status'],'actionAuthority':False,
 'cohort':{'markets':c['markets'],'rows':c['rows'],'positiveRate':c['positiveRate'],'medianPublicLagMs':c['medianPublicLagMs'],'maxPublicLagMs':c['maxPublicLagMs'],'phase':'final 0-60s positive-floor Target chronology','special20260816Sealed':True,'echtgeldTraining':False},
 'primaryResult':{'eligibleFolds':s['eligibleFolds'],'testPositives':s['testPositives'],'meanDeltaAuc':s['meanDeltaAuc'],'meanDeltaAp':s['meanDeltaAp'],'meanLogLossImprovement':s['meanLogLossImprovement'],'worstDeltaAuc':s['worstFoldDeltaAuc'],'allFoldAucNonnegative':s['allFoldAucNonnegative'],'seedNoRegression5of5':'UNCHANGED_LAST_VERIFIED_5_OF_5_NO_ACTION_CODE_CHANGE'},
 'summary':'Strict-past confirmed Maker realization cadence had strong natural variation but did not add chronology-stable final-60s positive-floor break-risk information above the retained late quote + placement-readiness stack. Mean AUC lift was small, mean AP worsened, and one fold reversed. Reject this late-protection routing formulation only; preserve prior first-crossing realized-build-dominance evidence in its original role.',
 'retestAllowed':False,
 'nextDistinct':'Do not rescue confirmed-fill cadence with alternate 5s/10s/30s windows, count/share thresholds, recency bins, or nonlinear model sweeps. Freeze late quote + readiness; prefer genuinely new independent chronology for their predeclared replication or a semantically different late lifecycle information source.'}
for rel in ['data/research/r4_v0/r4_hourly_experiment_registry_v1.json','data/research/hourly_novel_test_registry_v1.json']:
 p=ROOT/rel; x=json.loads(p.read_text(encoding='utf-8')); arr=x.setdefault('tests',[]); arr[:]=[z for z in arr if z.get('testId')!=tid]; arr.append(entry); p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
prog=ROOT/'data/research/r4_v0/hourly/r4_information_layer_progress_20260828_v42.md'
prog.write_text(f'''# R4 Information Layer Progress V42 — 2026-08-28 17:38

- Exactly one novel bounded test: `{tid}` -> `{art['status']}`; preregistered before scoring after both-registry + semantic duplicate audit.
- Semantic novelty: prior strict-past observed-fill research asked whether pre-cross weak-side realized build predicts whether the **first** safe crossing becomes durable. This cycle asks a different lifecycle/phase question: once final-60s floor is already positive, does trailing confirmed Maker realization cadence add next-10s floor-break risk context above the retained late quote + placement-readiness stack? It is not pending-fill probability, queue opportunity, crossing acquisition, or an action translation.
- Layers: confirmed Maker fills = EXECUTION INFORMATION; observed fill cadence = EXECUTION_LIFECYCLE context candidate; weak quote = retained INFORMATION; placement readiness = retained LATE_PROTECTION BELIEF context; Predict/strike = BELIEF context; portfolio/payoff = LOGIC; NOT_ACTION_AUTHORITY.
- Cohort: {c['markets']} ordinary Target markets / {c['rows']} final-60s positive-floor rows; positive rate {c['positiveRate']:.3f}; strict-past public lag median {c['medianPublicLagMs']:.0f}ms / max {c['maxPublicLagMs']:.0f}ms; lifecycle features had broad natural variation (weak 15s fill-share nonzero rate {c['lifecycleVariation']['weak_fill_shares_15s']['nonzeroRate']:.3f}); 2026-08-16 SEALED; no Echtgeld fit/ingest.
- Result: 3 eligible chronological folds / {s['testPositives']} positive test labels. Mean dAUC {s['meanDeltaAuc']:+.5f}, mean dAP {s['meanDeltaAp']:+.5f}, mean log-loss improvement {s['meanLogLossImprovement']:+.5f}, worst dAUC {s['worstFoldDeltaAuc']:+.5f}; fixed gate fails -> `{art['status']}`.
- Interpretation: realization cadence improves calibration on average but does not provide stable ranking/AP transfer; one fold reverses AUC and mean AP worsens. Preserve the old first-crossing realized-build-dominance signal only in its original crossing-quality role. Do not window/threshold/model-sweep rescue this late routing.
- No action authority. Last verified seed/no-regression remains 5/5 PASS because no action/champion code changed; R4 champion/live R3-S/R3.1/8781 untouched.
- Artifact: `data/research/r4_v0/hourly/r4_late_observed_fill_cadence_protection_routing_v1.json`; preregistration: `data/research/r4_v0/hourly/r4_late_observed_fill_cadence_protection_routing_v1_preregistered.json`.
- Next: freeze retained late quote + placement readiness. Prefer genuine new independent chronology for predeclared replication, or a semantically different naturally-supported late lifecycle source; do not repackage observed-fill cadence.
''',encoding='utf-8')
h=ROOT/'data/research/r4_v0/r4_hourly_research_handoff_v1.md'
with h.open('a',encoding='utf-8') as f:
 f.write(f'''\n\n## 2026-08-28 17:38 — LATE OBSERVED FILL-CADENCE PROTECTION ROUTING V1 — REJECTED\n- Exactly one novel bounded test: `{tid}` -> `{art['status']}`; preregistered before scoring after both-registry + semantic duplicate audit.\n- Semantic novelty: prior observed-fill work predicted first-safe-crossing durability. This cycle asks whether already-confirmed Maker realization cadence, after a positive floor already exists in final 0-60s, adds next-10s floor-break information above retained weak quote + late placement readiness. No pending-fill/queue/crossing-acquisition/action semantics are reused.\n- Layer assignment: confirmed Maker fills = EXECUTION INFORMATION; observed fill cadence = EXECUTION_LIFECYCLE context candidate; weak quote = retained INFORMATION; placement readiness = retained LATE_PROTECTION BELIEF context; Predict/strike = BELIEF context; portfolio/payoff = LOGIC; NOT_ACTION_AUTHORITY.\n- Cohort: {c['markets']} ordinary Target markets / {c['rows']} rows; positive rate {c['positiveRate']:.3f}; public lag median {c['medianPublicLagMs']:.0f}ms / max {c['maxPublicLagMs']:.0f}ms; weak-fill-shares 15s nonzero rate {c['lifecycleVariation']['weak_fill_shares_15s']['nonzeroRate']:.3f}; 2026-08-16 SEALED; no Echtgeld fit/ingest.\n- Three eligible chronological folds / {s['testPositives']} positive labels: mean dAUC {s['meanDeltaAuc']:+.5f}, mean dAP {s['meanDeltaAp']:+.5f}, mean log-loss improvement {s['meanLogLossImprovement']:+.5f}, worst dAUC {s['worstFoldDeltaAuc']:+.5f}. Fixed KEEP gate fails -> `TESTED_REJECTED`.\n- Interpretation: trailing confirmed realization cadence has real support and improves mean calibration, but ranking/AP transfer is not chronology-stable. This does not overturn the prior first-crossing weak-side realized-build-dominance KEEP_SIGNAL; it rejects only late positive-floor protection routing of cadence. Do not retest alternate windows/bins/thresholds/model sweeps.\n- Last verified seed/no-regression remains 5/5 PASS; no action/champion code changed. R4 champion/live R3-S/R3.1/8781 unchanged.\n- Artifact: `data/research/r4_v0/hourly/r4_late_observed_fill_cadence_protection_routing_v1.json`; preregistration `data/research/r4_v0/hourly/r4_late_observed_fill_cadence_protection_routing_v1_preregistered.json`; progress V42; both registries updated.\n- Next distinct gap: freeze late quote + readiness context. Prefer genuinely new independent chronology for predeclared replication or a semantically different naturally-supported late execution/lifecycle source; do not repackage confirmed-fill cadence.\n<!-- R4_LATE_OBSERVED_FILL_CADENCE_PROTECTION_ROUTING_V1_20260828_1738 -->\n''')
print(json.dumps({'ok':True,'testId':tid,'status':art['status'],'progress':str(prog.relative_to(ROOT)).replace('\\','/')}))
