import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
ART='data/research/r4_v0/hourly/r4_late_positive_floor_dwell_protection_routing_v1.json'
PRE='data/research/r4_v0/hourly/r4_late_positive_floor_dwell_protection_routing_v1_preregistered.json'
TOOL='tools/test_r4_late_positive_floor_dwell_protection_routing_v1.py'
TID='R4_LATE_POSITIVE_FLOOR_DWELL_PROTECTION_ROUTING_V1_20260828_2238'
a=json.load(open(ROOT/ART,encoding='utf-8')); c=a['coverage']; s=a['summary']; pre=json.load(open(ROOT/PRE,encoding='utf-8'))
exp_path=ROOT/'data/research/r4_v0/r4_hourly_experiment_registry_v1.json'; reg=json.load(open(exp_path,encoding='utf-8'))
conclusion='Strict-past uninterrupted positive-floor dwell/reentry lifecycle had strong natural support and one positive chronology block, but mean ranking/AP were negative and the newest chronology reversed. Reject as incremental late protection context; do not threshold/bin/window/model-sweep or grant action authority.'
nextd='Freeze retained late quote + placement-readiness context. Do not repackage positive-floor dwell/reentry maturity. Prefer genuinely new independent chronology replication or a semantically different naturally-supported late execution/protection source.'
entry={'experimentId':TID,'testedAt':'2026-08-28T22:38:00+08:00','type':'FINAL60_POSITIVE_FLOOR_DWELL_LIFECYCLE_PROTECTION_CONTEXT','status':a['status'],'semanticKeys':pre['semanticKeys'],'candidate':a['question'],'artifact':ART,'preregisteredArtifact':PRE,'candidateTool':TOOL,'primaryResult':s,'conclusion':conclusion,'promotion':'NONE_NOT_ACTION_AUTHORITY','retestAllowed':False,'nextDistinct':nextd}
reg['experiments']=[x for x in reg.get('experiments',[]) if x.get('experimentId')!=TID]+[entry]
test_entry={'testId':TID,'testedAt':'2026-08-28T22:38:00+08:00','status':a['status'],'domain':'R4','semanticAxis':pre['semanticAxis'],'semanticKeys':pre['semanticKeys'],'hypothesis':pre['hypothesis'],'artifact':ART,'preregistration':PRE,'tool':TOOL,'decision':a['status'],'actionAuthority':False,'cohort':c,'primaryResult':dict(s,seedNoRegression5of5='UNCHANGED_LAST_VERIFIED_5_OF_5_NO_ACTION_CODE_CHANGE'),'summary':conclusion,'retestAllowed':False,'nextDistinct':nextd}
reg['tests']=[x for x in reg.get('tests',[]) if x.get('testId')!=TID]+[test_entry]
exp_path.write_text(json.dumps(reg,ensure_ascii=False,indent=2),encoding='utf-8')
nov_path=ROOT/'data/research/hourly_novel_test_registry_v1.json'; nov=json.load(open(nov_path,encoding='utf-8'))
nov_entry={'testId':TID,'testedAt':'2026-08-28T22:38:00+08:00','axis':pre['semanticAxis'],'semanticKeys':pre['semanticKeys'],'hypothesis':pre['hypothesis'],'layerAssignment':pre['layerAssignment'],'cohort':pre['cohort'],'primaryMetrics':pre['primaryMetrics'],'fixedKeepRule':pre['fixedKeepRule'],'semanticDifferenceFromPrior':pre['semanticDifferenceFromPriorTests'],'status':a['status'],'artifact':ART,'preregistration':PRE,'tool':TOOL,'actionAuthority':False}
nov['tests']=[x for x in nov.get('tests',[]) if x.get('testId')!=TID]+[nov_entry]
nov_path.write_text(json.dumps(nov,ensure_ascii=False,indent=2),encoding='utf-8')
prog=ROOT/'data/research/r4_v0/hourly/r4_information_layer_progress_20260828_v47.md'
prog.write_text(f'''# R4 Information Layer Progress V47 — 2026-08-28 22:38\n\n- Exactly one novel bounded test: `{TID}` -> `{a['status']}`; preregistered before scoring after both-registry + semantic duplicate audit.\n- Semantic novelty: tests strict-past **current safe-base dwell maturity**—uninterrupted positive-floor age and recent positive-floor reentries—as late lifecycle context. This is distinct from floor high-water/drawdown magnitude, weak-side flips, quote/fill/freshness families, and reserve-debt sequencing. Prior positive-floor duration appearances were outcome metrics, not a late protection information/routing candidate.\n- Layers: positive-floor dwell history = LOGIC_LIFECYCLE_CONTEXT from strict-past portfolio state; weak quote = retained INFORMATION; placement readiness = retained late-protection BELIEF context; Predict/strike = BELIEF context; current portfolio/payoff = LOGIC; NOT_ACTION_AUTHORITY.\n- Cohort: {c['markets']} ordinary Target markets / {c['rows']} final-60s positive-floor rows; positive rate {c['positiveRate']:.3f}; dwell median {c['dwellAgeMedianS']:.1f}s, P90 {c['dwellAgeP90S']:.1f}s; recent-60s reentry nonzero rate {c['reentry60sNonzeroRate']:.3f}; 2026-08-16 SEALED; no Echtgeld fit/ingest.\n- Three chronological folds / {s['testPositives']} positive labels: mean dAUC {s['meanDeltaAuc']:+.5f}, mean dAP {s['meanDeltaAp']:+.5f}, mean log-loss improvement {s['meanLogLossImprovement']:+.5f}, worst dAUC {s['worstFoldDeltaAuc']:+.5f}. Fold dAUCs 0.0000 / +0.0362 / -0.0429; newest chronology reverses and mean ranking/AP are negative, so fixed gate fails.\n- Decision: `{a['status']}`. Do not threshold/bin/window/model-sweep positive-floor dwell/reentry maturity; no order/size/owner/MPQ/KEEP/PULL/REPRICE authority.\n- Last verified seed/no-regression remains 5/5 PASS because no action/champion code changed. R4 champion/live R3-S/R3.1/8781 untouched.\n''',encoding='utf-8')
hp=ROOT/'data/research/r4_v0/r4_hourly_research_handoff_v1.md'; h=hp.read_text(encoding='utf-8'); marker='<!-- R4_LATE_POSITIVE_FLOOR_DWELL_PROTECTION_ROUTING_V1_20260828_2238 -->'
if marker not in h:
 h+=f'''\n\n## 2026-08-28 22:38 — LATE POSITIVE-FLOOR DWELL PROTECTION ROUTING V1 — REJECTED\n- Exactly one novel bounded test: `{TID}` -> `{a['status']}`; preregistered before scoring after both-registry + semantic duplicate audit.\n- Semantic novelty: strict-past uninterrupted current positive-floor dwell age + recent positive-floor reentry count as late safe-base maturity context; not floor-highwater magnitude, weak-side flips, quote/fill/freshness, or reserve-debt sequencing.\n- Layer assignment: dwell/reentry history = LOGIC_LIFECYCLE_CONTEXT; weak quote = retained INFORMATION; placement readiness = retained LATE_PROTECTION BELIEF context; Predict/strike = BELIEF context; portfolio/payoff geometry = LOGIC; NOT_ACTION_AUTHORITY.\n- Cohort: {c['markets']} ordinary Target markets / {c['rows']} final-60s positive-floor rows; positive rate {c['positiveRate']:.3f}; dwell median {c['dwellAgeMedianS']:.1f}s, P90 {c['dwellAgeP90S']:.1f}s; reentry nonzero rate {c['reentry60sNonzeroRate']:.3f}; 2026-08-16 SEALED; no Echtgeld fit/ingest.\n- Three folds / {s['testPositives']} positives: mean dAUC {s['meanDeltaAuc']:+.5f}, mean dAP {s['meanDeltaAp']:+.5f}, mean log-loss improvement {s['meanLogLossImprovement']:+.5f}, worst dAUC {s['worstFoldDeltaAuc']:+.5f}. Fixed gate fails -> TESTED_REJECTED.\n- Do not rescue with dwell/reentry thresholds, bins, alternate windows, or model sweeps. Last verified seed/no-regression remains 5/5 PASS; no action/champion code changed. R4 champion/live R3-S/R3.1/8781 unchanged.\n- Artifact: `{ART}`; preregistration `{PRE}`; progress V47; both registries updated.\n- Next: freeze retained late quote + placement-readiness context; prefer genuinely new independent chronology replication or a semantically different naturally-supported late execution/protection source.\n{marker}\n'''; hp.write_text(h,encoding='utf-8')
print(json.dumps({'ok':True,'status':a['status'],'testId':TID,'progress':str(prog.relative_to(ROOT)).replace('\\','/'),'experimentCount':sum(1 for x in reg['experiments'] if x.get('experimentId')==TID),'testCount':sum(1 for x in reg['tests'] if x.get('testId')==TID),'novelCount':sum(1 for x in nov['tests'] if x.get('testId')==TID)},ensure_ascii=False))
