from pathlib import Path
import json
from datetime import datetime
from zoneinfo import ZoneInfo
ROOT=Path(__file__).resolve().parents[1]
ART=ROOT/'data/research/r4_v0/hourly/r4_information_pipeline_health_high_prepare_tail_routing_v1.json'
PRE=ROOT/'data/research/r4_v0/hourly/r4_information_pipeline_health_high_prepare_tail_routing_v1_preregistered.json'
REG=ROOT/'data/research/r4_v0/r4_hourly_experiment_registry_v1.json'
NOV=ROOT/'data/research/hourly_novel_test_registry_v1.json'
HAND=ROOT/'data/research/r4_v0/r4_hourly_research_handoff_v1.md'
PROG=ROOT/'data/research/r4_v0/hourly/r4_information_layer_progress_20260828_v38.md'
TEST='R4_INFORMATION_PIPELINE_HEALTH_HIGH_PREPARE_TAIL_ROUTING_V1_20260828_1338'
a=json.loads(ART.read_text(encoding='utf-8')); p=json.loads(PRE.read_text(encoding='utf-8')); s=a['primaryHighPrepareSummary']; c=a['coverage']
fold=[f['HIGH']['increment']['deltaAuc'] for f in a['folds'] if f['HIGH'].get('eligible')]
now=datetime.now(ZoneInfo('Asia/Taipei')).isoformat()
entry={
 'testId':TEST,'testedAt':now,'status':a['status'],'domain':'R4','semanticAxis':p['semanticAxis'],
 'semanticKeys':['HIGH PREPARE Formation','upstream information pipeline health','Predict/Chainlink source and receipt age','micro writer lag','feature completeness/missingness','public stream event rates and dropped events','retained weak-side quote economics','15s floor-tail damage','information reliability context only'],
 'hypothesis':p['hypothesis'],'artifact':'data/research/r4_v0/hourly/r4_information_pipeline_health_high_prepare_tail_routing_v1.json','preregistration':'data/research/r4_v0/hourly/r4_information_pipeline_health_high_prepare_tail_routing_v1_preregistered.json','tool':'tools/test_r4_information_pipeline_health_high_prepare_tail_routing_v1.py','decision':a['status'],'actionAuthority':False,
 'cohort':{'markets':c['markets'],'rows':c['rows'],'medianPublicLagMs':c['publicLagMedianMs'],'maxPublicLagMs':c['publicLagMaxMs'],'special20260816Sealed':True,'echtgeldTraining':False},
 'primaryResult':{'eligibleFolds':s['eligibleFolds'],'meanDeltaAuc':s['meanDeltaAuc'],'meanDeltaAp':s['meanDeltaAp'],'meanLogLossImprovement':s['meanLogLossImprovement'],'worstDeltaAuc':s['worstDeltaAuc'],'allFoldAucNonnegative':s['allFoldAucNonnegative'],'variedCandidateCount':a['variedCandidateCount'],'foldDeltaAuc':fold,'seedNoRegression5of5':'UNCHANGED_LAST_VERIFIED_5_OF_5_NO_ACTION_CODE_CHANGE','trainerRefresh':'FAILED_NO_NEW_ARTIFACT_EMPTY_FROZEN_MATCHED_GAP_ARRAY'},
 'summary':f"Upstream pipeline-health features had adequate natural variation ({a['variedCandidateCount']} varied candidates) but degraded the retained HIGH-PREPARE weak-quote tail stack in every chronological AUC fold. mean dAUC={s['meanDeltaAuc']:.5f}, mean dAP={s['meanDeltaAp']:.5f}, mean log-loss improvement={s['meanLogLossImprovement']:.5f}, worst dAUC={s['worstDeltaAuc']:.5f}. Reject this routing formulation; do not threshold/bin individual ages, lags, completeness or event rates to rescue it.",
 'retestAllowed':False,
 'nextDistinct':'Do not repackage upstream source-age/writer-lag/completeness/event-rate health as another HIGH-PREPARE threshold/regime. Prefer a semantically different naturally-supported PREPARE/BUILD interaction or late protection information route, or wait for genuinely new independent chronology for a frozen replication.'
}
for path in (REG,NOV):
 d=json.loads(path.read_text(encoding='utf-8')); arr=d['tests']; arr[:]=[x for x in arr if x.get('testId')!=TEST]; arr.append(entry); path.write_text(json.dumps(d,ensure_ascii=False,indent=2),encoding='utf-8')
progress=f'''# R4 Information Layer Progress V38 — 2026-08-28 13:xx\n\n- Exactly one novel bounded test: `{TEST}` -> `{a['status']}`. Preregistered before execution after both-registry and semantic duplicate audit.\n- Semantic novelty: quote freshness V1 tested only the age of the matched Predict-market quote snapshot. This cycle isolates upstream pipeline reliability/health (Predict/Chainlink source+receipt age, micro writer lag, completeness/missingness, event rates, dropped events) above the retained HIGH-PREPARE weak-quote stack.\n- Layers: pipeline health = `INFORMATION_RELIABILITY_CONTEXT`; weak quote = retained `INFORMATION`; placement readiness = `PREPARE BELIEF`; Predict/strike = `FORMATION BELIEF`; portfolio/payoff = `LOGIC`; output `NOT_ACTION_AUTHORITY`.\n- Cohort: {c['markets']} ordinary Target markets / {c['rows']} strict-past Formation rows; public quote median lag {c['publicLagMedianMs']:.0f}ms / max {c['publicLagMaxMs']:.0f}ms; 2026-08-16 SEALED; no Echtgeld fit/ingest. Ten of eleven pipeline-health candidates had non-trivial variation.\n- Three HIGH-PREPARE chronological folds all worsened AUC: {' / '.join(f'{x:+.4f}' for x in fold)}. mean dAUC {s['meanDeltaAuc']:+.5f}; mean dAP {s['meanDeltaAp']:+.5f}; mean log-loss improvement {s['meanLogLossImprovement']:+.5f}; worst dAUC {s['worstDeltaAuc']:+.5f}. Fixed gate fails -> `TESTED_REJECTED`.\n- No threshold/bin/model rescue and no action authority. Champion/live R3-S/R3.1/8781 unchanged. Last verified seed no-regression remains 5/5 because no action/champion code changed. Trainer refresh attempted once and failed before writing a snapshot because the frozen matched-gap training array was empty; latest valid trainer snapshot remains 2026-08-27 19:43 (Acquisition 0.7364 / Preservation 0.5879, frozen Echtgeld exactly 8).\n- Next: move away from pipeline-health/freshness variants. Prefer a semantically different naturally-supported PREPARE/BUILD parallel-belief interaction or late crossing/protection route; otherwise wait for genuinely new independent chronology.\n'''
PROG.write_text(progress,encoding='utf-8')
block=f'''\n\n## 2026-08-28 13:xx — INFORMATION PIPELINE HEALTH × HIGH PREPARE TAIL ROUTING V1 — REJECTED\n- Exactly one novel bounded test completed: `{TEST}`; preregistered before execution after both-registry + semantic duplicate audit.\n- Semantic novelty: unlike quote-freshness V1, which tested matched public quote age, this test isolates upstream public-information pipeline reliability/health: source/receipt ages, writer lag, feature completeness/missingness, stream event rates and dropped-event state.\n- Layer assignment: pipeline health = INFORMATION_RELIABILITY_CONTEXT; weak quote = retained INFORMATION; placement readiness = PREPARE BELIEF; Predict/strike = FORMATION BELIEF; portfolio/payoff geometry = LOGIC; NOT_ACTION_AUTHORITY.\n- Cohort: {c['markets']} ordinary Target markets / {c['rows']} 60-300s REPAIR rows; 2026-08-16 SEALED; no Echtgeld fit/ingest. Candidate variation was adequate ({a['variedCandidateCount']} varied features).\n- Three HIGH-PREPARE folds all regressed AUC ({' / '.join(f'{x:+.4f}' for x in fold)}): mean dAUC {s['meanDeltaAuc']:+.5f}, mean dAP {s['meanDeltaAp']:+.5f}, mean log-loss improvement {s['meanLogLossImprovement']:+.5f}, worst dAUC {s['worstDeltaAuc']:+.5f}. Fixed KEEP gate fails -> `TESTED_REJECTED`. Do not rescue with individual age/lag/completeness/event-rate thresholds or model sweeps.\n- Trainer refresh attempted once and failed with the known empty frozen matched-gap training-array condition; no new snapshot was written. Latest valid snapshot remains 2026-08-27 19:43 (Acquisition 0.7364 / Preservation 0.5879; frozen Echtgeld 8). Last verified seed no-regression remains 5/5; no champion/action code changed. R4 champion/live R3-S/R3.1/8781 unchanged.\n- Artifacts: `data/research/r4_v0/hourly/r4_information_pipeline_health_high_prepare_tail_routing_v1.json`, preregistration `data/research/r4_v0/hourly/r4_information_pipeline_health_high_prepare_tail_routing_v1_preregistered.json`, progress V38. Both registries updated.\n- Next distinct gap: do not repackage pipeline health/freshness. Prefer a semantically different naturally-supported PREPARE/BUILD parallel-belief interaction or late crossing/protection information route, or wait for genuinely new independent chronology for a frozen replication.\n<!-- R4_INFORMATION_PIPELINE_HEALTH_HIGH_PREPARE_TAIL_ROUTING_V1_20260828_1338 -->\n'''
with HAND.open('a',encoding='utf-8') as f: f.write(block)
print(json.dumps({'ok':True,'testId':TEST,'status':a['status'],'progress':str(PROG.relative_to(ROOT)).replace('\\','/'),'registriesUpdated':True},ensure_ascii=False))
