from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[1]
art_path='data/research/r4_v0/hourly/r4_late_placement_readiness_protection_routing_v1.json'
pre_path='data/research/r4_v0/hourly/r4_late_placement_readiness_protection_routing_v1_preregistered.json'
tool='tools/test_r4_late_placement_readiness_protection_routing_v1.py'
a=json.loads((ROOT/art_path).read_text(encoding='utf-8'))
tid=a['testId']; s=a['summary']; c=a['coverage']
entry={
 'testId':tid,'testedAt':'2026-08-28T15:33:00+08:00','status':a['status'],'domain':'R4',
 'semanticAxis':'LATE_CROSSING_PROTECTION_INFORMATION_ROUTING / PLACEMENT_READINESS_INCREMENTAL_BREAK_RISK',
 'semanticKeys':['final 0-60s','current positive floor','next-10s floor break','frozen placement_readiness','retained weak-side quote economics','late protection context only'],
 'hypothesis':'In final 0-60s with an already-positive floor, test whether frozen placement_readiness adds stable floor-break information above portfolio/payoff geometry, Predict/strike, and retained late weak-side quote economics without carrying Formation PREPARE authority into late phase.',
 'artifact':art_path,'preregistration':pre_path,'tool':tool,'decision':a['status'],'actionAuthority':False,
 'cohort':{'markets':c['markets'],'rows':c['rows'],'positiveRate':c['positiveRate'],'medianPublicLagMs':c['medianPublicLagMs'],'maxPublicLagMs':c['maxPublicLagMs'],'readinessStd':c['readinessStd'],'phase':'final 0-60s positive-floor Target chronology','special20260816Sealed':True,'echtgeldTraining':False},
 'primaryResult':{'eligibleFolds':s['eligibleFolds'],'testPositives':s['testPositives'],'meanDeltaAuc':s['meanDeltaAuc'],'meanDeltaAp':s['meanDeltaAp'],'meanLogLossImprovement':s['meanLogLossImprovement'],'worstDeltaAuc':s['worstFoldDeltaAuc'],'allFoldAucNonnegative':s['allFoldAucNonnegative'],'seedNoRegression5of5':'UNCHANGED_LAST_VERIFIED_5_OF_5_NO_ACTION_CODE_CHANGE'},
 'summary':'Frozen placement readiness adds a small but preregistered-stable increment to final-60s positive-floor break-risk context above geometry+Predict/strike+retained late quote information. Three chronological folds are eligible; all delta AUC values are nonnegative and the mean AUC/AP/log-loss gates pass. This is late-protection context only and explicitly does not retain Formation PREPARE/action authority.',
 'retestAllowed':False,
 'nextDistinct':'Replicate this frozen late placement-readiness protection route only on genuinely new independent Target/HFT chronology before any logic/action experiment. Do not threshold/bin the readiness score or reinterpret it as late Formation authority.'
}
for rp in ['data/research/r4_v0/r4_hourly_experiment_registry_v1.json','data/research/hourly_novel_test_registry_v1.json']:
    p=ROOT/rp; d=json.loads(p.read_text(encoding='utf-8')); arr=d['tests']
    if not any(x.get('testId')==tid for x in arr): arr.append(entry)
    p.write_text(json.dumps(d,ensure_ascii=False,indent=2),encoding='utf-8')
prog=ROOT/'data/research/r4_v0/hourly/r4_information_layer_progress_20260828_v40.md'
prog.write_text(f'''# R4 Information Layer Progress V40 — 2026-08-28 15:33\n\n- Exactly one novel bounded test: `{tid}` -> `{a['status']}`. Preregistered before scoring after both-registry and semantic duplicate audit.\n- Semantic novelty: Formation evidence already assigns placement readiness to PREPARE/participation; this cycle explicitly tests whether that frozen belief has a separate **final-60s positive-floor protection-context** role above the already-retained late weak-side quote stack. It does not carry Formation authority into late phase.\n- Layers: placement readiness = PREPARE-source BELIEF tested only as late PROTECTION context; weak quote = retained INFORMATION; Predict/strike = BELIEF context; portfolio/payoff geometry = LOGIC; output NOT_ACTION_AUTHORITY.\n- Cohort: {c['markets']} ordinary Target markets / {c['rows']} final-60s current-positive-floor rows; positive rate {c['positiveRate']:.3f}; public quote lag median {c['medianPublicLagMs']:.0f}ms / max {c['maxPublicLagMs']:.0f}ms; readiness SD {c['readinessStd']:.4f}. 2026-08-16 SEALED; no Echtgeld fit/ingest.\n- Result: {s['eligibleFolds']} chronological folds / {s['testPositives']} positive test labels; mean dAUC {s['meanDeltaAuc']:+.5f}, mean dAP {s['meanDeltaAp']:+.5f}, mean log-loss improvement {s['meanLogLossImprovement']:+.5f}, worst dAUC {s['worstFoldDeltaAuc']:+.5f}; all-fold AUC nonnegative = {s['allFoldAucNonnegative']}. Fixed KEEP gate passes.\n- Decision: `TESTED_KEEP_SIGNAL`, context-only. No order/size/owner/MPQ/late-Formation authority. Do not threshold/bin/model-sweep the readiness score.\n- Execution note: the first run exposed a fold-construction implementation gap for n<32 before any model scoring; the same preregistered testId/gate was rerun after only constructing three expanding chronological folds. No semantic/model/threshold change.\n- Broad stability: no action/champion code changed; last verified seed/no-regression remains 5/5 PASS. R4 champion, live R3-S/R3.1 and 8781 remain untouched.\n- Next: freeze this late context role and seek a genuinely new independent chronology replication before any separate logic/action-authority experiment.\n''',encoding='utf-8')
handoff=ROOT/'data/research/r4_v0/r4_hourly_research_handoff_v1.md'
with handoff.open('a',encoding='utf-8') as f:
 f.write(f'''\n\n## 2026-08-28 15:33 — LATE PLACEMENT-READINESS PROTECTION ROUTING V1 — KEEP_SIGNAL\n- Exactly one novel bounded test: `{tid}` -> `{a['status']}`; preregistered before scoring after both-registry + semantic duplicate audit.\n- Semantic novelty: placement readiness was previously a Formation PREPARE/participation belief. This test asks a different routing question: in final 0-60s with current floor>0, does the frozen readiness score add next-10s floor-break information above portfolio/payoff geometry, Predict/strike, and the already-kept late weak-side quote context? Formation PREPARE authority is explicitly excluded.\n- Layer assignment: placement readiness = BELIEF source tested only as LATE_PROTECTION_CONTEXT; weak-side quote economics = retained INFORMATION; Predict/strike = BELIEF context; portfolio/payoff = LOGIC; NOT_ACTION_AUTHORITY.\n- Cohort: {c['markets']} ordinary Target markets / {c['rows']} rows; positive rate {c['positiveRate']:.3f}; quote lag median {c['medianPublicLagMs']:.0f}ms / max {c['maxPublicLagMs']:.0f}ms; readiness SD {c['readinessStd']:.4f}. 2026-08-16 SEALED; no Echtgeld fit/ingest.\n- Three chronological folds / {s['testPositives']} positive test labels: mean dAUC {s['meanDeltaAuc']:+.5f}, mean dAP {s['meanDeltaAp']:+.5f}, mean log-loss improvement {s['meanLogLossImprovement']:+.5f}, worst dAUC {s['worstFoldDeltaAuc']:+.5f}; all fold AUC deltas nonnegative. Fixed gate PASS -> `TESTED_KEEP_SIGNAL`.\n- Interpretation: placement readiness has evidence for a separate late **risk-context** role, but this is not evidence that PREPARE retains Formation authority in final 60s. No order/size/owner/MPQ/KEEP/PULL/REPRICE authority.\n- The initial run had no folds because the test helper omitted n<32 chronology construction; no model scoring occurred. Only that implementation bug was corrected, keeping the exact preregistered hypothesis/model/gate.\n- Broad stability: no action/champion code changed; last verified seed/no-regression remains 5/5 PASS. R4 champion/live R3-S/R3.1/8781 unchanged.\n- Artifact: `{art_path}`; preregistration `{pre_path}`; progress V40; both registries updated.\n- Next distinct gap: freeze this route and replicate only on genuinely new independent chronology before any separate action-authority experiment; do not threshold/bin readiness or reinterpret it as late Formation authority.\n<!-- R4_LATE_PLACEMENT_READINESS_PROTECTION_ROUTING_V1_20260828_1533 -->\n''')
print(json.dumps({'status':a['status'],'progress':str(prog.relative_to(ROOT)),'registriesUpdated':True,'handoffUpdated':True},ensure_ascii=False))
