from __future__ import annotations
import json
from pathlib import Path
from datetime import datetime
from zoneinfo import ZoneInfo
ROOT=Path(__file__).resolve().parents[1]
ART=ROOT/'data/research/r4_v0/hourly/r4_late_crossing_quote_tail_routing_v1.json'
PRE=ROOT/'data/research/r4_v0/hourly/r4_late_crossing_quote_tail_routing_v1_preregistered.json'
REG=ROOT/'data/research/r4_v0/r4_hourly_experiment_registry_v1.json'
NOV=ROOT/'data/research/hourly_novel_test_registry_v1.json'
HAND=ROOT/'data/research/r4_v0/r4_hourly_research_handoff_v1.md'
PROG=ROOT/'data/research/r4_v0/hourly/r4_information_layer_progress_20260827_v7.md'
art=json.load(open(ART,encoding='utf-8')); now=datetime.now(ZoneInfo('Asia/Taipei')).isoformat()
entry={
'experimentId':art['testId'],'testedAt':now,'type':'FINAL60_CROSSING_PROTECTION_QUOTE_INFORMATION_ROUTING','status':art['status'],
'semanticKeys':['final 0-60s crossing protection','weak-side quote economics','late positive-floor break risk','information not action authority'],
'candidate':'In final 0-60s positive-floor states, test incremental value of strict-past weak-side public quote economics beyond portfolio/payoff geometry + Predict/strike for next-10s floor break; information context only.',
'artifact':'data/research/r4_v0/hourly/r4_late_crossing_quote_tail_routing_v1.json','preregisteredArtifact':'data/research/r4_v0/hourly/r4_late_crossing_quote_tail_routing_v1_preregistered.json','candidateTool':'tools/test_r4_late_crossing_quote_tail_routing_v1.py',
'primaryResult':{'markets':art['coverage']['markets'],'rows':art['coverage']['rows'],'positiveRate':art['coverage']['positiveRate'],'medianPublicLagMs':art['coverage']['medianPublicLagMs'],'maxPublicLagMs':art['coverage']['maxPublicLagMs'],'eligibleFolds':art['summary']['eligibleFolds'],'testPositives':art['summary']['testPositives'],'meanDeltaAuc':art['summary']['meanDeltaAuc'],'meanDeltaAp':art['summary']['meanDeltaAp'],'meanLogLossImprovement':art['summary']['meanLogLossImprovement'],'worstFoldDeltaAuc':art['summary']['worstFoldDeltaAuc'],'allFoldAucNonnegative':art['summary']['allFoldAucNonnegative'],'seedNoRegression5of5':True,'trainerRefresh':'TIMEOUT_NO_NEW_ARTIFACT'},
'conclusion':'TESTED_KEEP_SIGNAL for late-phase INFORMATION routing only. Quote economics adds chronology-stable incremental information for imminent positive-floor break risk in final 0-60s, beyond geometry+Predict/strike. It does not inherit Formation PREPARE authority and has no order/size/owner/MPQ authority.',
'promotion':'KEEP_SIGNAL_LATE_CROSSING_PROTECTION_INFORMATION_CONTEXT_NOT_ACTION_AUTHORITY','retestAllowed':False,
'nextDistinct':'Test whether queue-opportunity/receipt-clock execution context adds independent incremental value to the retained final-60s floor-reserve + quote-information stack, using a distinct late crossing-quality/tail target; remain information/belief only before any logic-layer authority.'}
r=json.load(open(REG,encoding='utf-8'))
if not any(x.get('experimentId')==art['testId'] or x.get('cycleId')==art['testId'] for x in r['experiments']): r['experiments'].append(entry)
REG.write_text(json.dumps(r,ensure_ascii=False,indent=2),encoding='utf-8')
n=json.load(open(NOV,encoding='utf-8'))
nt={'testId':art['testId'],'testedAt':now,'axis':'R4_FINAL60_CROSSING_PROTECTION_QUOTE_INFORMATION_ROUTING','semanticKeys':entry['semanticKeys'],'hypothesis':art['question'],'cohort':{'source':'ordinary Target BTC + strict-past public_research_archive_v1','markets':art['coverage']['markets'],'rows':art['coverage']['rows'],'phase':'0-60s positive-floor only','sealed20260816':True,'publicQuoteMaxLagMs':1500},'primaryResult':entry['primaryResult'],'status':art['status'],'artifact':entry['artifact'],'preregisteredArtifact':entry['preregisteredArtifact'],'tool':entry['candidateTool'],'conclusion':entry['conclusion'],'retestAllowed':False}
if not any(x.get('testId')==art['testId'] for x in n['tests']): n['tests'].append(nt)
NOV.write_text(json.dumps(n,ensure_ascii=False,indent=2),encoding='utf-8')
section=f'''\n\n## 2026-08-27 06:35 — LATE CROSSING QUOTE TAIL ROUTING V1 — KEEP_SIGNAL\n- Semantic novelty: prior R4 quote-economics tests were restricted to 60-300s Formation; this cycle tests final 0-60s positive-floor break risk as CROSSING_PROTECTION context. Existing late protection floor-reserve state remains baseline logic context rather than being replaced.\n- Layer assignment: weak-side public quote economics = INFORMATION; portfolio/payoff geometry = LOGIC state context; Predict/strike = BELIEF context; Formation PREPARE authority explicitly excluded. Output is NOT_ACTION_AUTHORITY.\n- Cohort: {art['coverage']['markets']} ordinary Target BTC markets / {art['coverage']['rows']} positive-floor rows in final 0-60s; strict-past public quote median lag {art['coverage']['medianPublicLagMs']:.0f}ms, max {art['coverage']['maxPublicLagMs']:.0f}ms; 2026-08-16 SEALED. Offline label: floor breaks to <=0 within next 10s.\n- Three chronological folds all improved AUC. Mean dAUC {art['summary']['meanDeltaAuc']:+.4f}; worst fold {art['summary']['worstFoldDeltaAuc']:+.4f}; mean dAP {art['summary']['meanDeltaAp']:+.4f}; mean log-loss improvement {art['summary']['meanLogLossImprovement']:+.4f}; test positives {art['summary']['testPositives']}. Fixed preregistered KEEP gate passed.\n- Decision: TESTED_KEEP_SIGNAL for late CROSSING_PROTECTION INFORMATION routing only. No threshold/action coupling, no owner/size/order/MPQ authority, and no carry-over of Formation PREPARE authority.\n- Trainer refresh attempted once and timed out without a new artifact; per timeout rule it was not relaunched unchanged. Seed/no-regression 5/5 PASS. Champion/live R3-S/R3.1/8781 unchanged.\n- Artifact: `data/research/r4_v0/hourly/r4_late_crossing_quote_tail_routing_v1.json`; preregistration: `data/research/r4_v0/hourly/r4_late_crossing_quote_tail_routing_v1_preregistered.json`; tool: `tools/test_r4_late_crossing_quote_tail_routing_v1.py`.\n- Next distinct gap: test receipt-clock queue-opportunity as independent incremental late protection context on top of floor reserve + quote information, before any separate logic-layer authority experiment.\n<!-- R4_LATE_CROSSING_QUOTE_TAIL_ROUTING_V1_20260827_0635 -->\n'''
h=HAND.read_text(encoding='utf-8')
if art['testId'] not in h: HAND.write_text(h+section,encoding='utf-8')
PROG.write_text(f'''# R4 Information Layer Progress 2026-08-27 V7\n\n## New result: final-60s crossing/protection quote routing — KEEP_SIGNAL\n\nA preregistered final-0-60s test found that strict-past weak-side public quote economics adds stable incremental information beyond portfolio/payoff geometry + Predict/strike for whether an already-positive floor will break within the next 10 seconds.\n\nCoverage: {art['coverage']['markets']} ordinary Target BTC markets / {art['coverage']['rows']} positive-floor late rows. Public quote lag median {art['coverage']['medianPublicLagMs']:.0f} ms, max {art['coverage']['maxPublicLagMs']:.0f} ms. Three chronological folds all had positive delta AUC; mean delta AUC {art['summary']['meanDeltaAuc']:+.4f}, worst fold {art['summary']['worstFoldDeltaAuc']:+.4f}, mean delta AP {art['summary']['meanDeltaAp']:+.4f}, mean log-loss improvement {art['summary']['meanLogLossImprovement']:+.4f}.\n\nLayer interpretation: quote economics remains INFORMATION. In final 0-60s it can be routed as local CROSSING_PROTECTION risk context. It is not a PREPARE/BUILD head, not an action rule, and has no order/size/owner/MPQ authority. Existing floor-reserve protection state remains the late management semantic baseline.\n\nNext: test receipt-clock queue-opportunity/execution reachability as independent incremental late protection context on top of floor reserve + quote information, with a distinct local crossing-quality/tail label and no action authority.\n''',encoding='utf-8')
print(json.dumps({'ok':True,'registryExperiments':len(r['experiments']),'novelTests':len(n['tests']),'progress':str(PROG.relative_to(ROOT)).replace('\\','/')},ensure_ascii=False))
