from pathlib import Path
import json
from datetime import datetime
ROOT=Path(__file__).resolve().parents[1]
test_id='R4_WEAK_COMPLETION_ECONOMICS_FLOOR_BELIEF_V1_20260827_0337'
artifact='data/research/r4_v0/hourly/r4_weak_completion_economics_floor_belief_v1.json'
prereg='data/research/r4_v0/hourly/r4_weak_completion_economics_floor_belief_v1_preregistered.json'
rep=json.loads((ROOT/artifact).read_text(encoding='utf-8'))
entry={
 'experimentId':test_id,'testedAt':'2026-08-27T03:42:00+08:00','type':'WEAK_COMPLETION_ECONOMICS_SAFE_FLOOR_BELIEF','status':'REJECTED',
 'semanticKeys':['weak completion economics','strict-past weak-side public quote economics','future 15s safe-floor improvement','belief not action authority'],
 'candidate':'Among Target weak-side BUILD/REPAIR states, test whether strict-past public weak-side quote economics adds information beyond portfolio geometry + Predict/strike context about future 15s safe-floor improvement.',
 'artifact':artifact,'preregisteredArtifact':prereg,'candidateTool':'tools/test_r4_weak_completion_economics_floor_belief_v1.py',
 'primaryResult':{'markets':rep['coverage']['markets'],'rows':rep['coverage']['rows'],'positiveRate':rep['coverage']['positiveRate'],'eligibleFolds':rep['summary']['eligibleFolds'],'meanDeltaAuc':rep['summary']['meanDeltaAuc'],'meanDeltaAp':rep['summary']['meanDeltaAp'],'meanLogLossImprovement':rep['summary']['meanLogLossImprovement'],'allFoldAucPositive':rep['summary']['allFoldAucPositive'],'formation60_300DeltaAuc':rep['phaseDiagnostics']['FORMATION_60_300']['increment']['deltaAuc'],'seedNoRegression5of5':True},
 'conclusion':'REJECTED. Strict-past public weak-side quote economics did not add stable chronological safe-floor belief information beyond geometry+Predict/strike. Mean AUC lift was ~+0.0011, not all folds were positive, and 60-300s Formation-phase pooled AUC worsened by ~0.0154. Do not threshold/model-sweep rescue this formulation. Quote economics may remain raw INFORMATION, but this head is not a validated BELIEF and has no action authority.',
 'promotion':'NONE_NOT_ACTION_AUTHORITY','retestAllowed':False,
 'nextDistinct':'Test information-source routing/interaction rather than another quote-price head: identify whether weak-side economics is useful conditionally inside PREPARE/BUILD belief regimes or late crossing/protection, using a distinct semantic target and preserving 0-60s authority separation.'
}
# R4 registry
p=ROOT/'data/research/r4_v0/r4_hourly_experiment_registry_v1.json'; d=json.loads(p.read_text(encoding='utf-8'))
if not any(x.get('experimentId')==test_id or x.get('cycleId')==test_id for x in d['experiments']): d['experiments'].append(entry);p.write_text(json.dumps(d,ensure_ascii=False,indent=2),encoding='utf-8')
# global novelty ledger
p2=ROOT/'data/research/hourly_novel_test_registry_v1.json'; n=json.loads(p2.read_text(encoding='utf-8'))
nov={'testId':test_id,'testedAt':'2026-08-27T03:42:00+08:00','axis':'R4_WEAK_COMPLETION_ECONOMICS_SAFE_FLOOR_BELIEF','semanticKeys':entry['semanticKeys'],'hypothesis':entry['candidate'],'cohort':{'source':'Target ordinary BTC + strict-past public_research_archive_v1','markets':rep['coverage']['markets'],'rows':rep['coverage']['rows'],'sealed20260816':True},'primaryResult':entry['primaryResult'],'status':'TESTED_REJECTED','artifact':artifact,'preregisteredArtifact':prereg,'tool':'tools/test_r4_weak_completion_economics_floor_belief_v1.py','conclusion':entry['conclusion'],'retestAllowed':False}
if not any(x.get('testId')==test_id for x in n['tests']): n['tests'].append(nov);p2.write_text(json.dumps(n,ensure_ascii=False,indent=2),encoding='utf-8')
# handoff
hp=ROOT/'data/research/r4_v0/r4_hourly_research_handoff_v1.md'; text=hp.read_text(encoding='utf-8'); marker='<!-- R4_WEAK_COMPLETION_ECONOMICS_FLOOR_BELIEF_V1_20260827_0342 -->'
section=f'''\n\n## 2026-08-27 03:42 — WEAK COMPLETION ECONOMICS SAFE-FLOOR BELIEF V1 — REJECTED\n- Canonical information-layer contract and both registries were read first. Semantic audit found prior unregistered weak-completion pilot artifacts: the old runtime-safe head predicted whether Target continued REPAIR within 5s and was unstable; this cycle deliberately used a different semantic target, future 15s safe-floor improvement.\n- Layer assignment: weak-side public quote = INFORMATION; derived completion-economics head = BELIEF candidate; portfolio/payoff geometry remains LOGIC state context. No action authority.\n- Cohort: {rep['coverage']['markets']} ordinary Target BTC markets / {rep['coverage']['rows']} weak-side BUILD/REPAIR rows, strict-past public quote lag <=1500ms; 2026-08-16 SEALED. Future Target trajectory is offline label only; Target chosen action price, winner and settlement are excluded.\n- Fixed chronological result: 3 eligible folds; mean quote-economics AUC lift {rep['summary']['meanDeltaAuc']:.4f}, AP lift {rep['summary']['meanDeltaAp']:.4f}, log-loss improvement {rep['summary']['meanLogLossImprovement']:.4f}; not all fold AUC lifts were positive. In the 60-300s Formation phase, pooled AUC changed by {rep['phaseDiagnostics']['FORMATION_60_300']['increment']['deltaAuc']:.4f}. Final 0-60s remained diagnostic only and does not grant Formation authority.\n- Decision: REJECTED. Do not threshold/model-sweep rescue this quote-price belief formulation. Raw quote economics remains INFORMATION, but it is not validated as an independent weak-completion BELIEF from this target.\n- Trainer refresh: 500 ordinary Target markets, acquisition Spearman 0.7175, preservation 0.7352; frozen Echtgeld markets remained exactly 8. Seed/no-regression 5/5 PASS. Champion/live R3-S/R3.1/8781 unchanged.\n- Artifact: `{artifact}`; preregistration: `{prereg}`.\n- Next distinct gap: information-source routing/conditional interaction. Test whether quote economics contributes only inside specific PREPARE/BUILD belief regimes or late crossing/protection context, with a semantically distinct target; do not revive direct price/action translations.\n{marker}\n'''
if marker not in text: hp.write_text(text+section,encoding='utf-8')
# progress v4
v3=ROOT/'data/research/r4_v0/hourly/r4_information_layer_progress_20260827_v3.md';v4=ROOT/'data/research/r4_v0/hourly/r4_information_layer_progress_20260827_v4.md';base=v3.read_text(encoding='utf-8')
prog=f'''\n\n## Weak completion economics safe-floor belief V1 — REJECTED\nA semantically distinct runtime-safe belief test replaced the old next-action label with future 15s safe-floor improvement. Strict-past weak-side public quote economics added only ~+0.0011 mean AUC beyond portfolio geometry + Predict/strike, failed all-fold sign stability, and worsened pooled 60-300s Formation AUC by ~0.0154. Therefore do not create a standalone weak-completion quote-price BELIEF from this formulation. Quote economics stays INFORMATION only. Final 0-60s remains a separate crossing/protection routing problem.\n\nNext: test conditional information routing/interactions rather than another direct quote-price head.\n'''
v4.write_text(base+prog,encoding='utf-8')
print(json.dumps({'ok':True,'r4RegistryTotal':len(d['experiments']),'novelRegistryTotal':len(n['tests']),'handoffUpdated':True,'progress':str(v4.relative_to(ROOT)).replace('\\','/')}))
