from pathlib import Path
p=Path('tools/hftbacktest_r2_fixed_tape_tox_episode_cf_v0.py')
s=p.read_text(encoding='utf-8')
old='''            state={"atMs":int(t),"action":"SUPERVISOR_CF_DECISION","selected":EPISODE_OVERRIDE,"deltaTrack":dtrack,"deltaMaker":dmaker,"trackAbs":track_abs,"makerAbs":maker_abs,"trackSigned":track_signed,"makerSigned":maker_signed,"makerUp":float(actual.maker_up),"makerDown":float(actual.maker_down),"desiredMakerUp":float(desired_maker["UP"]),"desiredMakerDown":float(desired_maker["DOWN"]),"desiredTakerUp":float(desired_taker["UP"]),"desiredTakerDown":float(desired_taker["DOWN"]),"activeUp":active_maker.get("UP") is not None,"activeDown":active_maker.get("DOWN") is not None,"makerFillCount":sum(1 for e in fill_log if e.get("role")=="MAKER"),"toxCancelCount":sum(1 for e in toxicity_events if e.get("action")=="TOXIC_CANCEL_REQUEST"),"secondsLeft":float((latest_public_snapshot or {}).get("secondsLeft")) if (latest_public_snapshot or {}).get("secondsLeft") is not None else None}\n            episode_events.append(state)\n'''
new='''            state={"atMs":int(t),"action":"SUPERVISOR_CF_DECISION","selected":EPISODE_OVERRIDE,"deltaTrack":dtrack,"deltaMaker":dmaker,"trackAbs":track_abs,"makerAbs":maker_abs,"trackSigned":track_signed,"makerSigned":maker_signed,"makerUp":float(actual.maker_up),"makerDown":float(actual.maker_down),"desiredMakerUp":float(desired_maker["UP"]),"desiredMakerDown":float(desired_maker["DOWN"]),"desiredTakerUp":float(desired_taker["UP"]),"desiredTakerDown":float(desired_taker["DOWN"]),"activeUp":active_maker.get("UP") is not None,"activeDown":active_maker.get("DOWN") is not None,"makerFillCount":sum(1 for e in fill_log if e.get("role")=="MAKER"),"toxCancelCount":sum(1 for e in toxicity_events if e.get("action")=="TOXIC_CANCEL_REQUEST"),"secondsLeft":float((latest_public_snapshot or {}).get("secondsLeft")) if (latest_public_snapshot or {}).get("secondsLeft") is not None else None}\n            # Strict-past memory windows.  These summarize the execution path that led to this checkpoint.\n            for sec in (6,20,60):\n                lo=int(t)-sec*1000\n                mf=[e for e in fill_log if e.get("role")=="MAKER" and int(e.get("eventMs") or 0)>=lo and int(e.get("eventMs") or 0)<=int(t)]\n                state[f"makerFillCount{sec}s"]=float(len(mf))\n                state[f"makerFillShares{sec}s"]=float(sum(float(e.get("shares") or 0.0) for e in mf))\n                for sd in ("UP","DOWN"):\n                    z=[e for e in mf if str(e.get("side"))==sd]\n                    state[f"makerFillCount{sd}{sec}s"]=float(len(z))\n                    state[f"makerFillShares{sd}{sec}s"]=float(sum(float(e.get("shares") or 0.0) for e in z))\n                tc=[e for e in toxicity_events if e.get("action")=="TOXIC_CANCEL_REQUEST" and int(e.get("atMs") or 0)>=lo and int(e.get("atMs") or 0)<=int(t)]\n                state[f"toxCancelCount{sec}s"]=float(len(tc))\n                sub=[m for m in maker_meta.values() if int(m.get("submittedAtMs") or 0)>=lo and int(m.get("submittedAtMs") or 0)<=int(t)]\n                state[f"makerSubmitCount{sec}s"]=float(len(sub))\n                state[f"makerSubmitShares{sec}s"]=float(sum(float(m.get("qty") or 0.0) for m in sub))\n            ps=latest_public_snapshot or {}\n            for k in ("directionScore","spotReturn250msBps","spotReturn1sBps","spotReturn3sBps","spotReturn5sBps","futuresReturn250msBps","futuresReturn1sBps","futuresReturn3sBps","futuresReturn5sBps","spotQueueImbalance","futuresQueueImbalance","spotTakerImbalance250ms","spotTakerImbalance1s","futuresTakerImbalance250ms","futuresTakerImbalance1s","perpSpotBasisBps","spotMinusChainlinkBps"):\n                v=ps.get(k); state[k]=float(v) if v is not None else None\n            episode_events.append(state)\n'''
assert old in s
s=s.replace(old,new)
p.write_text(s,encoding='utf-8')
print('patched')
