from pathlib import Path
p=Path('tools/audit_r4_p0_provenance_journal_v1.py')
s=p.read_text(encoding='utf-8')
s=s.replace("    fill_lineage_fail = 0\n", "    fill_lineage_fail = 0\n    post_completion_carrier_count = 0\n")
needle="""        fill_events = [e for e in evs if e.get('event_type') in {'PARTIAL_FILL', 'FULL_FILL'}]\n"""
repl="""        # A completed responsibility is terminal. New carrier creation after completion means\n        # cancel/fill-race lineage leaked into a later, distinct economic responsibility.\n        _complete_idx = next((i for i,e in enumerate(evs) if e.get('event_type') == 'RESPONSIBILITY_COMPLETED'), None)\n        _post_completion_carriers = 0 if _complete_idx is None else sum(1 for e in evs[_complete_idx+1:] if e.get('event_type') == 'CARRIER_INTENT_CREATED')\n        post_completion_carrier_count += _post_completion_carriers\n\n        fill_events = [e for e in evs if e.get('event_type') in {'PARTIAL_FILL', 'FULL_FILL'}]\n"""
if needle not in s: raise SystemExit('terminal insert needle missing')
s=s.replace(needle,repl)
s=s.replace("            'fillLineageExact': fill_ok,\n", "            'fillLineageExact': fill_ok,\n            'postCompletionCarrierCount': _post_completion_carriers,\n")
s=s.replace("        'orphanEventCount': orphan_events,\n", "        'orphanEventCount': orphan_events,\n        'postCompletionCarrierCount': post_completion_carrier_count,\n")
s=s.replace("            for key in ('sequenceFailureCount','receivedTimeFailureCount','rootOpenFailureCount','parentChainFailureCount','stateReconstructionFailureCount','remainingObligationFailureCount','fillLineageFailureCount','duplicateExecutionIdCount','orphanEventCount'):\n", "            for key in ('sequenceFailureCount','receivedTimeFailureCount','rootOpenFailureCount','parentChainFailureCount','stateReconstructionFailureCount','remainingObligationFailureCount','fillLineageFailureCount','duplicateExecutionIdCount','orphanEventCount','postCompletionCarrierCount'):\n")
s=s.replace("    structural_exact = all(failures[k] == 0 for k in ('sequenceFailureCount','receivedTimeFailureCount','rootOpenFailureCount','parentChainFailureCount','orphanEventCount'))\n", "    structural_exact = all(failures[k] == 0 for k in ('sequenceFailureCount','receivedTimeFailureCount','rootOpenFailureCount','parentChainFailureCount','orphanEventCount','postCompletionCarrierCount'))\n")
# Insert cancel-resolution audit totals.
s=s.replace("    branch_continuity_num = branch_continuity_den = 0\n", "    branch_continuity_num = branch_continuity_den = 0\n    cancel_resolution_num = cancel_resolution_den = 0\n")
needle2="""        for rr in stress['responsibilityRows']:\n            if rr['intentCount'] >= 2:\n                branch_continuity_den += 1\n                if rr['parentChainValid']:\n                    branch_continuity_num += 1\n        market_rows.append({'marketId': r.get('marketId'), 'keep': keep, 'stress': stress, 'preStressPrefix': pref, 'stressCancelEvents': len(r.get('provenanceStressEvents') or [])})\n"""
repl2="""        for rr in stress['responsibilityRows']:\n            if rr['intentCount'] >= 2:\n                branch_continuity_den += 1\n                if rr['parentChainValid']:\n                    branch_continuity_num += 1\n        # Every injected cancel must resolve in one of exactly two safe ways:\n        # (A) responsibility fills/completes during cancel race; or\n        # (B) terminal cancel is followed by a new carrier on the SAME root linked to old intent.\n        stress_evs = r.get('reinsertProvenanceJournal') or []\n        for se in (r.get('provenanceStressEvents') or []):\n            cancel_resolution_den += 1\n            rid = str(se.get('responsibilityId')); old_iid = str(se.get('oldIntentId')); at = int(se.get('cancelRequestedAtMs') or 0)\n            future = [e for e in stress_evs if str(e.get('responsibility_id')) == rid and int(e.get('received_at_ms') or 0) >= at]\n            completed = any(e.get('event_type') == 'RESPONSIBILITY_COMPLETED' for e in future)\n            replaced = any(e.get('event_type') == 'CARRIER_INTENT_CREATED' and str(e.get('parent_intent_id')) == old_iid for e in future)\n            if completed or replaced:\n                cancel_resolution_num += 1\n        market_rows.append({'marketId': r.get('marketId'), 'keep': keep, 'stress': stress, 'preStressPrefix': pref, 'stressCancelEvents': len(r.get('provenanceStressEvents') or [])})\n"""
if needle2 not in s: raise SystemExit('cancel resolution insert missing')
s=s.replace(needle2,repl2)
s=s.replace("    branch_rate = branch_continuity_num / max(1, branch_continuity_den)\n", "    branch_rate = branch_continuity_num / max(1, branch_continuity_den)\n    cancel_resolution_rate = cancel_resolution_num / max(1, cancel_resolution_den)\n")
s=s.replace("        and branch_continuity_den >= len(market_rows) and branch_rate == 1.0\n", "        and branch_continuity_den >= len(market_rows) and branch_rate == 1.0\n        and cancel_resolution_den >= len(market_rows) and cancel_resolution_rate == 1.0\n")
s=s.replace("            'branchContinuityChecks': branch_continuity_den,\n", "            'branchContinuityChecks': branch_continuity_den,\n            'cancelResolutionExactRate': cancel_resolution_rate,\n            'cancelResolutionChecks': cancel_resolution_den,\n")
s=s.replace("            'branchContinuityRate': 1.0,\n", "            'branchContinuityRate': 1.0,\n            'cancelResolutionExactRate': 1.0,\n            'postCompletionCarrierCount': 0,\n")
p.write_text(s,encoding='utf-8')
print('patched terminal/cancel invariants')
