from pathlib import Path
p=Path('tools/test_r4_maker_continuous_runtime_two_axis_v37.py')
s=p.read_text(encoding='utf-8')
s=s.replace("POLICIES=('CONT_STATE_H2_SUSPEND_EXACT_FIRST_LATE_TOUCH1',)","POLICIES=('CONT_STATE_H2_SUSPEND_RUNTIME_TWO_AXIS_TOUCH1',)")
insert='''\n\ndef public_source_before(rows,t,max_age_ms=1000):\n    if not rows:return None\n    ts=[x[0] for x in rows];j=bisect.bisect_left(ts,int(t))-1\n    if j<0:return None\n    at,z=rows[j]\n    if int(t)-at>int(max_age_ms):return None\n    return z\n\ndef _sgn(side): return 1.0 if str(side).upper()=='UP' else -1.0\n\ndef runtime_adverse(pub_rows,t,weak_side):\n    z=public_source_before(pub_rows,t,1000)\n    if z is None:return None,{'reason':'NO_STRICT_PAST_PUBLIC_SOURCE'}\n    dom='DOWN' if str(weak_side).upper()=='UP' else 'UP'\n    try:\n        pu=float(z.get('predictUpMid'))\n        st=float(z.get('spotTakerImbalance1s'))\n        ft=float(z.get('futuresTakerImbalance1s'))\n    except (TypeError,ValueError):return None,{'reason':'MISSING_ADVERSE_INPUT'}\n    pa=_sgn(dom)*(pu-.5)*2.0; sa=_sgn(dom)*st; fa=_sgn(dom)*ft\n    score=.40*pa+.30*sa+.30*fa\n    return score,{'reason':'OK','dominantSide':dom,'predictAligned':pa,'spotTaker1sAligned':sa,'futuresTaker1sAligned':fa,'adverse':score}\n\ndef _queue_at_updates(updates,t,side,target_px):\n    book={'bids':{},'asks':{}}\n    for u in sorted(updates or [],key=lambda r:(int(r[1]),int(r[0]))):\n        if int(u[1])>int(t):break\n        cp=int(u[3]);chg=u[6] or {}\n        if cp and u[4] is not None and u[5] is not None:\n            book={'bids':{float(k):float(v) for k,v in (u[4] or {}).items()},'asks':{float(k):float(v) for k,v in (u[5] or {}).items()}}\n        else:apply_book(book,chg)\n    tp=round(float(target_px)+1e-12,2)\n    if str(side).upper()=='UP': return float(book['bids'].get(tp,0.0))\n    native=round(1.0-tp+1e-12,2); return float(book['asks'].get(native,0.0))\n\ndef runtime_queue_decay_1s(archive,t,side,original_px):\n    ups=archive.get('updates') or [];q0=_queue_at_updates(ups,int(t)-1000,side,original_px);q1=_queue_at_updates(ups,int(t),side,original_px)\n    if q0<=EPS:return None,{'reason':'NO_START_QUEUE','queueStartShares':q0,'queueSeamShares':q1}\n    change=q1-q0; decay=-change/q0\n    return decay,{'reason':'OK','queueStartShares':q0,'queueSeamShares':q1,'queueChangeShares':change,'queueChangeNorm':change/q0,'queueDecay1s':decay}\n'''
s=s.replace('\ndef quant(vals,p):',insert+'\ndef quant(vals,p):')
s=s.replace("mid=int(d['marketId']); events,times,meta=tape.build_archive_events(mid,trade_offset='mid'); br=book_rows(mid); pub=public_source_rows(mid)","mid=int(d['marketId']); archive=load_archive(ROOT/'data/execution_tape_v1/markets'/f'{mid}.json.xz'); events,times,meta=tape.build_archive_events(mid,trade_offset='mid'); br=book_rows(mid); pub=public_source_rows(mid)")
s=s.replace("    suspended_context={}\n", "    suspended_context={}\n    runtime_late_trace=[]\n")
old="""            late_mode=policy=='CONT_STATE_H2_SUSPEND_EXACT_FIRST_LATE_TOUCH1'\n            ev=EXACT_EVENT_MAP.get(str(mid)) or EXACT_EVENT_MAP.get(mid)\n            late_candidate=bool(late_mode and ev is not None and int(cur_t)==int(ev.get('t')) and str(lid)==str(ev.get('logical')) and weak_now==o['side'] and float(g_now['absNet'])>=36.0-EPS and not any(z['side']==o['side'] for _hid,z,_s,_rem in reservation_rows() if _hid not in cancel_req))\n            if late_candidate: counts['lateWeakCandidateChecks']+=1\n"""
new="""            late_mode=policy=='CONT_STATE_H2_SUSPEND_RUNTIME_TWO_AXIS_TOUCH1'\n            ev=EXACT_EVENT_MAP.get(str(mid)) or EXACT_EVENT_MAP.get(mid)\n            late_anchor=bool(late_mode and ev is not None and int(cur_t)==int(ev.get('t')) and str(lid)==str(ev.get('logical')) and weak_now==o['side'] and float(g_now['absNet'])>=36.0-EPS and not any(z['side']==o['side'] for _hid,z,_s,_rem in reservation_rows() if _hid not in cancel_req))\n            late_candidate=False\n            if late_anchor:\n                counts['runtimeLateAnchorChecks']+=1\n                adv,ad=runtime_adverse(pub,cur_t,o['side']); qd,qdmeta=runtime_queue_decay_1s(archive,cur_t,o['side'],o['px'])\n                late_candidate=bool(adv is not None and qd is not None and adv<=0.0+EPS and qd>=0.0-EPS)\n                runtime_late_trace.append({'t':int(cur_t),'logical':lid,'side':o['side'],'originalPx':float(o['px']),'adverse':adv,'queueDecay1s':qd,'eligible':late_candidate,'adverseMeta':ad,'queueMeta':qdmeta})\n                if late_candidate:counts['runtimeTwoAxisEligible']+=1\n                else:counts['runtimeTwoAxisSuspend']+=1\n            if late_candidate: counts['lateWeakCandidateChecks']+=1\n"""
if old not in s: raise SystemExit('late block not found')
s=s.replace(old,new)
s=s.replace("if late_candidate and policy=='CONT_STATE_H2_SUSPEND_EXACT_FIRST_LATE_TOUCH1':","if late_candidate and policy=='CONT_STATE_H2_SUSPEND_RUNTIME_TWO_AXIS_TOUCH1':")
s=s.replace("'continuousStateTrace':state_trace,**ps}","'continuousStateTrace':state_trace,'runtimeLateDecisionTrace':runtime_late_trace,**ps}")
s=s.replace("'version':'R4_ROLLING_QUEUE_OPTION_LIFECYCLE_V1'","'version':'R4_RUNTIME_TWO_AXIS_V37'")
p.write_text(s,encoding='utf-8')
print('patched',p)
