from pathlib import Path
p=Path('tools/hftbacktest_r4_p0_provenance_journal_v1.py')
s=p.read_text(encoding='utf-8')
s=s.replace('def run_recovery(mid: int, queue_reinsert: bool = False, candidate_delay_ms: int = 0) -> dict[str, Any]:',
            'def run_recovery(mid: int, queue_reinsert: bool = False, candidate_delay_ms: int = 0, provenance_stress_cancel: bool = False) -> dict[str, Any]:')
needle='''    pending_reinsert_lineage: dict[str, tuple[str, str] | None] = {"UP": None, "DOWN": None}\n    lineage_serial = 0\n'''
repl='''    pending_reinsert_lineage: dict[str, tuple[str, str] | None] = {"UP": None, "DOWN": None}\n    provenance_stress_done: dict[str, bool] = {"UP": False, "DOWN": False}\n    provenance_stress_events: list[dict[str, Any]] = []\n    lineage_serial = 0\n'''
if needle not in s: raise SystemExit('stress vars needle missing')
s=s.replace(needle,repl)
needle='''            book.advance(mid, t)\n            if candidate_at_ms is not None and candidate_recovery_side is not None:\n'''
repl='''            book.advance(mid, t)\n\n            # Deterministic P0-A lifecycle exam. It exists only to force a real cancel->reinsert\n            # path under receipt-clock HFT so provenance can be validated independently of the\n            # strategy candidate detector. It does not run in baseline/production code.\n            if provenance_stress_cancel:\n                for _stress_side in ("UP", "DOWN"):\n                    if provenance_stress_done[_stress_side]:\n                        continue\n                    _stress_num = active_maker.get(_stress_side)\n                    if _stress_num is None:\n                        continue\n                    _stress_om = maker_meta[int(_stress_num)]\n                    if int(t) - int(_stress_om.get("submittedAtMs") or t) < 1000:\n                        continue\n                    _stress_snap = ex.order_snapshot(bt, int(_stress_num))\n                    _stress_cur = bt.orders(0).get(int(_stress_num))\n                    if _stress_snap.get("status") not in {"NEW", "PARTIALLY_FILLED"} or _stress_cur is None or not bool(_stress_cur.cancellable):\n                        continue\n                    try:\n                        bt.cancel(0, int(_stress_num), False)\n                    except Exception:\n                        continue\n                    _resp = str(_stress_om.get("responsibilityId")); _intent = str(_stress_om.get("intentId")); _rs = responsibility_state[_resp]\n                    pending_reinsert_lineage[_stress_side] = (_resp, _intent)\n                    emit_provenance('CANCEL_REQUESTED', int(t), responsibility_id=_resp, intent_id=_intent, side=_stress_side,\n                                    client_order_id=_stress_om.get('clientOrderId'), venue_order_id=str(_stress_num),\n                                    requested_qty=float(_stress_om.get('qty') or 0.0), cum_confirmed_fill_qty=float(_rs['confirmed_qty']),\n                                    leaves_qty=max(0.0,float(_rs['requested_qty'])-float(_rs['confirmed_qty'])),\n                                    price=float(_stress_om.get('price') or 0.0), lifecycle_state='CANCEL_PENDING',\n                                    extras={'exam':'P0_DETERMINISTIC_CANCEL_REINSERT_V1'})\n                    provenance_stress_done[_stress_side] = True\n                    provenance_stress_events.append({'side':_stress_side,'cancelRequestedAtMs':int(t),'oldOrderNum':int(_stress_num),\n                                                     'responsibilityId':_resp,'oldIntentId':_intent})\n\n            if candidate_at_ms is not None and candidate_recovery_side is not None:\n'''
if needle not in s: raise SystemExit('stress insertion needle missing')
s=s.replace(needle,repl)
needle='''            "provenanceJournal": provenance_events,\n            "provenanceResponsibilityState": responsibility_state,\n'''
repl='''            "provenanceJournal": provenance_events,\n            "provenanceResponsibilityState": responsibility_state,\n            "provenanceStressEvents": provenance_stress_events,\n'''
if needle not in s: raise SystemExit('return stress needle missing')
s=s.replace(needle,repl)
needle='''def main() -> None:\n    ap=argparse.ArgumentParser(); ap.add_argument("--market-ids",required=True); a=ap.parse_args(); mids=[int(x) for x in a.market_ids.split(",") if x.strip()]\n    rows=[]\n    for i,mid in enumerate(mids,1):\n        keep=run_recovery(mid,queue_reinsert=False); rein=run_recovery(mid,queue_reinsert=True)\n'''
repl='''def main() -> None:\n    ap=argparse.ArgumentParser(); ap.add_argument("--market-ids",required=True); ap.add_argument("--provenance-stress-cancel",action="store_true"); a=ap.parse_args(); mids=[int(x) for x in a.market_ids.split(",") if x.strip()]\n    rows=[]\n    for i,mid in enumerate(mids,1):\n        keep=run_recovery(mid,queue_reinsert=False,provenance_stress_cancel=False); rein=run_recovery(mid,queue_reinsert=False,provenance_stress_cancel=bool(a.provenance_stress_cancel))\n'''
if needle not in s: raise SystemExit('main needle missing')
s=s.replace(needle,repl)
needle='''             "keepProvenanceJournal":keep.get("provenanceJournal"),"reinsertProvenanceJournal":rein.get("provenanceJournal"),\n             "keepProvenanceSummary":keep.get("provenanceSummary"),"reinsertProvenanceSummary":rein.get("provenanceSummary"),\n'''
repl='''             "keepProvenanceJournal":keep.get("provenanceJournal"),"reinsertProvenanceJournal":rein.get("provenanceJournal"),\n             "keepProvenanceSummary":keep.get("provenanceSummary"),"reinsertProvenanceSummary":rein.get("provenanceSummary"),\n             "provenanceStressEvents":rein.get("provenanceStressEvents"),\n'''
if needle not in s: raise SystemExit('row needle missing')
s=s.replace(needle,repl)
start='''    p0 = {"markets": len(rows), "eligibleCandidates": len(v), "branchSameResponsibility": 0, "branchChecked": 0,\n          "duplicateExecutionApplications": 0, "orphanEvents": 0}\n    for r in rows:\n        for k in ("keepProvenanceSummary","reinsertProvenanceSummary"):\n            sm = r.get(k) or {}; p0["duplicateExecutionApplications"] += int(sm.get("duplicateExecutionApplicationCount") or 0); p0["orphanEvents"] += int(sm.get("orphanEventCount") or 0)\n        q = r.get("reinsertEvent") or {}\n        if q.get("responsibilityId") and q.get("newResponsibilityId"):\n            p0["branchChecked"] += 1\n            if q.get("responsibilityId") == q.get("newResponsibilityId") and q.get("parentIntentId") == q.get("oldIntentId"):\n                p0["branchSameResponsibility"] += 1\n    p0["branchContinuityRate"] = p0["branchSameResponsibility"] / max(1,p0["branchChecked"])\n'''
repl='''    p0 = {"markets": len(rows), "eligibleCandidates": len(v), "branchSameResponsibility": 0, "branchChecked": 0,\n          "duplicateExecutionApplications": 0, "orphanEvents": 0, "stressCancelEvents": 0, "parentChainFailures": 0}\n    for r in rows:\n        for k in ("keepProvenanceSummary","reinsertProvenanceSummary"):\n            sm = r.get(k) or {}; p0["duplicateExecutionApplications"] += int(sm.get("duplicateExecutionApplicationCount") or 0); p0["orphanEvents"] += int(sm.get("orphanEventCount") or 0)\n        p0["stressCancelEvents"] += len(r.get("provenanceStressEvents") or [])\n        evs = r.get("reinsertProvenanceJournal") or []\n        by_resp = defaultdict(list)\n        for ev in evs:\n            if ev.get("event_type") == "CARRIER_INTENT_CREATED": by_resp[str(ev.get("responsibility_id"))].append(ev)\n        for rid, xs in by_resp.items():\n            if len(xs) < 2: continue\n            p0["branchChecked"] += 1\n            known=[]; good=True\n            for j,ev in enumerate(xs):\n                iid=ev.get("intent_id"); parent=ev.get("parent_intent_id")\n                if j>0 and parent not in known:\n                    good=False; p0["parentChainFailures"] += 1\n                known.append(iid)\n            if good: p0["branchSameResponsibility"] += 1\n    p0["branchContinuityRate"] = p0["branchSameResponsibility"] / max(1,p0["branchChecked"])\n'''
if start not in s: raise SystemExit('audit needle missing')
s=s.replace(start,repl)
p.write_text(s,encoding='utf-8')
print('patched stress',p)
