from pathlib import Path
p=Path('tools/hftbacktest_r4_p0_provenance_journal_v1.py')
s=p.read_text(encoding='utf-8')
needle="""                    emit_provenance('FULL_FILL' if leaves_root <= EPS else 'PARTIAL_FILL', fill_ms,\n                                    responsibility_id=resp_id, intent_id=intent_id, side=side,\n                                    client_order_id=om.get('clientOrderId'), venue_order_id=str(num), execution_id=exec_id,\n                                    requested_qty=float(om.get('qty') or 0.0), cum_confirmed_fill_qty=float(rs['confirmed_qty']),\n                                    leaves_qty=leaves_root, price=px, lifecycle_state='FILLED' if leaves_root <= EPS else 'PARTIAL')\n                    if leaves_root <= EPS and rs.get('status') != 'COMPLETED':\n                        rs['status'] = 'COMPLETED'\n                        emit_provenance('RESPONSIBILITY_COMPLETED', fill_ms, responsibility_id=resp_id, intent_id=intent_id,\n                                        side=side, cum_confirmed_fill_qty=float(rs['confirmed_qty']), leaves_qty=0.0,\n                                        lifecycle_state='COMPLETED')\n"""
repl="""                    emit_provenance('FULL_FILL' if leaves_root <= EPS else 'PARTIAL_FILL', fill_ms,\n                                    responsibility_id=resp_id, intent_id=intent_id, side=side,\n                                    client_order_id=om.get('clientOrderId'), venue_order_id=str(num), execution_id=exec_id,\n                                    requested_qty=float(om.get('qty') or 0.0), cum_confirmed_fill_qty=float(rs['confirmed_qty']),\n                                    leaves_qty=leaves_root, price=px, lifecycle_state='FILLED' if leaves_root <= EPS else 'PARTIAL',\n                                    received_at_ms=int(now))\n                    if leaves_root <= EPS and rs.get('status') != 'COMPLETED':\n                        rs['status'] = 'COMPLETED'\n                        # Cancel/fill race: a responsibility completed while cancel was pending.\n                        # Any pending reinsert lineage for this root must be released; later demand is a NEW responsibility.\n                        _pending = pending_reinsert_lineage.get(side)\n                        if _pending is not None and str(_pending[0]) == resp_id:\n                            pending_reinsert_lineage[side] = None\n                        emit_provenance('RESPONSIBILITY_COMPLETED', fill_ms, responsibility_id=resp_id, intent_id=intent_id,\n                                        side=side, cum_confirmed_fill_qty=float(rs['confirmed_qty']), leaves_qty=0.0,\n                                        lifecycle_state='COMPLETED', received_at_ms=int(now),\n                                        extras={'cancelRaceResolved': bool(_pending is not None and str(_pending[0]) == resp_id)})\n"""
if needle not in s: raise SystemExit('fill block needle missing')
s=s.replace(needle,repl)
p.write_text(s,encoding='utf-8')
print('patched cancel-race + receive clock')
