from __future__ import annotations
import argparse,json
from pathlib import Path
from collections import defaultdict,deque,Counter
EPS=1e-9

def analyze_row(r):
    meta={str(x['key']):x for x in (r.get('riskTrancheLedger') or [])}
    splits=[x for x in (r.get('splitEvents') or []) if x.get('event')=='ROLE_FILL_SPLIT']
    pays=[x for x in (r.get('r257Events') or []) if x.get('event')=='R257_RISK_REPAIR_OBLIGATION_PAYMENT']
    # Build strict event stream. Native process appends ROLE_FILL_SPLIT before R257 payment telemetry
    # for the same physical fill; therefore risk-fill births at a clock are visible before a later
    # R257 payment generated by the same process call, but no future-clock tranche exists early.
    stream=[]
    seq=0
    for x in splits:
        seq+=1
        k=str(x.get('key'));inc=float(x.get('fillInc') or 0.0)
        if k in meta and inc>EPS:
            stream.append((int(x.get('t') or 0),0,seq,'RISK_BIRTH',x))
    seq=0
    for e in pays:
        seq+=1;stream.append((int(e.get('t') or 0),1,seq,'PAY',e))
    stream.sort(key=lambda z:(z[0],z[1],z[2]))
    repair_lookup={(int(x.get('t') or 0),str(x.get('key'))):x for x in splits if float(x.get('repairAllocated') or 0.0)>EPS}
    tranches=[];by_gen=defaultdict(deque);orphan=0.0
    for t,_,__,kind,e in stream:
        if kind=='RISK_BIRTH':
            k=str(e.get('key'));m=meta[k];inc=float(e.get('fillInc') or 0.0);gen=int(m.get('generation') or e.get('generationAtSubmit') or -1)
            z={'id':len(tranches)+1,'key':k,'generation':gen,'createdAt':t,'side':str(e.get('side')),
               'entryPrice':float(e.get('price') or m.get('price') or 0.0),'qty':inc,'remaining':inc,'paidQty':0.0,
               'passivePaidQty':0.0,'activePaidQty':0.0,'pairEdge':0.0,'completedAt':None,'payments':[]}
            tranches.append(z);by_gen[gen].append(z);continue
        q=float(e.get('paid') or 0.0);gen=int(e.get('generation') or -1)
        if q<=EPS:continue
        lk=repair_lookup.get((t,str(e.get('key'))),{});px=float(lk.get('price') or 0.0);active=bool(e.get('active'));dq=by_gen[gen]
        while q>EPS and dq:
            z=dq[0]
            if z['remaining']<=EPS:dq.popleft();continue
            # Chronology invariant: this should always hold now.
            if t<z['createdAt']:raise RuntimeError(f'payment before tranche birth {r["marketId"]} {t} < {z["createdAt"]}')
            take=min(q,z['remaining']);q-=take;z['remaining']-=take;z['paidQty']+=take
            if active:z['activePaidQty']+=take
            else:z['passivePaidQty']+=take
            edge=take*(1.0-z['entryPrice']-px);z['pairEdge']+=edge
            z['payments'].append({'t':t,'key':str(e.get('key')),'price':px,'qty':take,'active':active,'edge':edge})
            if z['remaining']<=EPS:
                z['remaining']=0.0;z['completedAt']=t;dq.popleft()
        if q>EPS:orphan+=q
    completed=[z for z in tranches if z['completedAt'] is not None]
    nonneg=[z for z in completed if z['pairEdge']>=-EPS]
    passive=[z for z in nonneg if z['passivePaidQty']>=z['qty']-EPS and z['activePaidQty']<=EPS]
    neg=[z for z in completed if z['pairEdge']<-EPS]
    return {'marketId':int(r['marketId']),'pnl':float(r['pnlDiagnosticOnly']),'best':float(r['best']),'floor':float(r['floor']),'fills':int(r['fillEvents']),
            'riskFillTranches':len(tranches),'completedTranches':len(completed),'nonnegativeCompleted':len(nonneg),'negativeCompleted':len(neg),
            'passiveOnlyNonnegative':len(passive),'completedPairEdge':sum(z['pairEdge'] for z in completed),
            'nonnegativePairEdge':sum(z['pairEdge'] for z in nonneg),'negativePairEdge':sum(z['pairEdge'] for z in neg),
            'unrepaidQty':sum(z['remaining'] for z in tranches),'orphanPaymentQty':orphan,'tranches':tranches}

def main():
    ap=argparse.ArgumentParser();ap.add_argument('--r264',required=True);ap.add_argument('--output',required=True);a=ap.parse_args();d=json.load(open(a.r264,encoding='utf-8'));rows=[]
    for r in d['rows']:
        if r.get('cell')!='R264_EXECUTION_REPRESENTED_PRE_REPAIR_REEXPAND':continue
        x=analyze_row(r);rows.append(x);print(json.dumps({k:x[k] for k in ['marketId','pnl','best','floor','riskFillTranches','completedTranches','nonnegativeCompleted','negativeCompleted','passiveOnlyNonnegative','completedPairEdge','unrepaidQty','orphanPaymentQty']},ensure_ascii=False),flush=True)
    agg=Counter()
    for x in rows:
        for k in ['riskFillTranches','completedTranches','nonnegativeCompleted','negativeCompleted','passiveOnlyNonnegative']:agg[k]+=int(x[k])
    summary={'markets':len(rows),**dict(agg),'completedPairEdge':sum(x['completedPairEdge'] for x in rows),'negativePairEdge':sum(x['negativePairEdge'] for x in rows),
             'nonnegativePairEdge':sum(x['nonnegativePairEdge'] for x in rows),'marketsWithPassiveOnlyNonnegativeToken':sum(x['passiveOnlyNonnegative']>0 for x in rows),
             'unrepaidQty':sum(x['unrepaidQty'] for x in rows),'orphanPaymentQty':sum(x['orphanPaymentQty'] for x in rows)}
    out={'version':'MS4_R2_85_STRICT_CHRONOLOGY_CYCLE_CAPITAL_SHADOW_V1','researchOnly':True,'behaviorChange':False,'source':a.r264,'summary':summary,'rows':rows,
         'supersedesForCycleAttribution':['MS4_R2_73_R264_CYCLE_CAPITAL_REARM_SHADOW_V1','R2.83/R2.84 tranche-level conclusions that depended on its prebuilt future-tranche FIFO'],
         'boundary':['risk tranche can enter FIFO only at its actual confirmed fill time','future tranches cannot receive earlier Repair payments','same-clock risk birth precedes later R257 payment telemetry from the same process call','actual R257 payments and actual Repair prices only','no behavior change','winner not used for cycle attribution']}
    Path(a.output).parent.mkdir(parents=True,exist_ok=True);Path(a.output).write_text(json.dumps(out,indent=2),encoding='utf-8');print(json.dumps({'ok':True,'summary':summary},ensure_ascii=False))
if __name__=='__main__':main()
