from __future__ import annotations

import argparse
import json
import math
import os
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
BASE = ROOT / "data" / "research" / "execution_aware_fill_lifecycle_v0"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--input",
        default="hft_r2_cycle_option_program_dataset_v1_report.json",
    )
    parser.add_argument(
        "--dataset-id",
        default="btc5m/hft-r2-cycle-option-program-1573252-v0",
    )
    parser.add_argument(
        "--dataset-root",
        default=str(BASE / "minari"),
    )
    parser.add_argument(
        "--output",
        default="hft_r2_cycle_option_program_minari_v1_validation.json",
    )
    args = parser.parse_args()
    os.environ["MINARI_DATASETS_PATH"] = str(Path(args.dataset_root).resolve())

    import gymnasium as gym
    import minari
    import numpy as np
    from minari.data_collector.episode_buffer import EpisodeBuffer

    source_path = BASE / args.input
    source = json.loads(source_path.read_text(encoding="utf-8"))
    feature_count = len(source["observationFeatures"])
    action_count = len(source["actionSpace"])
    buffers: list[EpisodeBuffer] = []
    expected_returns: list[float] = []
    expected_steps: list[int] = []
    for index, episode in enumerate(source["episodes"]):
        observations = np.asarray(episode["observations"], dtype=np.float32)
        actions = np.asarray(episode["actions"], dtype=np.int64)
        rewards = np.asarray(episode["rewards"], dtype=np.float32)
        terminations = np.asarray(episode["terminations"], dtype=np.bool_)
        truncations = np.asarray(episode["truncations"], dtype=np.bool_)
        if observations.shape != (len(actions) + 1, feature_count):
            raise RuntimeError(
                f"episode {index} observation shape {observations.shape} is not {(len(actions) + 1, feature_count)}"
            )
        if rewards.shape != actions.shape or terminations.shape != actions.shape or truncations.shape != actions.shape:
            raise RuntimeError(f"episode {index} transition arrays are not aligned")
        if not np.isfinite(observations).all() or not np.isfinite(rewards).all():
            raise RuntimeError(f"episode {index} has non-finite values")
        if len(actions) == 0 or not bool(terminations[-1]) or bool(truncations[-1]):
            raise RuntimeError(f"episode {index} lacks a proper terminal transition")
        if int(actions.min()) < 0 or int(actions.max()) >= action_count:
            raise RuntimeError(f"episode {index} action outside declared space")
        buffers.append(
            EpisodeBuffer(
                id=index,
                observations=observations,
                actions=actions,
                rewards=rewards,
                terminations=terminations,
                truncations=truncations,
            )
        )
        expected_returns.append(float(rewards.sum()))
        expected_steps.append(len(actions))

    observation_space = gym.spaces.Box(
        low=-np.inf,
        high=np.inf,
        shape=(feature_count,),
        dtype=np.float32,
    )
    action_space = gym.spaces.Discrete(action_count)
    storage_file = Path(args.dataset_root).resolve() / Path(*args.dataset_id.split("/")) / "data" / "main_data.hdf5"
    if storage_file.exists():
        dataset = minari.load_dataset(args.dataset_id)
    else:
        dataset = minari.create_dataset_from_buffers(
            dataset_id=args.dataset_id,
            buffer=buffers,
            action_space=action_space,
            observation_space=observation_space,
            algorithm_name="HFTBACKTEST_PHASE_CONDITIONED_PROGRAM_GRID",
            author="BTC 5M Lab",
            description=(
                "Research-only Frozen-R2 option-transition episodes generated by HftBacktest + Predict Execution Tape V1. "
                "Actions are WAIT or passive offsets inside the current R2-authorized maintain/repair option."
            ),
            requirements=["gymnasium==1.0.0", "minari==0.5.3", "h5py==3.16.0", "Pillow==12.1.1"],
        )
    loaded = minari.load_dataset(args.dataset_id)
    loaded_episodes = list(loaded.iterate_episodes())
    actual_returns = [float(np.asarray(episode.rewards, dtype=float).sum()) for episode in loaded_episodes]
    actual_steps = [len(episode.actions) for episode in loaded_episodes]
    checks = {
        "datasetIdRoundTrip": getattr(loaded, "dataset_id", getattr(loaded, "_dataset_id", None)) == args.dataset_id,
        "episodeCount": len(loaded_episodes) == len(buffers),
        "stepCounts": actual_steps == expected_steps,
        "returns": len(actual_returns) == len(expected_returns)
        and all(math.isclose(a, b, abs_tol=1e-5) for a, b in zip(actual_returns, expected_returns, strict=True)),
        "observationSpace": tuple(loaded.observation_space.shape) == (feature_count,),
        "actionSpace": int(loaded.action_space.n) == action_count,
        "sourceWinnerNotObservation": "winner" not in source["observationFeatures"],
        "sourceTargetFutureNotObservation": all(
            "target_future" not in name.lower() for name in source["observationFeatures"]
        ),
    }
    decision = "KEEP_MINARI_DATA_CONTRACT" if all(checks.values()) else "BLOCKED_MINARI_DATA_CONTRACT"
    report: dict[str, Any] = {
        "version": "HFT_R2_CYCLE_OPTION_PROGRAM_MINARI_V1_VALIDATION",
        "researchOnly": True,
        "source": source_path.name,
        "datasetId": args.dataset_id,
        "datasetRoot": str(Path(args.dataset_root).resolve()),
        "minariVersion": minari.__version__,
        "gymnasiumVersion": gym.__version__,
        "episodes": len(loaded_episodes),
        "transitions": sum(actual_steps),
        "observationFeatures": feature_count,
        "actions": action_count,
        "returnMin": min(actual_returns),
        "returnMax": max(actual_returns),
        "checks": checks,
        "decision": decision,
        "d3rlpyInstalled": False,
        "next": (
            "Do not train on this one-market schema smoke. If the action-family ceiling is positive, preregister a small chronological multi-market dataset, "
            "then install d3rlpy in this isolated Python 3.12 research runtime and compare conservative offline baselines."
        ),
    }
    output = BASE / args.output
    output.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps({"ok": all(checks.values()), "output": str(output), **report}, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
