from pathlib import Path
p=Path('src/predict_bot/r3_dual_paper_shadow_v2.py')
s=p.read_text(encoding='utf-8')
s=s.replace("        create table if not exists r3_shadow_market_v2(strategy_version text,lane text,market_id integer,checkpoint_count integer,switch_count integer,safe_cross_observed integer,repair_intent_count integer,context_nontrivial_count integer,last_state text,updated_at_ms integer,primary key(strategy_version,lane,market_id));\n        '''); self.db.commit()", "        create table if not exists r3_shadow_market_v2(strategy_version text,lane text,market_id integer,checkpoint_count integer,switch_count integer,safe_cross_observed integer,repair_intent_count integer,context_nontrivial_count integer,last_state text,updated_at_ms integer,primary key(strategy_version,lane,market_id));\n        create table if not exists r3_hft_control_runs_v2(strategy_version text,market_id integer,status text,maker_fill_events integer,maker_filled_shares real,taker_fills integer,final_abs_net real,worst_case_floor real,maker_net real,veto_strong integer,weak_substitutions integer,contextual_events integer,summary_json text,completed_at_ms integer,primary key(strategy_version,market_id));\n        create table if not exists r3_meta_v2(key text primary key,value text);\n        '''); self.db.commit()\n        row=self.db.execute(\"select value from r3_meta_v2 where key='hft_control_activation_market'\").fetchone()\n        if row is None:\n            hc=conn(HFT_DB,True); mx=hc.execute(\"select max(market_id) from hft_forward_runs_v1 where strategy_key='R2' and status='COMPLETE'\").fetchone()[0] or 0; hc.close(); self.hft_control_activation_market=int(mx); self.db.execute(\"insert into r3_meta_v2(key,value) values('hft_control_activation_market',?)\",(str(self.hft_control_activation_market),)); self.db.commit()\n        else:self.hft_control_activation_market=int(row[0])")
old="        for mid in hm:self._write('HFT_PAPER',mid,self._hft_events(mid),self._hft_packet(mid))"
new="        for mid in hm:self._write('HFT_PAPER',mid,self._hft_events(mid),self._hft_packet(mid))\n        # Actual PAPER execution authority begins only for new COMPLETE HFT markets after activation.\n        future=[m for m in hm if m>self.hft_control_activation_market]\n        if future:\n            from tools import hftbacktest_r3_context_control_v0 as ctl\n            for mid in sorted(future):\n                for ver,soft in [(BASE,False),(SOFT,True)]:\n                    if self.db.execute('select 1 from r3_hft_control_runs_v2 where strategy_version=? and market_id=?',(ver,mid)).fetchone():continue\n                    try:\n                        rep=ctl.run_market(mid,soft); sr=rep['studentRollout']; port=sr['finalPortfolio']; rc=rep['r3Control']; summ={'marketId':mid,'strategyVersion':ver,'makerFillEvents':sr['makerFillEvents'],'makerFilledShares':sr['makerFilledShares'],'takerFills':sr['takerFills'],'finalAbsNet':port.get('combined_abs_net'),'worstCaseFloor':port.get('worst_case_floor'),'makerNet':port.get('maker_net'),'vetoStrong':rc['vetoStrong'],'weakSubstitutions':rc['weakSubstitutions'],'contextualEvents':rc['contextualEvents'],'execution':'HFTBACKTEST_R3_CONTEXT_CONTROL_V0','paperOnly':True}\n                        self.db.execute('insert or replace into r3_hft_control_runs_v2 values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)',(ver,mid,'COMPLETE',int(sr['makerFillEvents']),float(sr['makerFilledShares']),int(sr['takerFills']),float(port.get('combined_abs_net') or 0.),float(port.get('worst_case_floor') or 0.),float(port.get('maker_net') or 0.),int(rc['vetoStrong']),int(rc['weakSubstitutions']),int(rc['contextualEvents']),json.dumps(summ,separators=(',',':')),int(time.time()*1000)));self.db.commit()\n                    except Exception as e:\n                        self.db.execute('insert or replace into r3_hft_control_runs_v2(strategy_version,market_id,status,summary_json,completed_at_ms) values(?,?,?,?,?)',(ver,mid,'ERROR',json.dumps({'error':f'{type(e).__name__}: {e}'},separators=(',',':')),int(time.time()*1000)));self.db.commit()"
s=s.replace(old,new)
s=s.replace("return {'ok':self.last_error is None,'status':'ACTIVE' if self.last_error is None else 'DEGRADED','version':VERSION,'paperOnly':True,'liveOrdersAffected':False,'r21ActionAuthority':False,'r3LiveOrderAuthority':False,'fullContextPacket':True,'makerControlIntentEnabled':True,'makerControlExecution':'SHADOW_INTENT_ONLY','database':str(OUT_DB),'lastLoopMs':self.last_loop,'lastError':self.last_error,'lanes':lanes,'latest':latest}", "hft_runs=[dict(r) for r in self.db.execute('select strategy_version,count(*) runs,sum(case when status=\'COMPLETE\' then 1 else 0 end) complete,max(completed_at_ms) updated_at_ms from r3_hft_control_runs_v2 group by strategy_version')]; return {'ok':self.last_error is None,'status':'ACTIVE' if self.last_error is None else 'DEGRADED','version':VERSION,'paperOnly':True,'liveOrdersAffected':False,'r21ActionAuthority':False,'r3LiveOrderAuthority':False,'r3PaperOrderAuthority':True,'fullContextPacket':True,'makerControlIntentEnabled':True,'makerControlExecution':'HFT_ACTUAL_PAPER_CONTROL_ON_NEW_COMPLETE_MARKETS','hftControlActivationAfterMarket':self.hft_control_activation_market,'database':str(OUT_DB),'lastLoopMs':self.last_loop,'lastError':self.last_error,'lanes':lanes,'hftControlRuns':hft_runs,'latest':latest}")
p.write_text(s,encoding='utf-8')
print('patched',p)
