from pathlib import Path
p=Path('tools/hftbacktest_r2_queue_option_counterfactual_v1.py')
s=p.read_text(encoding='utf-8')
orig=s
s=s.replace('import argparse\nimport json\nimport math\nimport sys\n', 'import argparse\nimport json\nimport math\nimport sys\nimport hashlib\n')
s=s.replace('    active_maker: dict[str, int | None] = {"UP": None, "DOWN": None}\n    maker_meta: dict[int, dict[str, Any]] = {}\n', '    active_maker: dict[str, int | None] = {"UP": None, "DOWN": None}\n    maker_meta: dict[int, dict[str, Any]] = {}\n    responsibility_seq = {"UP": 0, "DOWN": 0}\n    responsibility_id: dict[str, str | None] = {"UP": None, "DOWN": None}\n    child_seq_by_responsibility: dict[str, int] = defaultdict(int)\n    fill_timeline_by_intent: dict[str, list[dict[str, Any]]] = defaultdict(list)\n')
s=s.replace('    candidate_original_child_num: int | None = None\n    candidate_original_child_cum: float = 0.0\n', '    candidate_original_child_num: int | None = None\n    candidate_original_child_cum: float = 0.0\n    candidate_responsibility_id: str | None = None\n    candidate_client_intent_id: str | None = None\n')
s=s.replace('                fill_log.append({"eventMs": fill_ms, "role": "MAKER", "side": side, "price": px, "shares": delta, "fee": 0.0, "orderNum": int(num)})\n', '                _rid = str(om.get("responsibilityId") or "")\n                _cid = str(om.get("clientIntentId") or "")\n                _fe = {"eventMs": fill_ms, "role": "MAKER", "side": side, "price": px, "shares": delta, "fee": 0.0, "orderNum": int(num), "responsibilityId": _rid, "clientIntentId": _cid, "cumExecQtyAfter": cum}\n                fill_log.append(_fe)\n                if _cid:\n                    fill_timeline_by_intent[_cid].append(dict(_fe))\n')
s=s.replace('        num = next_num; next_num += 1\n        rc = ex.submit_native(bt, num, side, px, qty)\n        maker_meta[num] = {"side": side, "price": px, "qty": qty, "prevCum": 0.0, "submittedAtMs": t, "submitRc": int(rc)}\n', '        num = next_num; next_num += 1\n        rid = responsibility_id.get(side)\n        if rid is None:\n            responsibility_seq[side] += 1\n            rid = f"r4prov:{mid}:{side}:resp:{responsibility_seq[side]}:{t}"\n            responsibility_id[side] = rid\n        child_seq_by_responsibility[rid] += 1\n        child_ordinal = child_seq_by_responsibility[rid]\n        raw_key = f"{rid}|child|{child_ordinal}|{t}|{px:.8f}|{qty:.8f}"\n        cid = "r4ci:" + hashlib.sha256(raw_key.encode("utf-8")).hexdigest()[:24]\n        rc = ex.submit_native(bt, num, side, px, qty)\n        maker_meta[num] = {"side": side, "price": px, "qty": qty, "prevCum": 0.0, "submittedAtMs": t, "submitRc": int(rc), "responsibilityId": rid, "clientIntentId": cid, "childOrdinal": child_ordinal}\n')
s=s.replace('            for x in by_maker.get(t, []):\n                desired_maker[x["side"]] += float(x["shares"])\n                latest_reason[x[\'side\']]=str(x.get(\'reason\') or \'UNKNOWN\')\n', '            for x in by_maker.get(t, []):\n                _side = x["side"]\n                _actual_side = actual.maker_up if _side == "UP" else actual.maker_down\n                _pre_deficit = float(desired_maker[_side]) - float(_actual_side)\n                if _pre_deficit <= EPS:\n                    responsibility_seq[_side] += 1\n                    responsibility_id[_side] = f"r4prov:{mid}:{_side}:resp:{responsibility_seq[_side]}:{t}"\n                desired_maker[_side] += float(x["shares"])\n                latest_reason[_side]=str(x.get(\'reason\') or \'UNKNOWN\')\n')
s=s.replace('                        candidate_original_child_num = int(child0)\n                        _cs0 = ex.order_snapshot(bt, int(candidate_original_child_num))\n', '                        candidate_original_child_num = int(child0)\n                        candidate_responsibility_id = str(maker_meta[int(child0)].get("responsibilityId") or "") or None\n                        candidate_client_intent_id = str(maker_meta[int(child0)].get("clientIntentId") or "") or None\n                        _cs0 = ex.order_snapshot(bt, int(candidate_original_child_num))\n')
s=s.replace('        candidate_child_labels = None\n        if candidate_at_ms is not None and candidate_original_child_num is not None:\n', '        candidate_child_labels = None\n        candidate_identity_frontier = None\n        if candidate_at_ms is not None and candidate_original_child_num is not None:\n')
s=s.replace('            candidate_child_labels = {\n                "orderNum": int(candidate_original_child_num),\n', '            candidate_child_labels = {\n                "orderNum": int(candidate_original_child_num),\n')
needle='''                "fillShares5s": float(sum(float(ev1.get("shares") or 0.0) for ev1 in future_child if int(ev1["eventMs"]) <= int(candidate_at_ms)+5000)),\n            }\n\n        if queue_reinsert_event is not None'''
repl='''                "fillShares5s": float(sum(float(ev1.get("shares") or 0.0) for ev1 in future_child if int(ev1["eventMs"]) <= int(candidate_at_ms)+5000)),\n            }\n            if candidate_client_intent_id:\n                _events = [ev for ev in fill_timeline_by_intent.get(candidate_client_intent_id, []) if int(ev.get("eventMs") or 0) > int(candidate_at_ms)]\n                _rem = float((candidate_queue_features or {}).get("remainingQty") or 0.0)\n                candidate_identity_frontier = {\n                    "responsibilityId": candidate_responsibility_id,\n                    "clientIntentId": candidate_client_intent_id,\n                    "remainingQtyAtCheckpoint": _rem,\n                    "fillShares1s": float(sum(float(ev.get("shares") or 0.0) for ev in _events if int(ev["eventMs"]) <= int(candidate_at_ms)+1000)),\n                    "fillShares3s": float(sum(float(ev.get("shares") or 0.0) for ev in _events if int(ev["eventMs"]) <= int(candidate_at_ms)+3000)),\n                    "fillShares5s": float(sum(float(ev.get("shares") or 0.0) for ev in _events if int(ev["eventMs"]) <= int(candidate_at_ms)+5000)),\n                    "eventCount": len(_events),\n                }\n\n        if queue_reinsert_event is not None'''
if needle not in s: raise SystemExit('frontier insertion needle missing')
s=s.replace(needle,repl)
needle2='''            "candidateOriginalChildNum": candidate_original_child_num,\n            "candidateChildKeepLabels": candidate_child_labels,\n'''
repl2='''            "candidateOriginalChildNum": candidate_original_child_num,\n            "candidateChildKeepLabels": candidate_child_labels,\n            "creationTimeProvenance": {\n                "candidateResponsibilityId": candidate_responsibility_id,\n                "candidateClientIntentId": candidate_client_intent_id,\n                "candidateIdentityFrontier": candidate_identity_frontier,\n                "makerOrders": [dict(orderNum=int(n), **m) for n,m in sorted(maker_meta.items())],\n                "makerFillTimeline": [dict(ev) for ev in fill_log if str(ev.get("role")) == "MAKER"],\n            },\n'''
if needle2 not in s: raise SystemExit('return insertion needle missing')
s=s.replace(needle2,repl2)
if s==orig: raise SystemExit('no changes')
p.write_text(s,encoding='utf-8')
print({'patched':True,'bytes':len(s)})
