from __future__ import annotations
import json, random
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'data/research/execution_aware_fill_lifecycle_v0'; CONTRACT=OUT/'r21_echtgeld_live_state_bridge_contract_v1.json'; CURRIC=OUT/'r21_echtgeld_environment_curriculum_v1_dataset.json'; REPORT=OUT/'r21_echtgeld_live_bridge_exam_v1_report.json'
TERMINAL={'FILLED','CANCELED','REJECTED','EXPIRED','FAILED'}; LIVE={'PLANNED','QUOTING','QUOTE_READY','PLACING','RESTING','PARTIAL_FILL','CANCEL_PENDING','CANCEL_UNKNOWN','UNKNOWN_SUBMISSION'}
def bridge(x):
 req=float(x.get('requestedShares',0)); fill=max(0,min(req,float(x.get('confirmedShares',0)))); state=str(x.get('orderState','')).upper(); target=float(x.get('targetShares',req)); actual=float(x.get('actualShares',fill)); unknown=state=='UNKNOWN_SUBMISSION' or bool(x.get('unknownWrite',False)); terminal=state in TERMINAL; owner='UNKNOWN_CHILD' if unknown else ('CURRENT_CHILD' if state in LIVE else 'RELEASED'); gap=max(0,target-actual); child=max(0,req-fill); avail=max(0,gap-child) if owner!='RELEASED' else gap
 return {'actualConfirmedInventory':actual,'ownershipState':owner,'terminalCertainty':terminal,'effectiveTargetRevision':target,'remainingObligation':gap,'availableUnownedObligation':avail,'childRemainingShares':child,'situationCode':'UNKNOWN_QUARANTINE' if unknown else ('LIVE_PARTIAL' if state=='PARTIAL_FILL' else ('CANCEL_PENDING' if state=='CANCEL_PENDING' else ('TERMINAL_REMAINDER' if terminal and child>1e-9 else ('TERMINAL_COMPLETE' if terminal else 'LIVE_NO_FILL'))))}
def main():
 c=json.loads(CONTRACT.read_text(encoding='utf-8')); data=json.loads(CURRIC.read_text(encoding='utf-8')); rows=data.get('rows',data.get('examples',data if isinstance(data,list) else [])); checks=[]
 def ck(n,o,d=None): checks.append({'name':n,'passed':bool(o),'detail':d})
 ck('contract_r21_no_action_authority',c.get('r21ActionAuthority') is False); ck('contract_no_executor_callback',c.get('executorCallbackAllowed') is False); ck('contract_runtime_quantity_not_fixed18','never assume 18' in c.get('quantityRule','')); ck('contract_minimum_notional_1',float(c.get('minimumNotionalUsdt',-1))==1.0); ck('curriculum_minimum_notional_1',float(data.get('minimumNotionalUsdt',-1))==1.0); ck('curriculum_present',len(rows)>=300,{'rows':len(rows)})
 fixed=[({'requestedShares':10,'confirmedShares':4,'orderState':'PARTIAL_FILL','targetShares':10,'actualShares':4},('CURRENT_CHILD',False,6,0)),({'requestedShares':10,'confirmedShares':4,'orderState':'CANCELED','targetShares':10,'actualShares':4},('RELEASED',True,6,6)),({'requestedShares':10,'confirmedShares':0,'orderState':'UNKNOWN_SUBMISSION','targetShares':10,'actualShares':0},('UNKNOWN_CHILD',False,10,0)),({'requestedShares':10,'confirmedShares':10,'orderState':'FILLED','targetShares':10,'actualShares':10},('RELEASED',True,0,0)),({'requestedShares':8,'confirmedShares':3,'orderState':'CANCEL_PENDING','targetShares':8,'actualShares':3},('CURRENT_CHILD',False,5,0))]
 for i,(x,e) in enumerate(fixed):
  y=bridge(x); ck(f'fixed_{i}_ownership',y['ownershipState']==e[0],y); ck(f'fixed_{i}_terminal',y['terminalCertainty']==e[1],y); ck(f'fixed_{i}_remaining',abs(y['remainingObligation']-e[2])<1e-9,y); ck(f'fixed_{i}_no_duplicate_owner',abs(y['availableUnownedObligation']-e[3])<1e-9,y)
 random.seed(21); good=0
 for _ in range(5000):
  req=random.choice([8.,10.]); fill=random.uniform(0,req); state=random.choice(sorted(TERMINAL|LIVE)); target=random.uniform(0,14); y=bridge({'requestedShares':req,'confirmedShares':fill,'orderState':state,'targetShares':target,'actualShares':fill}); good += int(y['remainingObligation']>=0 and y['childRemainingShares']>=0 and 0<=y['availableUnownedObligation']<=y['remainingObligation']+1e-9 and (y['terminalCertainty']==(state in TERMINAL)))
 ck('fuzz_5000_invariants',good==5000,{'passed':good,'total':5000}); ck('10share_boundary_0_10',(10*.099)<1 and (10*.1)>=1); ck('8share_boundary_0_125',(8*.124)<1 and (8*.125)>=1)
 failed=[x for x in checks if not x['passed']]; rep={'version':'R21_ECHTGELD_LIVE_BRIDGE_EXAM_V1','researchOnly':True,'venueWrites':0,'echtgeldArmingAffected':False,'minimumNotionalUsdt':1.0,'checksPassed':len(checks)-len(failed),'checksFailed':len(failed),'status':'PASS' if not failed else 'FAIL','checks':checks,'guards':['R2.1 state-only','No executor callback','No live order writes','No Echtgeld arming','No silent quantity upsize']}; REPORT.write_text(json.dumps(rep,ensure_ascii=False,indent=2),encoding='utf-8'); print(json.dumps({'status':rep['status'],'passed':rep['checksPassed'],'failed':rep['checksFailed'],'curriculumRows':len(rows),'report':str(REPORT.relative_to(ROOT))},ensure_ascii=False,indent=2))
if __name__=='__main__': main()
