from __future__ import annotations
import json,joblib
from pathlib import Path
import numpy as np,pandas as pd
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.metrics import roc_auc_score,average_precision_score,log_loss
ROOT=Path(__file__).resolve().parents[1]
SRC=ROOT/'data/research/r4_v0/hourly/r4_management_responsibility_router_v0_rows.csv'
OUT=ROOT/'data/research/r4_v0/hourly/r4_management_continue_weak_v1.json'
MODEL=ROOT/'data/research/r4_v0/hourly/r4_management_continue_weak_v1.joblib'
PORT=['seconds_left','pre_abs_payoff_gap','pre_risk_deficit','placement_readiness_native_5s']
RESP=['weak_active_owners','dominant_active_owners','weak_oldest_age_s','dominant_oldest_age_s']
MEM=['current_mode_age_s','events_5s','events_15s','transitions_15s']
ROUTED=PORT+RESP+MEM
FORM=['seconds_left','pre_abs_payoff_gap','pre_risk_deficit','predict_up_mid','predict_edge','predict_supports_dominant','strike_toward_dominant_bps','spot_supports_dominant','placement_readiness_native_5s']
def hgb(seed):return HistGradientBoostingClassifier(learning_rate=.05,max_leaf_nodes=15,max_depth=4,min_samples_leaf=20,l2_regularization=1,max_iter=220,random_state=seed)
def met(y,p):
 y=np.asarray(y,int);p=np.asarray(p,float);return {'n':int(len(y)),'rate':float(y.mean()),'auc':float(roc_auc_score(y,p)) if len(np.unique(y))>1 else None,'ap':float(average_precision_score(y,p)) if y.sum()>0 else None,'logLoss':float(log_loss(y,np.clip(p,1e-6,1-1e-6),labels=[0,1]))}
def main():
 a=pd.read_csv(SRC).replace([np.inf,-np.inf],np.nan).dropna(subset=list(dict.fromkeys(FORM+ROUTED+['market_id','t','build_now','continue_weak_5s']))).copy();a.market_id=a.market_id.astype(int)
 d=a[(a.seconds_left>=60)&(a.seconds_left<=300)&(a.build_now==1)].sort_values(['market_id','t']).copy();ms=d.groupby('market_id').t.min().sort_values().index.astype(int).tolist();trm=ms[:-7];tem=ms[-7:]
 # Formation head gets all states on train markets; manager gets only current BUILD states.
 fa=a[a.market_id.isin(trm)].copy();tr=d[d.market_id.isin(trm)].copy();te=d[d.market_id.isin(tem)].copy();fm=hgb(51001).fit(fa[FORM],fa.build_now.astype(int));tr['formation_build_confidence']=fm.predict_proba(tr[FORM])[:,1];te['formation_build_confidence']=fm.predict_proba(te[FORM])[:,1]
 old=hgb(51002).fit(tr[ROUTED],tr.continue_weak_5s.astype(int));new=hgb(51003).fit(tr[ROUTED+['formation_build_confidence']],tr.continue_weak_5s.astype(int));po=old.predict_proba(te[ROUTED])[:,1];pn=new.predict_proba(te[ROUTED+['formation_build_confidence']])[:,1]
 report={'version':'R4_MANAGEMENT_CONTINUE_WEAK_V1','researchOnly':True,'actionAuthority':False,'curriculum':'M0_RESPONSIBILITY_CONTINUATION','architecture':'Formation head emits semantic current BUILD confidence; Manager consumes that belief plus portfolio/readiness/responsibility/lifecycle state. Raw Predict/strike is not exposed to Manager.','coverage':{'markets':len(ms),'rows':int(len(d)),'trainMarkets':len(trm),'holdoutMarkets':tem,'phase':'60-300s'},'features':{'formationHead':FORM,'manager':ROUTED+['formation_build_confidence']},'holdout':{'V0_ROUTED':met(te.continue_weak_5s,po),'V1_WITH_FORMATION_BELIEF':met(te.continue_weak_5s,pn)},'guards':['No raw Predict/strike at Manager interface.','Formation confidence is generated by a separate head trained only on earlier train markets.','Future continuation is label only.','No action/price/size/channel authority, no threshold sweep, no winner/settlement.']}
 report['holdout']['delta']={'auc':report['holdout']['V1_WITH_FORMATION_BELIEF']['auc']-report['holdout']['V0_ROUTED']['auc'],'ap':report['holdout']['V1_WITH_FORMATION_BELIEF']['ap']-report['holdout']['V0_ROUTED']['ap'],'logLossImprovement':report['holdout']['V0_ROUTED']['logLoss']-report['holdout']['V1_WITH_FORMATION_BELIEF']['logLoss']}
 joblib.dump({'version':'R4_MANAGEMENT_CONTINUE_WEAK_V1','formation_model':fm,'manager_model':new,'formation_features':FORM,'manager_features':ROUTED+['formation_build_confidence'],'phase':[60,300],'actionAuthority':False},MODEL);report['modelPath']=str(MODEL.relative_to(ROOT)).replace('\\','/');OUT.write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf-8');print(json.dumps(report,ensure_ascii=False,indent=2))
if __name__=='__main__':main()
