"""Predict.fun BNB Testnet research bot."""

from .calibrated_value_confirmation_filters import (
    install_calibrated_value_confirmation_filters as _install_calibrated_value_confirmation_filters,
)
from .calibrated_value_confirmation_variants import (
    install_calibrated_value_confirmation_variants as _install_calibrated_value_confirmation_variants,
)
from .confirmation_add_sources_patch import (
    install_confirmation_add_sources_patch as _install_confirmation_add_sources_patch,
)
from .decision_snapshot_diagnostics import (
    install_decision_snapshot_diagnostics as _install_decision_snapshot_diagnostics,
)
from .decision_snapshot_state import (
    install_decision_snapshot_state as _install_decision_snapshot_state,
)
from .direct_outcome_guard import (
    install_direct_outcome_guard as _install_direct_outcome_guard,
)
from .microprice_confirm_exit_098_entry_guard_patch import (
    install_microprice_confirm_exit_098_entry_guard_patch as _install_microprice_confirm_exit_098_entry_guard_patch,
)
from .microprice_confirm_exit_098_horizon_patch import (
    install_microprice_confirm_exit_098_horizon_patch as _install_microprice_confirm_exit_098_horizon_patch,
)
from .microprice_confirm_exit_098_live_patch import (
    install_microprice_confirm_exit_098_live_patch as _install_microprice_confirm_exit_098_live_patch,
)
from .microprice_confirm_exit_098_live_v2_patch import (
    install_microprice_confirm_exit_098_live_v2_patch as _install_microprice_confirm_exit_098_live_v2_patch,
)
from .microprice_confirm_live_patch import (
    install_microprice_confirm_live_patch as _install_microprice_confirm_live_patch,
)
from .microprice_confirm_optimization_shadows import (
    install_microprice_confirm_optimization_shadows as _install_microprice_confirm_optimization_shadows,
)
from .microprice_feature_shadows import (
    install_microprice_feature_shadows as _install_microprice_feature_shadows,
)
from .microprice_variant_relaxation import (
    install_microprice_variant_relaxation as _install_microprice_variant_relaxation,
)
from .microprice_variants import (
    install_microprice_variants as _install_microprice_variants,
)
from .microprice_dashboard_patch import (
    install_microprice_dashboard_patch as _install_microprice_dashboard_patch,
)
from .pair_arb_initial_capacity_patch import (
    install_pair_arb_initial_capacity_patch as _install_pair_arb_initial_capacity_patch,
)

_install_decision_snapshot_diagnostics()
_install_decision_snapshot_state()
_install_direct_outcome_guard()
_install_microprice_variant_relaxation()
_install_microprice_variants()
_install_microprice_dashboard_patch()
_install_microprice_feature_shadows()
_install_microprice_confirm_optimization_shadows()
_install_calibrated_value_confirmation_variants()
_install_calibrated_value_confirmation_filters()
_install_microprice_confirm_live_patch()
_install_microprice_confirm_exit_098_live_patch()
_install_microprice_confirm_exit_098_live_v2_patch()
_install_microprice_confirm_exit_098_entry_guard_patch()
_install_microprice_confirm_exit_098_horizon_patch()
_install_confirmation_add_sources_patch()
_install_pair_arb_initial_capacity_patch()
del _install_calibrated_value_confirmation_filters
del _install_calibrated_value_confirmation_variants
del _install_confirmation_add_sources_patch
del _install_decision_snapshot_diagnostics
del _install_decision_snapshot_state
del _install_direct_outcome_guard
del _install_microprice_confirm_exit_098_entry_guard_patch
del _install_microprice_confirm_exit_098_horizon_patch
del _install_microprice_confirm_exit_098_live_patch
del _install_microprice_confirm_exit_098_live_v2_patch
del _install_microprice_confirm_live_patch
del _install_microprice_confirm_optimization_shadows
del _install_microprice_feature_shadows
del _install_microprice_variant_relaxation
del _install_microprice_variants
del _install_microprice_dashboard_patch
del _install_pair_arb_initial_capacity_patch
