from __future__ import annotations

from decimal import Decimal
from typing import Iterable


MICROPRICE_CONFIRM_LIVE_STRATEGY = "R_MICROPRICE_CONFIRM"
MICROPRICE_CONFIRM_LIVE_PATCH_VERSION = "MICROPRICE_CONFIRM_LIVE_V1"


def _append_unique(values: Iterable[str], item: str) -> tuple[str, ...]:
    return tuple(dict.fromkeys((*tuple(values), item)))


def install_microprice_confirm_live_patch() -> None:
    """Register the confirmed Microprice variant for guarded live execution.

    The signal remains generated by the existing paper/research tracker.  This
    patch only allows that immutable candidate to cross the live queue when the
    operator explicitly selects R_MICROPRICE_CONFIRM.  The live executor still
    owns strategy selection, stake limits, quote refresh/reprice checks,
    drawdown/cooldown controls, and confirmation-add execution safety.
    """

    from . import live_trading as live
    from . import m_realtime as realtime
    from . import research_forward as research

    strategy = MICROPRICE_CONFIRM_LIVE_STRATEGY

    live.LIVE_RESEARCH_STRATEGIES = _append_unique(
        live.LIVE_RESEARCH_STRATEGIES,
        strategy,
    )
    live.LIVE_SUPPORTED_STRATEGIES = _append_unique(
        live.LIVE_SUPPORTED_STRATEGIES,
        strategy,
    )
    live.LIVE_RESEARCH_REPRICE_GAPS = {
        **live.LIVE_RESEARCH_REPRICE_GAPS,
        strategy: Decimal("0.05"),
    }

    # m_realtime imports the live tuple by value and precomputes this set at
    # module import time, so both names must be refreshed explicitly.
    realtime.LIVE_RESEARCH_STRATEGIES = _append_unique(
        realtime.LIVE_RESEARCH_STRATEGIES,
        strategy,
    )
    realtime.LIVE_FORWARDABLE_PAPER_STRATEGIES = {
        *realtime.LIVE_FORWARDABLE_PAPER_STRATEGIES,
        strategy,
    }

    # Keep this correct even when the installer order changes.  The dedicated
    # all-live confirmation-add patch will reapply the same source list later.
    all_live_sources = tuple(live.LIVE_SUPPORTED_STRATEGIES)
    research.CONFIRMATION_ADD_SOURCE_STRATEGIES = all_live_sources
    live.CONFIRMATION_ADD_SOURCE_STRATEGIES = all_live_sources
