from __future__ import annotations

import json
from typing import Any

from .poly_quote_canary import _finite, _ms
from .poly_quote_canary_exit_sim import ExitSimulatedPolyQuoteCanary, _units_from_wei
from .poly_quote_canary_live_sizing import _shares_from_wei


class DurableExitSimulatedPolyQuoteCanary(ExitSimulatedPolyQuoteCanary):
    """V3 exit scenarios that always persist a meaningful best/worst envelope.

    The Paper engine already records the held-side Binance Bid at the exact exit
    signal as trade.exit_price. That value arrives here as event['paper_price'].
    If realtime first-level Bid size is available for the same market, BEST uses
    only that visible size. If size is unavailable, BEST becomes an explicitly
    labelled optimistic upper bound: all simulated entry shares at the recorded
    exit-signal Bid. WORST remains zero shares sold and full hold to official
    settlement.

    This class also converts legacy EXIT canary rows (including SELL -9000
    rejects) into the new scenario model on startup whenever the source Paper
    trade can be reconstructed. ENTRY signed-quote rows are never rewritten.
    """

    def _create_schema(self) -> None:
        super()._create_schema()
        with self.db_lock:
            columns = {
                str(row[1])
                for row in self.db.execute(
                    "PRAGMA table_info(poly_quote_canary_attempts)"
                ).fetchall()
            }
            additions = {
                "sim_best_depth_mode": "TEXT",
                "sim_source_exit_price": "REAL",
                "sim_legacy_exit_migrated": "INTEGER NOT NULL DEFAULT 0",
            }
            for name, ddl in additions.items():
                if name not in columns:
                    self.db.execute(
                        f"ALTER TABLE poly_quote_canary_attempts ADD COLUMN {name} {ddl}"
                    )
            self.db.commit()

    def start(self) -> None:
        # Convert rows generated by the previous SELL signed-quote implementation
        # before serving the first dashboard snapshot.
        self._migrate_legacy_exit_rows()
        super().start()

    def _update_v3_fields(self, trade_id: int, **values: Any) -> None:
        allowed = {
            "sim_best_depth_mode",
            "sim_source_exit_price",
            "sim_legacy_exit_migrated",
        }
        updates = {key: value for key, value in values.items() if key in allowed}
        if not updates:
            return
        updates["updated_at_ms"] = _ms()
        assignments = ", ".join(f"{key}=?" for key in updates)
        with self.db_lock:
            self.db.execute(
                f"UPDATE poly_quote_canary_attempts SET {assignments} "
                "WHERE trade_id=? AND phase='EXIT'",
                (*updates.values(), int(trade_id)),
            )
            self.db.commit()

    def _source_trade(self, trade_id: int) -> dict[str, Any] | None:
        with self.db_lock:
            row = self.db.execute(
                "SELECT * FROM cross_oracle_strategy_trades WHERE id=? LIMIT 1",
                (int(trade_id),),
            ).fetchone()
        return dict(row) if row is not None else None

    def _migrate_legacy_exit_rows(self) -> None:
        with self.db_lock:
            rows = [
                dict(row)
                for row in self.db.execute(
                    """SELECT * FROM poly_quote_canary_attempts
                        WHERE phase='EXIT'
                          AND (execution_mode IS NULL OR execution_mode='')
                        ORDER BY id ASC"""
                ).fetchall()
            ]
        for row in rows:
            source = self._source_trade(int(row["trade_id"]))
            if not source:
                continue
            exit_price = _finite(source.get("exit_price"))
            closed_at_ms = source.get("closed_at_ms")
            if exit_price is None or not (0 < exit_price <= 1) or closed_at_ms is None:
                continue
            event = {
                "trade_id": int(row["trade_id"]),
                "strategy": str(row["strategy"]),
                "phase": "EXIT",
                "market_id": int(row["binance_market_id"]),
                "side": str(row["side"]),
                "signal_at_ms": int(closed_at_ms),
                "queued_at_ms": int(closed_at_ms),
                "paper_price": float(exit_price),
                "stake_usdt": float(source.get("stake_usdt") or row.get("paper_stake_usdt") or 0.0),
                "shares": float(source.get("shares") or row.get("paper_shares") or 0.0),
                "poly_up_mid": _finite(source.get("entry_poly_up_mid")),
                "signal_binance_up_mid": _finite(source.get("entry_binance_up_mid")),
                "poly_selected_mid": None,
            }
            try:
                metadata = json.loads(str(source.get("metadata_json") or "{}"))
                if isinstance(metadata, dict):
                    event["poly_selected_mid"] = _finite(metadata.get("polySelectedMid"))
            except json.JSONDecodeError:
                pass
            self._process_exit_simulation(event, migrated=True)

    def _process_event(self, event: dict[str, Any]) -> None:
        if str(event.get("phase") or "") != "EXIT":
            return super()._process_event(event)
        self._process_exit_simulation(dict(event), migrated=False)

    def _process_exit_simulation(self, event: dict[str, Any], migrated: bool = False) -> None:
        trade_id = int(event["trade_id"])
        signal_at_ms = int(event["signal_at_ms"])
        entry = self._entry_execution_row(trade_id)
        if entry is None:
            self._update_attempt(
                trade_id,
                "EXIT",
                status="EXIT_SIM_NOT_APPLICABLE_NO_ENTRY_CANARY",
                reason="no ENTRY signed quote canary exists for this Paper trade",
                would_submit=0,
            )
            self._update_sim_fields(
                trade_id,
                execution_mode="SIMULATED_EXIT_NO_SELL_QUOTE",
                sim_settlement_status="NOT_APPLICABLE",
            )
            self._update_v3_fields(
                trade_id,
                sim_best_depth_mode="NOT_APPLICABLE",
                sim_source_exit_price=_finite(event.get("paper_price")),
                sim_legacy_exit_migrated=1 if migrated else 0,
            )
            return
        if int(entry.get("would_submit") or 0) != 1:
            self._update_attempt(
                trade_id,
                "EXIT",
                status="EXIT_SIM_NOT_APPLICABLE_ENTRY_FAILED",
                reason=(
                    "ENTRY signed quote did not pass simulated placement; "
                    "a real position would not exist to exit"
                ),
                would_submit=0,
            )
            self._update_sim_fields(
                trade_id,
                execution_mode="SIMULATED_EXIT_NO_SELL_QUOTE",
                sim_settlement_status="NOT_APPLICABLE",
            )
            self._update_v3_fields(
                trade_id,
                sim_best_depth_mode="NOT_APPLICABLE",
                sim_source_exit_price=_finite(event.get("paper_price")),
                sim_legacy_exit_migrated=1 if migrated else 0,
            )
            return

        entry_cost = _units_from_wei(entry.get("quote_amount_in_wei"))
        if entry_cost is None:
            entry_cost = _finite(entry.get("simulated_entry_stake_usdt"))
        if entry_cost is None:
            entry_cost = _finite(entry.get("paper_stake_usdt"))
        entry_shares = _shares_from_wei(entry.get("quote_amount_out_wei"))
        if entry_shares is None:
            entry_price = _finite(entry.get("quote_average_price"))
            if entry_cost is not None and entry_price is not None and entry_price > 0:
                entry_shares = entry_cost / entry_price
        if entry_cost is None or entry_cost <= 0 or entry_shares is None or entry_shares <= 0:
            self._update_attempt(
                trade_id,
                "EXIT",
                status="EXIT_SIM_NOT_APPLICABLE_ENTRY_SIZE_UNKNOWN",
                reason="ENTRY signed quote cost/shares are unavailable",
                would_submit=0,
            )
            self._update_sim_fields(
                trade_id,
                execution_mode="SIMULATED_EXIT_NO_SELL_QUOTE",
                sim_settlement_status="NOT_APPLICABLE",
            )
            self._update_v3_fields(
                trade_id,
                sim_best_depth_mode="NOT_APPLICABLE",
                sim_source_exit_price=_finite(event.get("paper_price")),
                sim_legacy_exit_migrated=1 if migrated else 0,
            )
            return

        observed_at_ms = _ms()
        market_id = int(event["market_id"])
        side = str(event["side"]).upper()

        # The strategy's recorded exit_price is the exact held-side Bid observed
        # at the exit signal. Prefer it over a later dashboard/realtime sample.
        signal_bid = _finite(event.get("paper_price"))
        latest = self._current_binance_state()
        latest_market_id = 0
        try:
            latest_market_id = int((latest or {}).get("market_id") or 0)
        except (TypeError, ValueError):
            latest_market_id = 0
        realtime_bid = _finite((latest or {}).get(f"{side.lower()}_bid"))
        realtime_bid_size = _finite((latest or {}).get(f"{side.lower()}_bid_size"))
        if latest_market_id != market_id:
            realtime_bid = None
            realtime_bid_size = None

        bid = signal_bid if signal_bid is not None and 0 < signal_bid <= 1 else realtime_bid
        if bid is None or not (0 < bid <= 1):
            best_evaluable = False
            depth_mode = "NO_RELIABLE_BID"
            fill_shares = None
            fill_ratio = None
            proceeds = None
            exit_fee = None
            net_exit = None
            unfilled = None
            bid_size = None
            reason = (
                "no reliable held-side exit Bid was recorded; best-case unavailable. "
                "worst execution scenario still holds 100% to official settlement"
            )
        else:
            best_evaluable = True
            if realtime_bid_size is not None and realtime_bid_size >= 0:
                bid_size = float(realtime_bid_size)
                fill_shares = min(entry_shares, bid_size)
                depth_mode = "FIRST_LEVEL_DEPTH"
                reason = (
                    "best case uses exit-signal Bid and no more shares than the current "
                    "visible first-level Bid size; remainder is held to settlement"
                )
            else:
                # This is an upper envelope, not an execution claim. It guarantees
                # a useful BEST endpoint when realtime does not expose level size.
                bid_size = None
                fill_shares = entry_shares
                depth_mode = "UPPER_BOUND_NO_DEPTH"
                reason = (
                    "first-level Bid size unavailable; BEST is an explicitly optimistic "
                    "upper bound assuming all signed-entry shares could sell at the "
                    "recorded exit-signal Bid. WORST still assumes zero shares sell"
                )
            fill_ratio = fill_shares / entry_shares
            proceeds = fill_shares * float(bid)
            fee_bps = int(entry.get("fee_rate_bps") or 200)
            exit_fee = proceeds * fee_bps / 10_000.0
            net_exit = proceeds - exit_fee
            unfilled = max(0.0, entry_shares - fill_shares)

        self._update_attempt(
            trade_id,
            "EXIT",
            quote_completed_at_ms=observed_at_ms,
            signal_to_quote_response_ms=max(0.0, observed_at_ms - signal_at_ms),
            adverse_price_move=(
                float(event["paper_price"]) - float(bid)
                if bid is not None and _finite(event.get("paper_price")) is not None else None
            ),
            signal_still_valid=1,
            would_submit=0,
            status="EXIT_SIM_WAITING_SETTLEMENT",
            reason=reason,
            quote_id_present=0,
        )
        self._update_sim_fields(
            trade_id,
            execution_mode="SIMULATED_EXIT_NO_SELL_QUOTE",
            sim_exit_observed_at_ms=observed_at_ms,
            sim_exit_observation_lag_ms=max(0.0, observed_at_ms - signal_at_ms),
            sim_entry_cost_usdt=entry_cost,
            sim_entry_shares=entry_shares,
            sim_exit_bid=bid,
            sim_exit_bid_size=bid_size,
            sim_best_case_evaluable=1 if best_evaluable else 0,
            sim_best_fill_shares=fill_shares,
            sim_best_fill_ratio=fill_ratio,
            sim_best_unfilled_shares=unfilled,
            sim_best_exit_proceeds_usdt=proceeds,
            sim_best_exit_fee_usdt=exit_fee,
            sim_best_exit_net_usdt=net_exit,
            sim_settlement_status="WAITING_OFFICIAL",
        )
        self._update_v3_fields(
            trade_id,
            sim_best_depth_mode=depth_mode,
            sim_source_exit_price=signal_bid,
            sim_legacy_exit_migrated=1 if migrated else 0,
        )
        self._finalize_exit_settlements([market_id])

    def snapshot(self) -> dict[str, Any]:
        payload = super().snapshot()
        # Re-read EXIT rows so V3-only columns added after the parent class are
        # included in the dashboard payload.
        with self.db_lock:
            exits = [
                dict(row)
                for row in self.db.execute(
                    """SELECT * FROM poly_quote_canary_attempts
                        WHERE phase='EXIT'
                          AND execution_mode='SIMULATED_EXIT_NO_SELL_QUOTE'
                        ORDER BY id DESC LIMIT 40"""
                ).fetchall()
            ]
        for row in exits:
            row.pop("token_id", None)
            row.pop("requested_amount_wei", None)
            row.pop("quote_amount_in_wei", None)
            row.pop("quote_amount_out_wei", None)
        payload["version"] = "POLY_ENTRY_REAL_QUOTE_EXIT_SCENARIOS_V3"
        payload["recentExitSimulations"] = exits
        rules = payload.get("exitSimulationRules")
        if isinstance(rules, dict):
            rules["missingDepthFallback"] = (
                "UPPER_BOUND_NO_DEPTH: all signed-entry shares at recorded exit-signal Bid; "
                "explicit optimistic bound, never labelled as observed full liquidity"
            )
            rules["exactExitPriceSource"] = "cross_oracle_strategy_trades.exit_price at exit signal"
            rules["legacySellRowsMigrated"] = True
        return payload
